// Generated by delombok at Thu Jul 16 14:07:14 IST 2026
package com.travelcarry.ai.controller;

import com.travelcarry.ai.entity.CarbonSavings;
import com.travelcarry.ai.entity.User;
import com.travelcarry.ai.entity.UserBadge;
import com.travelcarry.ai.exception.ResourceNotFoundException;
import com.travelcarry.ai.repository.CarbonSavingsRepository;
import com.travelcarry.ai.repository.UserBadgeRepository;
import com.travelcarry.ai.repository.UserRepository;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.stream.Collectors;

@RestController
@RequestMapping("/api/analytics")
public class AnalyticsController {
    private final CarbonSavingsRepository carbonSavingsRepository;
    private final UserBadgeRepository userBadgeRepository;
    private final UserRepository userRepository;

    @GetMapping("/user/{userId}/carbon")
    public ResponseEntity<CarbonSavings> getCarbonSavings(@PathVariable UUID userId) {
        CarbonSavings savings = carbonSavingsRepository.findByUserId(userId).orElseThrow(() -> new ResourceNotFoundException("Carbon statistics not found for user: " + userId));
        return ResponseEntity.ok(savings);
    }

    @GetMapping("/user/{userId}/badges")
    public ResponseEntity<List<Map<String, Object>>> getUserBadges(@PathVariable UUID userId) {
        List<UserBadge> badges = userBadgeRepository.findByUserId(userId);
        List<Map<String, Object>> response = badges.stream().map(ub -> {
            Map<String, Object> map = new HashMap<>();
            map.put("badgeName", ub.getBadge().getBadgeName());
            map.put("description", ub.getBadge().getBadgeDescription());
            map.put("iconUrl", ub.getBadge().getIconUrl());
            map.put("awardedAt", ub.getAwardedAt());
            return map;
        }).collect(Collectors.toList());
        return ResponseEntity.ok(response);
    }

    @GetMapping("/user/{userId}/profile-summary")
    public ResponseEntity<Map<String, Object>> getProfileSummary(@PathVariable UUID userId) {
        User user = userRepository.findById(userId).orElseThrow(() -> new ResourceNotFoundException("User not found"));
        CarbonSavings carbon = carbonSavingsRepository.findByUserId(userId).orElse(null);
        List<UserBadge> badges = userBadgeRepository.findByUserId(userId);
        Map<String, Object> summary = new HashMap<>();
        summary.put("userId", user.getId());
        summary.put("firstName", user.getFirstName());
        summary.put("lastName", user.getLastName());
        summary.put("email", user.getEmail());
        summary.put("role", user.getRole());
        summary.put("rating", user.getRating());
        summary.put("trustScore", user.getTrustScore());
        summary.put("trustLevel", user.getTrustLevel());
        summary.put("completedDeliveries", user.getCompletedDeliveries());
        summary.put("co2SavedKg", carbon != null ? carbon.getCo2SavedKg() : 0);
        summary.put("fuelSavedLiters", carbon != null ? carbon.getFuelSavedLiters() : 0);
        summary.put("badgesCount", badges.size());
        return ResponseEntity.ok(summary);
    }

    @GetMapping("/admin/dashboard")
    public ResponseEntity<Map<String, Object>> getAdminDashboard() {
        long totalUsers = userRepository.count();
        // Return overall metrics
        Map<String, Object> stats = new HashMap<>();
        stats.put("totalUsers", totalUsers);
        stats.put("totalRevenueINR", 28400.0); // Sample stats
        stats.put("totalCO2SavedKg", 5840.5);
        stats.put("activeTripsCount", 12);
        stats.put("pendingParcelsCount", 8);
        return ResponseEntity.ok(stats);
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public AnalyticsController(final CarbonSavingsRepository carbonSavingsRepository, final UserBadgeRepository userBadgeRepository, final UserRepository userRepository) {
        this.carbonSavingsRepository = carbonSavingsRepository;
        this.userBadgeRepository = userBadgeRepository;
        this.userRepository = userRepository;
    }
}
