// Generated by delombok at Thu Jul 16 14:07:14 IST 2026
package com.travelcarry.ai.controller;

import com.travelcarry.ai.dto.AuthResponse;
import com.travelcarry.ai.dto.LoginRequest;
import com.travelcarry.ai.dto.RegisterRequest;
import com.travelcarry.ai.service.AuthService;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.HashMap;
import java.util.Map;

@RestController
@RequestMapping("/api/auth")
public class AuthController {
    private final AuthService authService;

    @PostMapping("/register")
    public ResponseEntity<AuthResponse> register(@Valid @RequestBody RegisterRequest request) {
        return ResponseEntity.ok(authService.register(request));
    }

    @PostMapping("/login")
    public ResponseEntity<AuthResponse> login(@Valid @RequestBody LoginRequest request) {
        return ResponseEntity.ok(authService.login(request));
    }

    @PostMapping("/otp/send")
    public ResponseEntity<Map<String, String>> sendOtp(@RequestParam String contact, @RequestParam String purpose) {
        String code = authService.generateOtp(contact, purpose);
        Map<String, String> response = new HashMap<>();
        response.put("message", "OTP sent successfully");
        response.put("otp_code_dev_mock", code); // For local developer ease
        return ResponseEntity.ok(response);
    }

    @PostMapping("/otp/verify")
    public ResponseEntity<Map<String, Object>> verifyOtp(@RequestParam String contact, @RequestParam String code, @RequestParam String purpose) {
        boolean verified = authService.verifyOtp(contact, code, purpose);
        Map<String, Object> response = new HashMap<>();
        response.put("verified", verified);
        if (verified) {
            response.put("message", "OTP verified successfully");
            return ResponseEntity.ok(response);
        } else {
            response.put("message", "Invalid or expired OTP");
            return ResponseEntity.badRequest().body(response);
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public AuthController(final AuthService authService) {
        this.authService = authService;
    }
}
