// Generated by delombok at Thu Jul 16 14:07:14 IST 2026
package com.travelcarry.ai.controller;

import com.travelcarry.ai.dto.BookingDTO;
import com.travelcarry.ai.service.BookingService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.math.BigDecimal;
import java.util.List;
import java.util.UUID;

@RestController
@RequestMapping("/api/bookings")
public class BookingController {
    private final BookingService bookingService;

    @PostMapping
    public ResponseEntity<BookingDTO> createBooking(@RequestParam UUID tripId, @RequestParam UUID parcelId, @RequestParam BigDecimal price) {
        return ResponseEntity.ok(bookingService.createBooking(tripId, parcelId, price));
    }

    @GetMapping("/{id}")
    public ResponseEntity<BookingDTO> getBookingById(@PathVariable UUID id) {
        return ResponseEntity.ok(bookingService.getBookingById(id));
    }

    @PutMapping("/{id}/accept")
    public ResponseEntity<BookingDTO> acceptBooking(@PathVariable UUID id) {
        return ResponseEntity.ok(bookingService.acceptBooking(id));
    }

    @PostMapping("/{id}/verify-pickup")
    public ResponseEntity<BookingDTO> verifyPickup(@PathVariable UUID id, @RequestParam String otp) {
        return ResponseEntity.ok(bookingService.verifyPickup(id, otp));
    }

    @PostMapping("/{id}/verify-delivery")
    public ResponseEntity<BookingDTO> verifyDelivery(@PathVariable UUID id, @RequestParam String otp) {
        return ResponseEntity.ok(bookingService.verifyDelivery(id, otp));
    }

    @GetMapping("/traveler/{travelerId}")
    public ResponseEntity<List<BookingDTO>> getBookingsForTraveler(@PathVariable UUID travelerId) {
        return ResponseEntity.ok(bookingService.getBookingsForTraveler(travelerId));
    }

    @GetMapping("/sender/{senderId}")
    public ResponseEntity<List<BookingDTO>> getBookingsForSender(@PathVariable UUID senderId) {
        return ResponseEntity.ok(bookingService.getBookingsForSender(senderId));
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BookingController(final BookingService bookingService) {
        this.bookingService = bookingService;
    }
}
