// Generated by delombok at Thu Jul 16 14:07:14 IST 2026
package com.travelcarry.ai.controller;

import com.travelcarry.ai.dto.ChatDTO;
import com.travelcarry.ai.dto.MessageDTO;
import com.travelcarry.ai.service.ChatService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.List;
import java.util.UUID;

@RestController
@RequestMapping("/api/chats")
public class ChatController {
    private final ChatService chatService;

    @GetMapping("/booking/{bookingId}")
    public ResponseEntity<ChatDTO> getChatByBooking(@PathVariable UUID bookingId) {
        return ResponseEntity.ok(chatService.getOrInitializeChat(bookingId));
    }

    @PostMapping("/{chatId}/messages")
    public ResponseEntity<MessageDTO> sendMessage(@PathVariable UUID chatId, @RequestParam UUID senderId, @RequestBody String messageText) {
        // Strip extra quotes if any from raw request body
        String text = messageText;
        if (text.startsWith("\"") && text.endsWith("\"") && text.length() > 1) {
            text = text.substring(1, text.length() - 1);
        }
        return ResponseEntity.ok(chatService.sendMessage(chatId, senderId, text));
    }

    @GetMapping("/{chatId}/messages")
    public ResponseEntity<List<MessageDTO>> getMessages(@PathVariable UUID chatId) {
        return ResponseEntity.ok(chatService.getMessages(chatId));
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ChatController(final ChatService chatService) {
        this.chatService = chatService;
    }
}
