// Generated by delombok at Thu Jul 16 14:07:14 IST 2026
package com.travelcarry.ai.controller;

import com.travelcarry.ai.dto.ParcelDTO;
import com.travelcarry.ai.service.AIService;
import com.travelcarry.ai.service.ParcelService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.List;
import java.util.UUID;

@RestController
@RequestMapping("/api/parcels")
public class ParcelController {
    private final ParcelService parcelService;
    private final AIService aiService;

    @PostMapping
    public ResponseEntity<ParcelDTO> createParcel(@RequestBody ParcelDTO dto, @RequestParam UUID senderId) {
        return ResponseEntity.ok(parcelService.createParcel(dto, senderId));
    }

    @GetMapping("/{id}")
    public ResponseEntity<ParcelDTO> getParcelById(@PathVariable UUID id) {
        return ResponseEntity.ok(parcelService.getParcelById(id));
    }

    @GetMapping("/sender/{senderId}")
    public ResponseEntity<List<ParcelDTO>> getParcelsBySender(@PathVariable UUID senderId) {
        return ResponseEntity.ok(parcelService.getParcelsBySender(senderId));
    }

    // AI Endpoints
    @GetMapping("/{id}/ai-matches")
    public ResponseEntity<List<AIService.MatchResult>> getAIMatches(@PathVariable UUID id) {
        ParcelDTO parcel = parcelService.getParcelById(id);
        List<AIService.MatchResult> matches = aiService.getTravelerMatches(parcel.getStartCity(), parcel.getEndCity(), parcel.getWeightKg().doubleValue(), parcel.getCategory());
        return ResponseEntity.ok(matches);
    }

    @GetMapping("/ai-pricing")
    public ResponseEntity<AIService.PricePrediction> getAIPricing(@RequestParam String startCity, @RequestParam String endCity, @RequestParam double weightKg, @RequestParam String priority) {
        return ResponseEntity.ok(aiService.predictPricing(startCity, endCity, weightKg, priority));
    }

    @GetMapping("/ai-safety")
    public ResponseEntity<AIService.SafetyScanResult> scanSafety(@RequestParam String category, @RequestParam String description) {
        return ResponseEntity.ok(aiService.scanParcelSafety(category, description));
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ParcelController(final ParcelService parcelService, final AIService aiService) {
        this.parcelService = parcelService;
        this.aiService = aiService;
    }
}
