// Generated by delombok at Thu Jul 16 14:07:14 IST 2026
package com.travelcarry.ai.controller;

import com.travelcarry.ai.dto.TrackingDTO;
import com.travelcarry.ai.service.TrackingService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.math.BigDecimal;
import java.util.UUID;

@RestController
@RequestMapping("/api/tracking")
public class TrackingController {
    private final TrackingService trackingService;

    @GetMapping("/booking/{bookingId}")
    public ResponseEntity<TrackingDTO> getTracking(@PathVariable UUID bookingId) {
        return ResponseEntity.ok(trackingService.getOrInitializeTracking(bookingId));
    }

    @PutMapping("/booking/{bookingId}/location")
    public ResponseEntity<TrackingDTO> updateLocation(@PathVariable UUID bookingId, @RequestParam BigDecimal latitude, @RequestParam BigDecimal longitude, @RequestParam(required = false) String statusDescription) {
        return ResponseEntity.ok(trackingService.updateLocation(bookingId, latitude, longitude, statusDescription));
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public TrackingController(final TrackingService trackingService) {
        this.trackingService = trackingService;
    }
}
