// Generated by delombok at Thu Jul 16 14:07:14 IST 2026
package com.travelcarry.ai.controller;

import com.travelcarry.ai.dto.TripDTO;
import com.travelcarry.ai.service.TripService;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;
import java.util.List;
import java.util.UUID;

@RestController
@RequestMapping("/api/trips")
public class TripController {
    private final TripService tripService;

    @PostMapping
    public ResponseEntity<TripDTO> createTrip(@RequestBody TripDTO dto, @RequestParam UUID travelerId) {
        return ResponseEntity.ok(tripService.createTrip(dto, travelerId));
    }

    @GetMapping("/{id}")
    public ResponseEntity<TripDTO> getTripById(@PathVariable UUID id) {
        return ResponseEntity.ok(tripService.getTripById(id));
    }

    @GetMapping("/traveler/{travelerId}")
    public ResponseEntity<List<TripDTO>> getTripsByTraveler(@PathVariable UUID travelerId) {
        return ResponseEntity.ok(tripService.getTripsByTraveler(travelerId));
    }

    @GetMapping("/search")
    public ResponseEntity<List<TripDTO>> searchTrips(@RequestParam String startCity, @RequestParam String endCity) {
        return ResponseEntity.ok(tripService.searchTrips(startCity, endCity));
    }

    @PutMapping("/{id}/status")
    public ResponseEntity<TripDTO> updateTripStatus(@PathVariable UUID id, @RequestParam String status) {
        return ResponseEntity.ok(tripService.updateTripStatus(id, status));
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public TripController(final TripService tripService) {
        this.tripService = tripService;
    }
}
