// Generated by delombok at Thu Jul 16 14:07:14 IST 2026
package com.travelcarry.ai.controller;

import com.travelcarry.ai.dto.WalletDTO;
import com.travelcarry.ai.service.WalletService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.math.BigDecimal;
import java.util.UUID;

@RestController
@RequestMapping("/api/wallets")
public class WalletController {
    private final WalletService walletService;

    @GetMapping("/user/{userId}")
    public ResponseEntity<WalletDTO> getWalletByUser(@PathVariable UUID userId) {
        return ResponseEntity.ok(walletService.getWalletByUser(userId));
    }

    @PostMapping("/user/{userId}/deposit")
    public ResponseEntity<WalletDTO> deposit(@PathVariable UUID userId, @RequestParam BigDecimal amount, @RequestParam String description) {
        return ResponseEntity.ok(walletService.addFunds(userId, amount, description));
    }

    @PostMapping("/user/{userId}/withdraw")
    public ResponseEntity<WalletDTO> withdraw(@PathVariable UUID userId, @RequestParam BigDecimal amount, @RequestParam String description) {
        return ResponseEntity.ok(walletService.withdrawFunds(userId, amount, description));
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public WalletController(final WalletService walletService) {
        this.walletService = walletService;
    }
}
