// Generated by delombok at Thu Jul 16 14:07:14 IST 2026
package com.travelcarry.ai.entity;

import jakarta.persistence.*;
import lombok.*;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

@Entity
@Table(name = "ai_predictions")
public class AIPrediction {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "parcel_id")
    private Parcel parcel;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "trip_id")
    private Trip trip;
    @Column(name = "match_confidence_score", precision = 5, scale = 2)
    private BigDecimal matchConfidenceScore;
    @Column(name = "predicted_price_min", precision = 10, scale = 2)
    private BigDecimal predictedPriceMin;
    @Column(name = "predicted_price_rec", precision = 10, scale = 2)
    private BigDecimal predictedPriceRec;
    @Column(name = "predicted_price_prem", precision = 10, scale = 2)
    private BigDecimal predictedPricePrem;
    @Column(name = "trust_score")
    private Integer trustScore;
    @Column(name = "fraud_risk_score", precision = 5, scale = 2)
    private BigDecimal fraudRiskScore;
    @Column(name = "delay_probability", precision = 5, scale = 2)
    private BigDecimal delayProbability;
    @Column(name = "created_at", updatable = false)
    private OffsetDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        createdAt = OffsetDateTime.now();
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class AIPredictionBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UUID id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Parcel parcel;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Trip trip;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal matchConfidenceScore;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal predictedPriceMin;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal predictedPriceRec;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal predictedPricePrem;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Integer trustScore;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal fraudRiskScore;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal delayProbability;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private OffsetDateTime createdAt;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        AIPredictionBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public AIPrediction.AIPredictionBuilder id(final UUID id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public AIPrediction.AIPredictionBuilder parcel(final Parcel parcel) {
            this.parcel = parcel;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public AIPrediction.AIPredictionBuilder trip(final Trip trip) {
            this.trip = trip;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public AIPrediction.AIPredictionBuilder matchConfidenceScore(final BigDecimal matchConfidenceScore) {
            this.matchConfidenceScore = matchConfidenceScore;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public AIPrediction.AIPredictionBuilder predictedPriceMin(final BigDecimal predictedPriceMin) {
            this.predictedPriceMin = predictedPriceMin;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public AIPrediction.AIPredictionBuilder predictedPriceRec(final BigDecimal predictedPriceRec) {
            this.predictedPriceRec = predictedPriceRec;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public AIPrediction.AIPredictionBuilder predictedPricePrem(final BigDecimal predictedPricePrem) {
            this.predictedPricePrem = predictedPricePrem;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public AIPrediction.AIPredictionBuilder trustScore(final Integer trustScore) {
            this.trustScore = trustScore;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public AIPrediction.AIPredictionBuilder fraudRiskScore(final BigDecimal fraudRiskScore) {
            this.fraudRiskScore = fraudRiskScore;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public AIPrediction.AIPredictionBuilder delayProbability(final BigDecimal delayProbability) {
            this.delayProbability = delayProbability;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public AIPrediction.AIPredictionBuilder createdAt(final OffsetDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public AIPrediction build() {
            return new AIPrediction(this.id, this.parcel, this.trip, this.matchConfidenceScore, this.predictedPriceMin, this.predictedPriceRec, this.predictedPricePrem, this.trustScore, this.fraudRiskScore, this.delayProbability, this.createdAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "AIPrediction.AIPredictionBuilder(id=" + this.id + ", parcel=" + this.parcel + ", trip=" + this.trip + ", matchConfidenceScore=" + this.matchConfidenceScore + ", predictedPriceMin=" + this.predictedPriceMin + ", predictedPriceRec=" + this.predictedPriceRec + ", predictedPricePrem=" + this.predictedPricePrem + ", trustScore=" + this.trustScore + ", fraudRiskScore=" + this.fraudRiskScore + ", delayProbability=" + this.delayProbability + ", createdAt=" + this.createdAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static AIPrediction.AIPredictionBuilder builder() {
        return new AIPrediction.AIPredictionBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UUID getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Parcel getParcel() {
        return this.parcel;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Trip getTrip() {
        return this.trip;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getMatchConfidenceScore() {
        return this.matchConfidenceScore;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getPredictedPriceMin() {
        return this.predictedPriceMin;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getPredictedPriceRec() {
        return this.predictedPriceRec;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getPredictedPricePrem() {
        return this.predictedPricePrem;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getTrustScore() {
        return this.trustScore;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getFraudRiskScore() {
        return this.fraudRiskScore;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getDelayProbability() {
        return this.delayProbability;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final UUID id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setParcel(final Parcel parcel) {
        this.parcel = parcel;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTrip(final Trip trip) {
        this.trip = trip;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMatchConfidenceScore(final BigDecimal matchConfidenceScore) {
        this.matchConfidenceScore = matchConfidenceScore;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPredictedPriceMin(final BigDecimal predictedPriceMin) {
        this.predictedPriceMin = predictedPriceMin;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPredictedPriceRec(final BigDecimal predictedPriceRec) {
        this.predictedPriceRec = predictedPriceRec;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPredictedPricePrem(final BigDecimal predictedPricePrem) {
        this.predictedPricePrem = predictedPricePrem;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTrustScore(final Integer trustScore) {
        this.trustScore = trustScore;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFraudRiskScore(final BigDecimal fraudRiskScore) {
        this.fraudRiskScore = fraudRiskScore;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDelayProbability(final BigDecimal delayProbability) {
        this.delayProbability = delayProbability;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AIPrediction)) return false;
        final AIPrediction other = (AIPrediction) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$trustScore = this.getTrustScore();
        final java.lang.Object other$trustScore = other.getTrustScore();
        if (this$trustScore == null ? other$trustScore != null : !this$trustScore.equals(other$trustScore)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$parcel = this.getParcel();
        final java.lang.Object other$parcel = other.getParcel();
        if (this$parcel == null ? other$parcel != null : !this$parcel.equals(other$parcel)) return false;
        final java.lang.Object this$trip = this.getTrip();
        final java.lang.Object other$trip = other.getTrip();
        if (this$trip == null ? other$trip != null : !this$trip.equals(other$trip)) return false;
        final java.lang.Object this$matchConfidenceScore = this.getMatchConfidenceScore();
        final java.lang.Object other$matchConfidenceScore = other.getMatchConfidenceScore();
        if (this$matchConfidenceScore == null ? other$matchConfidenceScore != null : !this$matchConfidenceScore.equals(other$matchConfidenceScore)) return false;
        final java.lang.Object this$predictedPriceMin = this.getPredictedPriceMin();
        final java.lang.Object other$predictedPriceMin = other.getPredictedPriceMin();
        if (this$predictedPriceMin == null ? other$predictedPriceMin != null : !this$predictedPriceMin.equals(other$predictedPriceMin)) return false;
        final java.lang.Object this$predictedPriceRec = this.getPredictedPriceRec();
        final java.lang.Object other$predictedPriceRec = other.getPredictedPriceRec();
        if (this$predictedPriceRec == null ? other$predictedPriceRec != null : !this$predictedPriceRec.equals(other$predictedPriceRec)) return false;
        final java.lang.Object this$predictedPricePrem = this.getPredictedPricePrem();
        final java.lang.Object other$predictedPricePrem = other.getPredictedPricePrem();
        if (this$predictedPricePrem == null ? other$predictedPricePrem != null : !this$predictedPricePrem.equals(other$predictedPricePrem)) return false;
        final java.lang.Object this$fraudRiskScore = this.getFraudRiskScore();
        final java.lang.Object other$fraudRiskScore = other.getFraudRiskScore();
        if (this$fraudRiskScore == null ? other$fraudRiskScore != null : !this$fraudRiskScore.equals(other$fraudRiskScore)) return false;
        final java.lang.Object this$delayProbability = this.getDelayProbability();
        final java.lang.Object other$delayProbability = other.getDelayProbability();
        if (this$delayProbability == null ? other$delayProbability != null : !this$delayProbability.equals(other$delayProbability)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AIPrediction;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $trustScore = this.getTrustScore();
        result = result * PRIME + ($trustScore == null ? 43 : $trustScore.hashCode());
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $parcel = this.getParcel();
        result = result * PRIME + ($parcel == null ? 43 : $parcel.hashCode());
        final java.lang.Object $trip = this.getTrip();
        result = result * PRIME + ($trip == null ? 43 : $trip.hashCode());
        final java.lang.Object $matchConfidenceScore = this.getMatchConfidenceScore();
        result = result * PRIME + ($matchConfidenceScore == null ? 43 : $matchConfidenceScore.hashCode());
        final java.lang.Object $predictedPriceMin = this.getPredictedPriceMin();
        result = result * PRIME + ($predictedPriceMin == null ? 43 : $predictedPriceMin.hashCode());
        final java.lang.Object $predictedPriceRec = this.getPredictedPriceRec();
        result = result * PRIME + ($predictedPriceRec == null ? 43 : $predictedPriceRec.hashCode());
        final java.lang.Object $predictedPricePrem = this.getPredictedPricePrem();
        result = result * PRIME + ($predictedPricePrem == null ? 43 : $predictedPricePrem.hashCode());
        final java.lang.Object $fraudRiskScore = this.getFraudRiskScore();
        result = result * PRIME + ($fraudRiskScore == null ? 43 : $fraudRiskScore.hashCode());
        final java.lang.Object $delayProbability = this.getDelayProbability();
        result = result * PRIME + ($delayProbability == null ? 43 : $delayProbability.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "AIPrediction(id=" + this.getId() + ", parcel=" + this.getParcel() + ", trip=" + this.getTrip() + ", matchConfidenceScore=" + this.getMatchConfidenceScore() + ", predictedPriceMin=" + this.getPredictedPriceMin() + ", predictedPriceRec=" + this.getPredictedPriceRec() + ", predictedPricePrem=" + this.getPredictedPricePrem() + ", trustScore=" + this.getTrustScore() + ", fraudRiskScore=" + this.getFraudRiskScore() + ", delayProbability=" + this.getDelayProbability() + ", createdAt=" + this.getCreatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public AIPrediction() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public AIPrediction(final UUID id, final Parcel parcel, final Trip trip, final BigDecimal matchConfidenceScore, final BigDecimal predictedPriceMin, final BigDecimal predictedPriceRec, final BigDecimal predictedPricePrem, final Integer trustScore, final BigDecimal fraudRiskScore, final BigDecimal delayProbability, final OffsetDateTime createdAt) {
        this.id = id;
        this.parcel = parcel;
        this.trip = trip;
        this.matchConfidenceScore = matchConfidenceScore;
        this.predictedPriceMin = predictedPriceMin;
        this.predictedPriceRec = predictedPriceRec;
        this.predictedPricePrem = predictedPricePrem;
        this.trustScore = trustScore;
        this.fraudRiskScore = fraudRiskScore;
        this.delayProbability = delayProbability;
        this.createdAt = createdAt;
    }
}
