// Generated by delombok at Thu Jul 16 14:07:14 IST 2026
package com.travelcarry.ai.entity;

import jakarta.persistence.*;
import lombok.*;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

@Entity
@Table(name = "bookings")
public class Booking {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "parcel_id", nullable = false, unique = true)
    private Parcel parcel;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "trip_id", nullable = false)
    private Trip trip;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "traveler_id", nullable = false)
    private User traveler;
    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal price;
    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal commission;
    @Column(name = "base_price", nullable = false, precision = 10, scale = 2)
    private BigDecimal basePrice;
    @Column(name = "pickup_otp")
    private String pickupOtp;
    @Column(name = "delivery_otp")
    private String deliveryOtp;
    @Column(nullable = false)
    private String status; // PENDING, ACCEPTED, REJECTED, PICKED_UP, DELIVERED, CANCELLED
    @Column(name = "created_at", updatable = false)
    private OffsetDateTime createdAt;
    @Column(name = "updated_at")
    private OffsetDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        createdAt = OffsetDateTime.now();
        updatedAt = OffsetDateTime.now();
        if (status == null) status = "PENDING";
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = OffsetDateTime.now();
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class BookingBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UUID id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Parcel parcel;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Trip trip;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private User traveler;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal price;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal commission;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal basePrice;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String pickupOtp;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String deliveryOtp;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String status;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private OffsetDateTime createdAt;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private OffsetDateTime updatedAt;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        BookingBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Booking.BookingBuilder id(final UUID id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Booking.BookingBuilder parcel(final Parcel parcel) {
            this.parcel = parcel;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Booking.BookingBuilder trip(final Trip trip) {
            this.trip = trip;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Booking.BookingBuilder traveler(final User traveler) {
            this.traveler = traveler;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Booking.BookingBuilder price(final BigDecimal price) {
            this.price = price;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Booking.BookingBuilder commission(final BigDecimal commission) {
            this.commission = commission;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Booking.BookingBuilder basePrice(final BigDecimal basePrice) {
            this.basePrice = basePrice;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Booking.BookingBuilder pickupOtp(final String pickupOtp) {
            this.pickupOtp = pickupOtp;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Booking.BookingBuilder deliveryOtp(final String deliveryOtp) {
            this.deliveryOtp = deliveryOtp;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Booking.BookingBuilder status(final String status) {
            this.status = status;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Booking.BookingBuilder createdAt(final OffsetDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Booking.BookingBuilder updatedAt(final OffsetDateTime updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Booking build() {
            return new Booking(this.id, this.parcel, this.trip, this.traveler, this.price, this.commission, this.basePrice, this.pickupOtp, this.deliveryOtp, this.status, this.createdAt, this.updatedAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "Booking.BookingBuilder(id=" + this.id + ", parcel=" + this.parcel + ", trip=" + this.trip + ", traveler=" + this.traveler + ", price=" + this.price + ", commission=" + this.commission + ", basePrice=" + this.basePrice + ", pickupOtp=" + this.pickupOtp + ", deliveryOtp=" + this.deliveryOtp + ", status=" + this.status + ", createdAt=" + this.createdAt + ", updatedAt=" + this.updatedAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static Booking.BookingBuilder builder() {
        return new Booking.BookingBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UUID getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Parcel getParcel() {
        return this.parcel;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Trip getTrip() {
        return this.trip;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public User getTraveler() {
        return this.traveler;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getPrice() {
        return this.price;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getCommission() {
        return this.commission;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getBasePrice() {
        return this.basePrice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPickupOtp() {
        return this.pickupOtp;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDeliveryOtp() {
        return this.deliveryOtp;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final UUID id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setParcel(final Parcel parcel) {
        this.parcel = parcel;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTrip(final Trip trip) {
        this.trip = trip;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTraveler(final User traveler) {
        this.traveler = traveler;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPrice(final BigDecimal price) {
        this.price = price;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCommission(final BigDecimal commission) {
        this.commission = commission;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBasePrice(final BigDecimal basePrice) {
        this.basePrice = basePrice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPickupOtp(final String pickupOtp) {
        this.pickupOtp = pickupOtp;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDeliveryOtp(final String deliveryOtp) {
        this.deliveryOtp = deliveryOtp;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUpdatedAt(final OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Booking)) return false;
        final Booking other = (Booking) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$parcel = this.getParcel();
        final java.lang.Object other$parcel = other.getParcel();
        if (this$parcel == null ? other$parcel != null : !this$parcel.equals(other$parcel)) return false;
        final java.lang.Object this$trip = this.getTrip();
        final java.lang.Object other$trip = other.getTrip();
        if (this$trip == null ? other$trip != null : !this$trip.equals(other$trip)) return false;
        final java.lang.Object this$traveler = this.getTraveler();
        final java.lang.Object other$traveler = other.getTraveler();
        if (this$traveler == null ? other$traveler != null : !this$traveler.equals(other$traveler)) return false;
        final java.lang.Object this$price = this.getPrice();
        final java.lang.Object other$price = other.getPrice();
        if (this$price == null ? other$price != null : !this$price.equals(other$price)) return false;
        final java.lang.Object this$commission = this.getCommission();
        final java.lang.Object other$commission = other.getCommission();
        if (this$commission == null ? other$commission != null : !this$commission.equals(other$commission)) return false;
        final java.lang.Object this$basePrice = this.getBasePrice();
        final java.lang.Object other$basePrice = other.getBasePrice();
        if (this$basePrice == null ? other$basePrice != null : !this$basePrice.equals(other$basePrice)) return false;
        final java.lang.Object this$pickupOtp = this.getPickupOtp();
        final java.lang.Object other$pickupOtp = other.getPickupOtp();
        if (this$pickupOtp == null ? other$pickupOtp != null : !this$pickupOtp.equals(other$pickupOtp)) return false;
        final java.lang.Object this$deliveryOtp = this.getDeliveryOtp();
        final java.lang.Object other$deliveryOtp = other.getDeliveryOtp();
        if (this$deliveryOtp == null ? other$deliveryOtp != null : !this$deliveryOtp.equals(other$deliveryOtp)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        final java.lang.Object this$updatedAt = this.getUpdatedAt();
        final java.lang.Object other$updatedAt = other.getUpdatedAt();
        if (this$updatedAt == null ? other$updatedAt != null : !this$updatedAt.equals(other$updatedAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Booking;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $parcel = this.getParcel();
        result = result * PRIME + ($parcel == null ? 43 : $parcel.hashCode());
        final java.lang.Object $trip = this.getTrip();
        result = result * PRIME + ($trip == null ? 43 : $trip.hashCode());
        final java.lang.Object $traveler = this.getTraveler();
        result = result * PRIME + ($traveler == null ? 43 : $traveler.hashCode());
        final java.lang.Object $price = this.getPrice();
        result = result * PRIME + ($price == null ? 43 : $price.hashCode());
        final java.lang.Object $commission = this.getCommission();
        result = result * PRIME + ($commission == null ? 43 : $commission.hashCode());
        final java.lang.Object $basePrice = this.getBasePrice();
        result = result * PRIME + ($basePrice == null ? 43 : $basePrice.hashCode());
        final java.lang.Object $pickupOtp = this.getPickupOtp();
        result = result * PRIME + ($pickupOtp == null ? 43 : $pickupOtp.hashCode());
        final java.lang.Object $deliveryOtp = this.getDeliveryOtp();
        result = result * PRIME + ($deliveryOtp == null ? 43 : $deliveryOtp.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        final java.lang.Object $updatedAt = this.getUpdatedAt();
        result = result * PRIME + ($updatedAt == null ? 43 : $updatedAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "Booking(id=" + this.getId() + ", parcel=" + this.getParcel() + ", trip=" + this.getTrip() + ", traveler=" + this.getTraveler() + ", price=" + this.getPrice() + ", commission=" + this.getCommission() + ", basePrice=" + this.getBasePrice() + ", pickupOtp=" + this.getPickupOtp() + ", deliveryOtp=" + this.getDeliveryOtp() + ", status=" + this.getStatus() + ", createdAt=" + this.getCreatedAt() + ", updatedAt=" + this.getUpdatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Booking() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Booking(final UUID id, final Parcel parcel, final Trip trip, final User traveler, final BigDecimal price, final BigDecimal commission, final BigDecimal basePrice, final String pickupOtp, final String deliveryOtp, final String status, final OffsetDateTime createdAt, final OffsetDateTime updatedAt) {
        this.id = id;
        this.parcel = parcel;
        this.trip = trip;
        this.traveler = traveler;
        this.price = price;
        this.commission = commission;
        this.basePrice = basePrice;
        this.pickupOtp = pickupOtp;
        this.deliveryOtp = deliveryOtp;
        this.status = status;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
}
