// Generated by delombok at Thu Jul 16 14:07:14 IST 2026
package com.travelcarry.ai.entity;

import jakarta.persistence.*;
import lombok.*;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

@Entity
@Table(name = "carbon_savings")
public class CarbonSavings {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false, unique = true)
    private User user;
    @Column(name = "co2_saved_kg", precision = 10, scale = 2)
    private BigDecimal co2SavedKg;
    @Column(name = "fuel_saved_liters", precision = 10, scale = 2)
    private BigDecimal fuelSavedLiters;
    @Column(name = "total_trips_shared")
    private Integer totalTripsShared;
    @Column(name = "updated_at")
    private OffsetDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        updatedAt = OffsetDateTime.now();
        if (co2SavedKg == null) co2SavedKg = BigDecimal.ZERO;
        if (fuelSavedLiters == null) fuelSavedLiters = BigDecimal.ZERO;
        if (totalTripsShared == null) totalTripsShared = 0;
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = OffsetDateTime.now();
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class CarbonSavingsBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UUID id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private User user;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal co2SavedKg;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal fuelSavedLiters;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Integer totalTripsShared;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private OffsetDateTime updatedAt;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        CarbonSavingsBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CarbonSavings.CarbonSavingsBuilder id(final UUID id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CarbonSavings.CarbonSavingsBuilder user(final User user) {
            this.user = user;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CarbonSavings.CarbonSavingsBuilder co2SavedKg(final BigDecimal co2SavedKg) {
            this.co2SavedKg = co2SavedKg;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CarbonSavings.CarbonSavingsBuilder fuelSavedLiters(final BigDecimal fuelSavedLiters) {
            this.fuelSavedLiters = fuelSavedLiters;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CarbonSavings.CarbonSavingsBuilder totalTripsShared(final Integer totalTripsShared) {
            this.totalTripsShared = totalTripsShared;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CarbonSavings.CarbonSavingsBuilder updatedAt(final OffsetDateTime updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CarbonSavings build() {
            return new CarbonSavings(this.id, this.user, this.co2SavedKg, this.fuelSavedLiters, this.totalTripsShared, this.updatedAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "CarbonSavings.CarbonSavingsBuilder(id=" + this.id + ", user=" + this.user + ", co2SavedKg=" + this.co2SavedKg + ", fuelSavedLiters=" + this.fuelSavedLiters + ", totalTripsShared=" + this.totalTripsShared + ", updatedAt=" + this.updatedAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static CarbonSavings.CarbonSavingsBuilder builder() {
        return new CarbonSavings.CarbonSavingsBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UUID getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public User getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getCo2SavedKg() {
        return this.co2SavedKg;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getFuelSavedLiters() {
        return this.fuelSavedLiters;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getTotalTripsShared() {
        return this.totalTripsShared;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final UUID id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUser(final User user) {
        this.user = user;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCo2SavedKg(final BigDecimal co2SavedKg) {
        this.co2SavedKg = co2SavedKg;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFuelSavedLiters(final BigDecimal fuelSavedLiters) {
        this.fuelSavedLiters = fuelSavedLiters;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTotalTripsShared(final Integer totalTripsShared) {
        this.totalTripsShared = totalTripsShared;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUpdatedAt(final OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof CarbonSavings)) return false;
        final CarbonSavings other = (CarbonSavings) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$totalTripsShared = this.getTotalTripsShared();
        final java.lang.Object other$totalTripsShared = other.getTotalTripsShared();
        if (this$totalTripsShared == null ? other$totalTripsShared != null : !this$totalTripsShared.equals(other$totalTripsShared)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$user = this.getUser();
        final java.lang.Object other$user = other.getUser();
        if (this$user == null ? other$user != null : !this$user.equals(other$user)) return false;
        final java.lang.Object this$co2SavedKg = this.getCo2SavedKg();
        final java.lang.Object other$co2SavedKg = other.getCo2SavedKg();
        if (this$co2SavedKg == null ? other$co2SavedKg != null : !this$co2SavedKg.equals(other$co2SavedKg)) return false;
        final java.lang.Object this$fuelSavedLiters = this.getFuelSavedLiters();
        final java.lang.Object other$fuelSavedLiters = other.getFuelSavedLiters();
        if (this$fuelSavedLiters == null ? other$fuelSavedLiters != null : !this$fuelSavedLiters.equals(other$fuelSavedLiters)) return false;
        final java.lang.Object this$updatedAt = this.getUpdatedAt();
        final java.lang.Object other$updatedAt = other.getUpdatedAt();
        if (this$updatedAt == null ? other$updatedAt != null : !this$updatedAt.equals(other$updatedAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof CarbonSavings;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $totalTripsShared = this.getTotalTripsShared();
        result = result * PRIME + ($totalTripsShared == null ? 43 : $totalTripsShared.hashCode());
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $user = this.getUser();
        result = result * PRIME + ($user == null ? 43 : $user.hashCode());
        final java.lang.Object $co2SavedKg = this.getCo2SavedKg();
        result = result * PRIME + ($co2SavedKg == null ? 43 : $co2SavedKg.hashCode());
        final java.lang.Object $fuelSavedLiters = this.getFuelSavedLiters();
        result = result * PRIME + ($fuelSavedLiters == null ? 43 : $fuelSavedLiters.hashCode());
        final java.lang.Object $updatedAt = this.getUpdatedAt();
        result = result * PRIME + ($updatedAt == null ? 43 : $updatedAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "CarbonSavings(id=" + this.getId() + ", user=" + this.getUser() + ", co2SavedKg=" + this.getCo2SavedKg() + ", fuelSavedLiters=" + this.getFuelSavedLiters() + ", totalTripsShared=" + this.getTotalTripsShared() + ", updatedAt=" + this.getUpdatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public CarbonSavings() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public CarbonSavings(final UUID id, final User user, final BigDecimal co2SavedKg, final BigDecimal fuelSavedLiters, final Integer totalTripsShared, final OffsetDateTime updatedAt) {
        this.id = id;
        this.user = user;
        this.co2SavedKg = co2SavedKg;
        this.fuelSavedLiters = fuelSavedLiters;
        this.totalTripsShared = totalTripsShared;
        this.updatedAt = updatedAt;
    }
}
