// Generated by delombok at Thu Jul 16 14:07:14 IST 2026
package com.travelcarry.ai.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.OffsetDateTime;
import java.util.UUID;

@Entity
@Table(name = "chats")
public class Chat {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "booking_id", nullable = false, unique = true)
    private Booking booking;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "traveler_id", nullable = false)
    private User traveler;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sender_id", nullable = false)
    private User sender;
    @Column(name = "created_at", updatable = false)
    private OffsetDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        createdAt = OffsetDateTime.now();
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class ChatBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UUID id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Booking booking;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private User traveler;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private User sender;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private OffsetDateTime createdAt;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        ChatBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Chat.ChatBuilder id(final UUID id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Chat.ChatBuilder booking(final Booking booking) {
            this.booking = booking;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Chat.ChatBuilder traveler(final User traveler) {
            this.traveler = traveler;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Chat.ChatBuilder sender(final User sender) {
            this.sender = sender;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Chat.ChatBuilder createdAt(final OffsetDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Chat build() {
            return new Chat(this.id, this.booking, this.traveler, this.sender, this.createdAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "Chat.ChatBuilder(id=" + this.id + ", booking=" + this.booking + ", traveler=" + this.traveler + ", sender=" + this.sender + ", createdAt=" + this.createdAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static Chat.ChatBuilder builder() {
        return new Chat.ChatBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UUID getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Booking getBooking() {
        return this.booking;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public User getTraveler() {
        return this.traveler;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public User getSender() {
        return this.sender;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final UUID id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBooking(final Booking booking) {
        this.booking = booking;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTraveler(final User traveler) {
        this.traveler = traveler;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSender(final User sender) {
        this.sender = sender;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Chat)) return false;
        final Chat other = (Chat) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$booking = this.getBooking();
        final java.lang.Object other$booking = other.getBooking();
        if (this$booking == null ? other$booking != null : !this$booking.equals(other$booking)) return false;
        final java.lang.Object this$traveler = this.getTraveler();
        final java.lang.Object other$traveler = other.getTraveler();
        if (this$traveler == null ? other$traveler != null : !this$traveler.equals(other$traveler)) return false;
        final java.lang.Object this$sender = this.getSender();
        final java.lang.Object other$sender = other.getSender();
        if (this$sender == null ? other$sender != null : !this$sender.equals(other$sender)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Chat;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $booking = this.getBooking();
        result = result * PRIME + ($booking == null ? 43 : $booking.hashCode());
        final java.lang.Object $traveler = this.getTraveler();
        result = result * PRIME + ($traveler == null ? 43 : $traveler.hashCode());
        final java.lang.Object $sender = this.getSender();
        result = result * PRIME + ($sender == null ? 43 : $sender.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "Chat(id=" + this.getId() + ", booking=" + this.getBooking() + ", traveler=" + this.getTraveler() + ", sender=" + this.getSender() + ", createdAt=" + this.getCreatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Chat() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Chat(final UUID id, final Booking booking, final User traveler, final User sender, final OffsetDateTime createdAt) {
        this.id = id;
        this.booking = booking;
        this.traveler = traveler;
        this.sender = sender;
        this.createdAt = createdAt;
    }
}
