// Generated by delombok at Thu Jul 16 14:07:14 IST 2026
package com.travelcarry.ai.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.OffsetDateTime;
import java.util.UUID;

@Entity
@Table(name = "messages")
public class Message {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "chat_id", nullable = false)
    private Chat chat;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sender_id", nullable = false)
    private User sender;
    @Column(name = "message_text", nullable = false, columnDefinition = "TEXT")
    private String messageText;
    @Column(name = "is_read")
    private Boolean isRead;
    @Column(name = "created_at", updatable = false)
    private OffsetDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        createdAt = OffsetDateTime.now();
        if (isRead == null) isRead = false;
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class MessageBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UUID id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Chat chat;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private User sender;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String messageText;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Boolean isRead;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private OffsetDateTime createdAt;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        MessageBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Message.MessageBuilder id(final UUID id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Message.MessageBuilder chat(final Chat chat) {
            this.chat = chat;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Message.MessageBuilder sender(final User sender) {
            this.sender = sender;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Message.MessageBuilder messageText(final String messageText) {
            this.messageText = messageText;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Message.MessageBuilder isRead(final Boolean isRead) {
            this.isRead = isRead;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Message.MessageBuilder createdAt(final OffsetDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Message build() {
            return new Message(this.id, this.chat, this.sender, this.messageText, this.isRead, this.createdAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "Message.MessageBuilder(id=" + this.id + ", chat=" + this.chat + ", sender=" + this.sender + ", messageText=" + this.messageText + ", isRead=" + this.isRead + ", createdAt=" + this.createdAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static Message.MessageBuilder builder() {
        return new Message.MessageBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UUID getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Chat getChat() {
        return this.chat;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public User getSender() {
        return this.sender;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getMessageText() {
        return this.messageText;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Boolean getIsRead() {
        return this.isRead;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final UUID id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setChat(final Chat chat) {
        this.chat = chat;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSender(final User sender) {
        this.sender = sender;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMessageText(final String messageText) {
        this.messageText = messageText;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setIsRead(final Boolean isRead) {
        this.isRead = isRead;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Message)) return false;
        final Message other = (Message) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$isRead = this.getIsRead();
        final java.lang.Object other$isRead = other.getIsRead();
        if (this$isRead == null ? other$isRead != null : !this$isRead.equals(other$isRead)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$chat = this.getChat();
        final java.lang.Object other$chat = other.getChat();
        if (this$chat == null ? other$chat != null : !this$chat.equals(other$chat)) return false;
        final java.lang.Object this$sender = this.getSender();
        final java.lang.Object other$sender = other.getSender();
        if (this$sender == null ? other$sender != null : !this$sender.equals(other$sender)) return false;
        final java.lang.Object this$messageText = this.getMessageText();
        final java.lang.Object other$messageText = other.getMessageText();
        if (this$messageText == null ? other$messageText != null : !this$messageText.equals(other$messageText)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Message;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $isRead = this.getIsRead();
        result = result * PRIME + ($isRead == null ? 43 : $isRead.hashCode());
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $chat = this.getChat();
        result = result * PRIME + ($chat == null ? 43 : $chat.hashCode());
        final java.lang.Object $sender = this.getSender();
        result = result * PRIME + ($sender == null ? 43 : $sender.hashCode());
        final java.lang.Object $messageText = this.getMessageText();
        result = result * PRIME + ($messageText == null ? 43 : $messageText.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "Message(id=" + this.getId() + ", chat=" + this.getChat() + ", sender=" + this.getSender() + ", messageText=" + this.getMessageText() + ", isRead=" + this.getIsRead() + ", createdAt=" + this.getCreatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Message() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Message(final UUID id, final Chat chat, final User sender, final String messageText, final Boolean isRead, final OffsetDateTime createdAt) {
        this.id = id;
        this.chat = chat;
        this.sender = sender;
        this.messageText = messageText;
        this.isRead = isRead;
        this.createdAt = createdAt;
    }
}
