// Generated by delombok at Thu Jul 16 14:07:14 IST 2026
package com.travelcarry.ai.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.OffsetDateTime;
import java.util.UUID;

@Entity
@Table(name = "otps")
public class Otp {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;
    @Column(name = "phone_number")
    private String phoneNumber;
    private String email;
    @Column(name = "otp_code", nullable = false)
    private String otpCode;
    @Column(nullable = false)
    private String purpose; // LOGIN, PICKUP, DELIVERY
    @Column(name = "is_verified")
    private Boolean isVerified;
    @Column(name = "expires_at", nullable = false)
    private OffsetDateTime expiresAt;
    @Column(name = "created_at", updatable = false)
    private OffsetDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        createdAt = OffsetDateTime.now();
        if (isVerified == null) isVerified = false;
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class OtpBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UUID id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String phoneNumber;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String email;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String otpCode;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String purpose;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Boolean isVerified;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private OffsetDateTime expiresAt;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private OffsetDateTime createdAt;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        OtpBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Otp.OtpBuilder id(final UUID id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Otp.OtpBuilder phoneNumber(final String phoneNumber) {
            this.phoneNumber = phoneNumber;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Otp.OtpBuilder email(final String email) {
            this.email = email;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Otp.OtpBuilder otpCode(final String otpCode) {
            this.otpCode = otpCode;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Otp.OtpBuilder purpose(final String purpose) {
            this.purpose = purpose;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Otp.OtpBuilder isVerified(final Boolean isVerified) {
            this.isVerified = isVerified;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Otp.OtpBuilder expiresAt(final OffsetDateTime expiresAt) {
            this.expiresAt = expiresAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Otp.OtpBuilder createdAt(final OffsetDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Otp build() {
            return new Otp(this.id, this.phoneNumber, this.email, this.otpCode, this.purpose, this.isVerified, this.expiresAt, this.createdAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "Otp.OtpBuilder(id=" + this.id + ", phoneNumber=" + this.phoneNumber + ", email=" + this.email + ", otpCode=" + this.otpCode + ", purpose=" + this.purpose + ", isVerified=" + this.isVerified + ", expiresAt=" + this.expiresAt + ", createdAt=" + this.createdAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static Otp.OtpBuilder builder() {
        return new Otp.OtpBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UUID getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getOtpCode() {
        return this.otpCode;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPurpose() {
        return this.purpose;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Boolean getIsVerified() {
        return this.isVerified;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public OffsetDateTime getExpiresAt() {
        return this.expiresAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final UUID id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPhoneNumber(final String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEmail(final String email) {
        this.email = email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setOtpCode(final String otpCode) {
        this.otpCode = otpCode;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPurpose(final String purpose) {
        this.purpose = purpose;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setIsVerified(final Boolean isVerified) {
        this.isVerified = isVerified;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setExpiresAt(final OffsetDateTime expiresAt) {
        this.expiresAt = expiresAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Otp)) return false;
        final Otp other = (Otp) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$isVerified = this.getIsVerified();
        final java.lang.Object other$isVerified = other.getIsVerified();
        if (this$isVerified == null ? other$isVerified != null : !this$isVerified.equals(other$isVerified)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$phoneNumber = this.getPhoneNumber();
        final java.lang.Object other$phoneNumber = other.getPhoneNumber();
        if (this$phoneNumber == null ? other$phoneNumber != null : !this$phoneNumber.equals(other$phoneNumber)) return false;
        final java.lang.Object this$email = this.getEmail();
        final java.lang.Object other$email = other.getEmail();
        if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
        final java.lang.Object this$otpCode = this.getOtpCode();
        final java.lang.Object other$otpCode = other.getOtpCode();
        if (this$otpCode == null ? other$otpCode != null : !this$otpCode.equals(other$otpCode)) return false;
        final java.lang.Object this$purpose = this.getPurpose();
        final java.lang.Object other$purpose = other.getPurpose();
        if (this$purpose == null ? other$purpose != null : !this$purpose.equals(other$purpose)) return false;
        final java.lang.Object this$expiresAt = this.getExpiresAt();
        final java.lang.Object other$expiresAt = other.getExpiresAt();
        if (this$expiresAt == null ? other$expiresAt != null : !this$expiresAt.equals(other$expiresAt)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Otp;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $isVerified = this.getIsVerified();
        result = result * PRIME + ($isVerified == null ? 43 : $isVerified.hashCode());
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $phoneNumber = this.getPhoneNumber();
        result = result * PRIME + ($phoneNumber == null ? 43 : $phoneNumber.hashCode());
        final java.lang.Object $email = this.getEmail();
        result = result * PRIME + ($email == null ? 43 : $email.hashCode());
        final java.lang.Object $otpCode = this.getOtpCode();
        result = result * PRIME + ($otpCode == null ? 43 : $otpCode.hashCode());
        final java.lang.Object $purpose = this.getPurpose();
        result = result * PRIME + ($purpose == null ? 43 : $purpose.hashCode());
        final java.lang.Object $expiresAt = this.getExpiresAt();
        result = result * PRIME + ($expiresAt == null ? 43 : $expiresAt.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "Otp(id=" + this.getId() + ", phoneNumber=" + this.getPhoneNumber() + ", email=" + this.getEmail() + ", otpCode=" + this.getOtpCode() + ", purpose=" + this.getPurpose() + ", isVerified=" + this.getIsVerified() + ", expiresAt=" + this.getExpiresAt() + ", createdAt=" + this.getCreatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Otp() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Otp(final UUID id, final String phoneNumber, final String email, final String otpCode, final String purpose, final Boolean isVerified, final OffsetDateTime expiresAt, final OffsetDateTime createdAt) {
        this.id = id;
        this.phoneNumber = phoneNumber;
        this.email = email;
        this.otpCode = otpCode;
        this.purpose = purpose;
        this.isVerified = isVerified;
        this.expiresAt = expiresAt;
        this.createdAt = createdAt;
    }
}
