// Generated by delombok at Thu Jul 16 14:07:14 IST 2026
package com.travelcarry.ai.entity;

import jakarta.persistence.*;
import lombok.*;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

@Entity
@Table(name = "parcels")
public class Parcel {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sender_id", nullable = false)
    private User sender;
    @Column(nullable = false)
    private String title;
    @Column(columnDefinition = "TEXT")
    private String description;
    @Column(name = "weight_kg", nullable = false, precision = 6, scale = 2)
    private BigDecimal weightKg;
    @Column(name = "width_cm", precision = 6, scale = 2)
    private BigDecimal widthCm;
    @Column(name = "height_cm", precision = 6, scale = 2)
    private BigDecimal heightCm;
    @Column(name = "depth_cm", precision = 6, scale = 2)
    private BigDecimal depthCm;
    @Column(name = "start_city", nullable = false)
    private String startCity;
    @Column(name = "end_city", nullable = false)
    private String endCity;
    @Column(nullable = false)
    private String category; // ELECTRONICS, FRAGILE, FOOD, LIQUID, DOCUMENTS, REGULAR
    @Column(name = "risk_score")
    private Integer riskScore;
    @Column(name = "packing_recommendation", columnDefinition = "TEXT")
    private String packingRecommendation;
    private String priority; // REGULAR, EMERGENCY
    @Column(name = "image_url")
    private String imageUrl;
    @Column(nullable = false)
    private String status; // POSTED, MATCHED, IN_TRANSIT, DELIVERED, CANCELLED
    @Column(name = "created_at", updatable = false)
    private OffsetDateTime createdAt;
    @Column(name = "updated_at")
    private OffsetDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        createdAt = OffsetDateTime.now();
        updatedAt = OffsetDateTime.now();
        if (status == null) status = "POSTED";
        if (riskScore == null) riskScore = 0;
        if (priority == null) priority = "REGULAR";
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = OffsetDateTime.now();
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class ParcelBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UUID id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private User sender;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String title;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String description;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal weightKg;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal widthCm;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal heightCm;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal depthCm;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String startCity;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String endCity;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String category;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Integer riskScore;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String packingRecommendation;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String priority;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String imageUrl;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String status;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private OffsetDateTime createdAt;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private OffsetDateTime updatedAt;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        ParcelBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Parcel.ParcelBuilder id(final UUID id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Parcel.ParcelBuilder sender(final User sender) {
            this.sender = sender;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Parcel.ParcelBuilder title(final String title) {
            this.title = title;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Parcel.ParcelBuilder description(final String description) {
            this.description = description;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Parcel.ParcelBuilder weightKg(final BigDecimal weightKg) {
            this.weightKg = weightKg;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Parcel.ParcelBuilder widthCm(final BigDecimal widthCm) {
            this.widthCm = widthCm;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Parcel.ParcelBuilder heightCm(final BigDecimal heightCm) {
            this.heightCm = heightCm;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Parcel.ParcelBuilder depthCm(final BigDecimal depthCm) {
            this.depthCm = depthCm;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Parcel.ParcelBuilder startCity(final String startCity) {
            this.startCity = startCity;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Parcel.ParcelBuilder endCity(final String endCity) {
            this.endCity = endCity;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Parcel.ParcelBuilder category(final String category) {
            this.category = category;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Parcel.ParcelBuilder riskScore(final Integer riskScore) {
            this.riskScore = riskScore;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Parcel.ParcelBuilder packingRecommendation(final String packingRecommendation) {
            this.packingRecommendation = packingRecommendation;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Parcel.ParcelBuilder priority(final String priority) {
            this.priority = priority;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Parcel.ParcelBuilder imageUrl(final String imageUrl) {
            this.imageUrl = imageUrl;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Parcel.ParcelBuilder status(final String status) {
            this.status = status;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Parcel.ParcelBuilder createdAt(final OffsetDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Parcel.ParcelBuilder updatedAt(final OffsetDateTime updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Parcel build() {
            return new Parcel(this.id, this.sender, this.title, this.description, this.weightKg, this.widthCm, this.heightCm, this.depthCm, this.startCity, this.endCity, this.category, this.riskScore, this.packingRecommendation, this.priority, this.imageUrl, this.status, this.createdAt, this.updatedAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "Parcel.ParcelBuilder(id=" + this.id + ", sender=" + this.sender + ", title=" + this.title + ", description=" + this.description + ", weightKg=" + this.weightKg + ", widthCm=" + this.widthCm + ", heightCm=" + this.heightCm + ", depthCm=" + this.depthCm + ", startCity=" + this.startCity + ", endCity=" + this.endCity + ", category=" + this.category + ", riskScore=" + this.riskScore + ", packingRecommendation=" + this.packingRecommendation + ", priority=" + this.priority + ", imageUrl=" + this.imageUrl + ", status=" + this.status + ", createdAt=" + this.createdAt + ", updatedAt=" + this.updatedAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static Parcel.ParcelBuilder builder() {
        return new Parcel.ParcelBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UUID getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public User getSender() {
        return this.sender;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getWeightKg() {
        return this.weightKg;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getWidthCm() {
        return this.widthCm;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getHeightCm() {
        return this.heightCm;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getDepthCm() {
        return this.depthCm;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStartCity() {
        return this.startCity;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getEndCity() {
        return this.endCity;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCategory() {
        return this.category;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getRiskScore() {
        return this.riskScore;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPackingRecommendation() {
        return this.packingRecommendation;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPriority() {
        return this.priority;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getImageUrl() {
        return this.imageUrl;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final UUID id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSender(final User sender) {
        this.sender = sender;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTitle(final String title) {
        this.title = title;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWeightKg(final BigDecimal weightKg) {
        this.weightKg = weightKg;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWidthCm(final BigDecimal widthCm) {
        this.widthCm = widthCm;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setHeightCm(final BigDecimal heightCm) {
        this.heightCm = heightCm;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDepthCm(final BigDecimal depthCm) {
        this.depthCm = depthCm;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStartCity(final String startCity) {
        this.startCity = startCity;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEndCity(final String endCity) {
        this.endCity = endCity;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCategory(final String category) {
        this.category = category;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRiskScore(final Integer riskScore) {
        this.riskScore = riskScore;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPackingRecommendation(final String packingRecommendation) {
        this.packingRecommendation = packingRecommendation;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPriority(final String priority) {
        this.priority = priority;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setImageUrl(final String imageUrl) {
        this.imageUrl = imageUrl;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUpdatedAt(final OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Parcel)) return false;
        final Parcel other = (Parcel) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$riskScore = this.getRiskScore();
        final java.lang.Object other$riskScore = other.getRiskScore();
        if (this$riskScore == null ? other$riskScore != null : !this$riskScore.equals(other$riskScore)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$sender = this.getSender();
        final java.lang.Object other$sender = other.getSender();
        if (this$sender == null ? other$sender != null : !this$sender.equals(other$sender)) return false;
        final java.lang.Object this$title = this.getTitle();
        final java.lang.Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        final java.lang.Object this$weightKg = this.getWeightKg();
        final java.lang.Object other$weightKg = other.getWeightKg();
        if (this$weightKg == null ? other$weightKg != null : !this$weightKg.equals(other$weightKg)) return false;
        final java.lang.Object this$widthCm = this.getWidthCm();
        final java.lang.Object other$widthCm = other.getWidthCm();
        if (this$widthCm == null ? other$widthCm != null : !this$widthCm.equals(other$widthCm)) return false;
        final java.lang.Object this$heightCm = this.getHeightCm();
        final java.lang.Object other$heightCm = other.getHeightCm();
        if (this$heightCm == null ? other$heightCm != null : !this$heightCm.equals(other$heightCm)) return false;
        final java.lang.Object this$depthCm = this.getDepthCm();
        final java.lang.Object other$depthCm = other.getDepthCm();
        if (this$depthCm == null ? other$depthCm != null : !this$depthCm.equals(other$depthCm)) return false;
        final java.lang.Object this$startCity = this.getStartCity();
        final java.lang.Object other$startCity = other.getStartCity();
        if (this$startCity == null ? other$startCity != null : !this$startCity.equals(other$startCity)) return false;
        final java.lang.Object this$endCity = this.getEndCity();
        final java.lang.Object other$endCity = other.getEndCity();
        if (this$endCity == null ? other$endCity != null : !this$endCity.equals(other$endCity)) return false;
        final java.lang.Object this$category = this.getCategory();
        final java.lang.Object other$category = other.getCategory();
        if (this$category == null ? other$category != null : !this$category.equals(other$category)) return false;
        final java.lang.Object this$packingRecommendation = this.getPackingRecommendation();
        final java.lang.Object other$packingRecommendation = other.getPackingRecommendation();
        if (this$packingRecommendation == null ? other$packingRecommendation != null : !this$packingRecommendation.equals(other$packingRecommendation)) return false;
        final java.lang.Object this$priority = this.getPriority();
        final java.lang.Object other$priority = other.getPriority();
        if (this$priority == null ? other$priority != null : !this$priority.equals(other$priority)) return false;
        final java.lang.Object this$imageUrl = this.getImageUrl();
        final java.lang.Object other$imageUrl = other.getImageUrl();
        if (this$imageUrl == null ? other$imageUrl != null : !this$imageUrl.equals(other$imageUrl)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        final java.lang.Object this$updatedAt = this.getUpdatedAt();
        final java.lang.Object other$updatedAt = other.getUpdatedAt();
        if (this$updatedAt == null ? other$updatedAt != null : !this$updatedAt.equals(other$updatedAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Parcel;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $riskScore = this.getRiskScore();
        result = result * PRIME + ($riskScore == null ? 43 : $riskScore.hashCode());
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $sender = this.getSender();
        result = result * PRIME + ($sender == null ? 43 : $sender.hashCode());
        final java.lang.Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        final java.lang.Object $weightKg = this.getWeightKg();
        result = result * PRIME + ($weightKg == null ? 43 : $weightKg.hashCode());
        final java.lang.Object $widthCm = this.getWidthCm();
        result = result * PRIME + ($widthCm == null ? 43 : $widthCm.hashCode());
        final java.lang.Object $heightCm = this.getHeightCm();
        result = result * PRIME + ($heightCm == null ? 43 : $heightCm.hashCode());
        final java.lang.Object $depthCm = this.getDepthCm();
        result = result * PRIME + ($depthCm == null ? 43 : $depthCm.hashCode());
        final java.lang.Object $startCity = this.getStartCity();
        result = result * PRIME + ($startCity == null ? 43 : $startCity.hashCode());
        final java.lang.Object $endCity = this.getEndCity();
        result = result * PRIME + ($endCity == null ? 43 : $endCity.hashCode());
        final java.lang.Object $category = this.getCategory();
        result = result * PRIME + ($category == null ? 43 : $category.hashCode());
        final java.lang.Object $packingRecommendation = this.getPackingRecommendation();
        result = result * PRIME + ($packingRecommendation == null ? 43 : $packingRecommendation.hashCode());
        final java.lang.Object $priority = this.getPriority();
        result = result * PRIME + ($priority == null ? 43 : $priority.hashCode());
        final java.lang.Object $imageUrl = this.getImageUrl();
        result = result * PRIME + ($imageUrl == null ? 43 : $imageUrl.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        final java.lang.Object $updatedAt = this.getUpdatedAt();
        result = result * PRIME + ($updatedAt == null ? 43 : $updatedAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "Parcel(id=" + this.getId() + ", sender=" + this.getSender() + ", title=" + this.getTitle() + ", description=" + this.getDescription() + ", weightKg=" + this.getWeightKg() + ", widthCm=" + this.getWidthCm() + ", heightCm=" + this.getHeightCm() + ", depthCm=" + this.getDepthCm() + ", startCity=" + this.getStartCity() + ", endCity=" + this.getEndCity() + ", category=" + this.getCategory() + ", riskScore=" + this.getRiskScore() + ", packingRecommendation=" + this.getPackingRecommendation() + ", priority=" + this.getPriority() + ", imageUrl=" + this.getImageUrl() + ", status=" + this.getStatus() + ", createdAt=" + this.getCreatedAt() + ", updatedAt=" + this.getUpdatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Parcel() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Parcel(final UUID id, final User sender, final String title, final String description, final BigDecimal weightKg, final BigDecimal widthCm, final BigDecimal heightCm, final BigDecimal depthCm, final String startCity, final String endCity, final String category, final Integer riskScore, final String packingRecommendation, final String priority, final String imageUrl, final String status, final OffsetDateTime createdAt, final OffsetDateTime updatedAt) {
        this.id = id;
        this.sender = sender;
        this.title = title;
        this.description = description;
        this.weightKg = weightKg;
        this.widthCm = widthCm;
        this.heightCm = heightCm;
        this.depthCm = depthCm;
        this.startCity = startCity;
        this.endCity = endCity;
        this.category = category;
        this.riskScore = riskScore;
        this.packingRecommendation = packingRecommendation;
        this.priority = priority;
        this.imageUrl = imageUrl;
        this.status = status;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
}
