// Generated by delombok at Thu Jul 16 14:07:14 IST 2026
package com.travelcarry.ai.entity;

import jakarta.persistence.*;
import lombok.*;
import java.util.UUID;

@Entity
@Table(name = "reward_badges")
public class RewardBadge {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;
    @Column(name = "badge_name", unique = true, nullable = false)
    private String badgeName;
    @Column(name = "badge_description", nullable = false)
    private String badgeDescription;
    @Column(name = "icon_url")
    private String iconUrl;
    @Column(columnDefinition = "TEXT")
    private String criteria;


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class RewardBadgeBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UUID id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String badgeName;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String badgeDescription;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String iconUrl;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String criteria;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        RewardBadgeBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public RewardBadge.RewardBadgeBuilder id(final UUID id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public RewardBadge.RewardBadgeBuilder badgeName(final String badgeName) {
            this.badgeName = badgeName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public RewardBadge.RewardBadgeBuilder badgeDescription(final String badgeDescription) {
            this.badgeDescription = badgeDescription;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public RewardBadge.RewardBadgeBuilder iconUrl(final String iconUrl) {
            this.iconUrl = iconUrl;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public RewardBadge.RewardBadgeBuilder criteria(final String criteria) {
            this.criteria = criteria;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public RewardBadge build() {
            return new RewardBadge(this.id, this.badgeName, this.badgeDescription, this.iconUrl, this.criteria);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "RewardBadge.RewardBadgeBuilder(id=" + this.id + ", badgeName=" + this.badgeName + ", badgeDescription=" + this.badgeDescription + ", iconUrl=" + this.iconUrl + ", criteria=" + this.criteria + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static RewardBadge.RewardBadgeBuilder builder() {
        return new RewardBadge.RewardBadgeBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UUID getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getBadgeName() {
        return this.badgeName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getBadgeDescription() {
        return this.badgeDescription;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getIconUrl() {
        return this.iconUrl;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCriteria() {
        return this.criteria;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final UUID id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBadgeName(final String badgeName) {
        this.badgeName = badgeName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBadgeDescription(final String badgeDescription) {
        this.badgeDescription = badgeDescription;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setIconUrl(final String iconUrl) {
        this.iconUrl = iconUrl;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCriteria(final String criteria) {
        this.criteria = criteria;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof RewardBadge)) return false;
        final RewardBadge other = (RewardBadge) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$badgeName = this.getBadgeName();
        final java.lang.Object other$badgeName = other.getBadgeName();
        if (this$badgeName == null ? other$badgeName != null : !this$badgeName.equals(other$badgeName)) return false;
        final java.lang.Object this$badgeDescription = this.getBadgeDescription();
        final java.lang.Object other$badgeDescription = other.getBadgeDescription();
        if (this$badgeDescription == null ? other$badgeDescription != null : !this$badgeDescription.equals(other$badgeDescription)) return false;
        final java.lang.Object this$iconUrl = this.getIconUrl();
        final java.lang.Object other$iconUrl = other.getIconUrl();
        if (this$iconUrl == null ? other$iconUrl != null : !this$iconUrl.equals(other$iconUrl)) return false;
        final java.lang.Object this$criteria = this.getCriteria();
        final java.lang.Object other$criteria = other.getCriteria();
        if (this$criteria == null ? other$criteria != null : !this$criteria.equals(other$criteria)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof RewardBadge;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $badgeName = this.getBadgeName();
        result = result * PRIME + ($badgeName == null ? 43 : $badgeName.hashCode());
        final java.lang.Object $badgeDescription = this.getBadgeDescription();
        result = result * PRIME + ($badgeDescription == null ? 43 : $badgeDescription.hashCode());
        final java.lang.Object $iconUrl = this.getIconUrl();
        result = result * PRIME + ($iconUrl == null ? 43 : $iconUrl.hashCode());
        final java.lang.Object $criteria = this.getCriteria();
        result = result * PRIME + ($criteria == null ? 43 : $criteria.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "RewardBadge(id=" + this.getId() + ", badgeName=" + this.getBadgeName() + ", badgeDescription=" + this.getBadgeDescription() + ", iconUrl=" + this.getIconUrl() + ", criteria=" + this.getCriteria() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public RewardBadge() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public RewardBadge(final UUID id, final String badgeName, final String badgeDescription, final String iconUrl, final String criteria) {
        this.id = id;
        this.badgeName = badgeName;
        this.badgeDescription = badgeDescription;
        this.iconUrl = iconUrl;
        this.criteria = criteria;
    }
}
