// Generated by delombok at Thu Jul 16 14:07:14 IST 2026
package com.travelcarry.ai.entity;

import jakarta.persistence.*;
import lombok.*;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

@Entity
@Table(name = "transactions")
public class Transaction {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "booking_id")
    private Booking booking;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sender_id", nullable = false)
    private User sender;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "traveler_id")
    private User traveler;
    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal amount;
    @Column(name = "platform_fee", nullable = false, precision = 10, scale = 2)
    private BigDecimal platformFee;
    @Column(name = "transaction_type", nullable = false)
    private String transactionType; // PAYMENT, PAYOUT, REFUND
    @Column(nullable = false)
    private String status; // PENDING, COMPLETED, FAILED
    @Column(name = "reference_id", unique = true)
    private String referenceId;
    @Column(name = "created_at", updatable = false)
    private OffsetDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        createdAt = OffsetDateTime.now();
        if (status == null) status = "PENDING";
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class TransactionBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UUID id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Booking booking;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private User sender;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private User traveler;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal amount;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal platformFee;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String transactionType;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String status;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String referenceId;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private OffsetDateTime createdAt;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        TransactionBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Transaction.TransactionBuilder id(final UUID id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Transaction.TransactionBuilder booking(final Booking booking) {
            this.booking = booking;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Transaction.TransactionBuilder sender(final User sender) {
            this.sender = sender;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Transaction.TransactionBuilder traveler(final User traveler) {
            this.traveler = traveler;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Transaction.TransactionBuilder amount(final BigDecimal amount) {
            this.amount = amount;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Transaction.TransactionBuilder platformFee(final BigDecimal platformFee) {
            this.platformFee = platformFee;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Transaction.TransactionBuilder transactionType(final String transactionType) {
            this.transactionType = transactionType;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Transaction.TransactionBuilder status(final String status) {
            this.status = status;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Transaction.TransactionBuilder referenceId(final String referenceId) {
            this.referenceId = referenceId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Transaction.TransactionBuilder createdAt(final OffsetDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Transaction build() {
            return new Transaction(this.id, this.booking, this.sender, this.traveler, this.amount, this.platformFee, this.transactionType, this.status, this.referenceId, this.createdAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "Transaction.TransactionBuilder(id=" + this.id + ", booking=" + this.booking + ", sender=" + this.sender + ", traveler=" + this.traveler + ", amount=" + this.amount + ", platformFee=" + this.platformFee + ", transactionType=" + this.transactionType + ", status=" + this.status + ", referenceId=" + this.referenceId + ", createdAt=" + this.createdAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static Transaction.TransactionBuilder builder() {
        return new Transaction.TransactionBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UUID getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Booking getBooking() {
        return this.booking;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public User getSender() {
        return this.sender;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public User getTraveler() {
        return this.traveler;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getAmount() {
        return this.amount;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getPlatformFee() {
        return this.platformFee;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTransactionType() {
        return this.transactionType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getReferenceId() {
        return this.referenceId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final UUID id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBooking(final Booking booking) {
        this.booking = booking;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSender(final User sender) {
        this.sender = sender;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTraveler(final User traveler) {
        this.traveler = traveler;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAmount(final BigDecimal amount) {
        this.amount = amount;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPlatformFee(final BigDecimal platformFee) {
        this.platformFee = platformFee;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTransactionType(final String transactionType) {
        this.transactionType = transactionType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setReferenceId(final String referenceId) {
        this.referenceId = referenceId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Transaction)) return false;
        final Transaction other = (Transaction) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$booking = this.getBooking();
        final java.lang.Object other$booking = other.getBooking();
        if (this$booking == null ? other$booking != null : !this$booking.equals(other$booking)) return false;
        final java.lang.Object this$sender = this.getSender();
        final java.lang.Object other$sender = other.getSender();
        if (this$sender == null ? other$sender != null : !this$sender.equals(other$sender)) return false;
        final java.lang.Object this$traveler = this.getTraveler();
        final java.lang.Object other$traveler = other.getTraveler();
        if (this$traveler == null ? other$traveler != null : !this$traveler.equals(other$traveler)) return false;
        final java.lang.Object this$amount = this.getAmount();
        final java.lang.Object other$amount = other.getAmount();
        if (this$amount == null ? other$amount != null : !this$amount.equals(other$amount)) return false;
        final java.lang.Object this$platformFee = this.getPlatformFee();
        final java.lang.Object other$platformFee = other.getPlatformFee();
        if (this$platformFee == null ? other$platformFee != null : !this$platformFee.equals(other$platformFee)) return false;
        final java.lang.Object this$transactionType = this.getTransactionType();
        final java.lang.Object other$transactionType = other.getTransactionType();
        if (this$transactionType == null ? other$transactionType != null : !this$transactionType.equals(other$transactionType)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$referenceId = this.getReferenceId();
        final java.lang.Object other$referenceId = other.getReferenceId();
        if (this$referenceId == null ? other$referenceId != null : !this$referenceId.equals(other$referenceId)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Transaction;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $booking = this.getBooking();
        result = result * PRIME + ($booking == null ? 43 : $booking.hashCode());
        final java.lang.Object $sender = this.getSender();
        result = result * PRIME + ($sender == null ? 43 : $sender.hashCode());
        final java.lang.Object $traveler = this.getTraveler();
        result = result * PRIME + ($traveler == null ? 43 : $traveler.hashCode());
        final java.lang.Object $amount = this.getAmount();
        result = result * PRIME + ($amount == null ? 43 : $amount.hashCode());
        final java.lang.Object $platformFee = this.getPlatformFee();
        result = result * PRIME + ($platformFee == null ? 43 : $platformFee.hashCode());
        final java.lang.Object $transactionType = this.getTransactionType();
        result = result * PRIME + ($transactionType == null ? 43 : $transactionType.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $referenceId = this.getReferenceId();
        result = result * PRIME + ($referenceId == null ? 43 : $referenceId.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "Transaction(id=" + this.getId() + ", booking=" + this.getBooking() + ", sender=" + this.getSender() + ", traveler=" + this.getTraveler() + ", amount=" + this.getAmount() + ", platformFee=" + this.getPlatformFee() + ", transactionType=" + this.getTransactionType() + ", status=" + this.getStatus() + ", referenceId=" + this.getReferenceId() + ", createdAt=" + this.getCreatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Transaction() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Transaction(final UUID id, final Booking booking, final User sender, final User traveler, final BigDecimal amount, final BigDecimal platformFee, final String transactionType, final String status, final String referenceId, final OffsetDateTime createdAt) {
        this.id = id;
        this.booking = booking;
        this.sender = sender;
        this.traveler = traveler;
        this.amount = amount;
        this.platformFee = platformFee;
        this.transactionType = transactionType;
        this.status = status;
        this.referenceId = referenceId;
        this.createdAt = createdAt;
    }
}
