// Generated by delombok at Thu Jul 16 14:07:14 IST 2026
package com.travelcarry.ai.entity;

import jakarta.persistence.*;
import lombok.*;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

@Entity
@Table(name = "trips")
public class Trip {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "traveler_id", nullable = false)
    private User traveler;
    @Column(name = "start_city", nullable = false)
    private String startCity;
    @Column(name = "end_city", nullable = false)
    private String endCity;
    @Column(name = "departure_date", nullable = false)
    private OffsetDateTime departureDate;
    @Column(name = "arrival_date", nullable = false)
    private OffsetDateTime arrivalDate;
    @Column(name = "luggage_capacity_kg", nullable = false, precision = 6, scale = 2)
    private BigDecimal luggageCapacityKg;
    @Column(name = "available_space_kg", nullable = false, precision = 6, scale = 2)
    private BigDecimal availableSpaceKg;
    @Column(name = "vehicle_type", nullable = false)
    private String vehicleType; // CAR, FLIGHT, TRAIN, BUS
    @Column(nullable = false)
    private String status; // PLANNED, ONGOING, COMPLETED, CANCELLED
    @Column(name = "created_at", updatable = false)
    private OffsetDateTime createdAt;
    @Column(name = "updated_at")
    private OffsetDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        createdAt = OffsetDateTime.now();
        updatedAt = OffsetDateTime.now();
        if (status == null) status = "PLANNED";
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = OffsetDateTime.now();
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class TripBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UUID id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private User traveler;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String startCity;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String endCity;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private OffsetDateTime departureDate;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private OffsetDateTime arrivalDate;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal luggageCapacityKg;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal availableSpaceKg;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String vehicleType;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String status;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private OffsetDateTime createdAt;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private OffsetDateTime updatedAt;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        TripBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Trip.TripBuilder id(final UUID id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Trip.TripBuilder traveler(final User traveler) {
            this.traveler = traveler;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Trip.TripBuilder startCity(final String startCity) {
            this.startCity = startCity;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Trip.TripBuilder endCity(final String endCity) {
            this.endCity = endCity;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Trip.TripBuilder departureDate(final OffsetDateTime departureDate) {
            this.departureDate = departureDate;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Trip.TripBuilder arrivalDate(final OffsetDateTime arrivalDate) {
            this.arrivalDate = arrivalDate;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Trip.TripBuilder luggageCapacityKg(final BigDecimal luggageCapacityKg) {
            this.luggageCapacityKg = luggageCapacityKg;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Trip.TripBuilder availableSpaceKg(final BigDecimal availableSpaceKg) {
            this.availableSpaceKg = availableSpaceKg;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Trip.TripBuilder vehicleType(final String vehicleType) {
            this.vehicleType = vehicleType;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Trip.TripBuilder status(final String status) {
            this.status = status;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Trip.TripBuilder createdAt(final OffsetDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Trip.TripBuilder updatedAt(final OffsetDateTime updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Trip build() {
            return new Trip(this.id, this.traveler, this.startCity, this.endCity, this.departureDate, this.arrivalDate, this.luggageCapacityKg, this.availableSpaceKg, this.vehicleType, this.status, this.createdAt, this.updatedAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "Trip.TripBuilder(id=" + this.id + ", traveler=" + this.traveler + ", startCity=" + this.startCity + ", endCity=" + this.endCity + ", departureDate=" + this.departureDate + ", arrivalDate=" + this.arrivalDate + ", luggageCapacityKg=" + this.luggageCapacityKg + ", availableSpaceKg=" + this.availableSpaceKg + ", vehicleType=" + this.vehicleType + ", status=" + this.status + ", createdAt=" + this.createdAt + ", updatedAt=" + this.updatedAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static Trip.TripBuilder builder() {
        return new Trip.TripBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UUID getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public User getTraveler() {
        return this.traveler;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStartCity() {
        return this.startCity;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getEndCity() {
        return this.endCity;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public OffsetDateTime getDepartureDate() {
        return this.departureDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public OffsetDateTime getArrivalDate() {
        return this.arrivalDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getLuggageCapacityKg() {
        return this.luggageCapacityKg;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getAvailableSpaceKg() {
        return this.availableSpaceKg;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getVehicleType() {
        return this.vehicleType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final UUID id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTraveler(final User traveler) {
        this.traveler = traveler;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStartCity(final String startCity) {
        this.startCity = startCity;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEndCity(final String endCity) {
        this.endCity = endCity;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDepartureDate(final OffsetDateTime departureDate) {
        this.departureDate = departureDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setArrivalDate(final OffsetDateTime arrivalDate) {
        this.arrivalDate = arrivalDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLuggageCapacityKg(final BigDecimal luggageCapacityKg) {
        this.luggageCapacityKg = luggageCapacityKg;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAvailableSpaceKg(final BigDecimal availableSpaceKg) {
        this.availableSpaceKg = availableSpaceKg;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setVehicleType(final String vehicleType) {
        this.vehicleType = vehicleType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUpdatedAt(final OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Trip)) return false;
        final Trip other = (Trip) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$traveler = this.getTraveler();
        final java.lang.Object other$traveler = other.getTraveler();
        if (this$traveler == null ? other$traveler != null : !this$traveler.equals(other$traveler)) return false;
        final java.lang.Object this$startCity = this.getStartCity();
        final java.lang.Object other$startCity = other.getStartCity();
        if (this$startCity == null ? other$startCity != null : !this$startCity.equals(other$startCity)) return false;
        final java.lang.Object this$endCity = this.getEndCity();
        final java.lang.Object other$endCity = other.getEndCity();
        if (this$endCity == null ? other$endCity != null : !this$endCity.equals(other$endCity)) return false;
        final java.lang.Object this$departureDate = this.getDepartureDate();
        final java.lang.Object other$departureDate = other.getDepartureDate();
        if (this$departureDate == null ? other$departureDate != null : !this$departureDate.equals(other$departureDate)) return false;
        final java.lang.Object this$arrivalDate = this.getArrivalDate();
        final java.lang.Object other$arrivalDate = other.getArrivalDate();
        if (this$arrivalDate == null ? other$arrivalDate != null : !this$arrivalDate.equals(other$arrivalDate)) return false;
        final java.lang.Object this$luggageCapacityKg = this.getLuggageCapacityKg();
        final java.lang.Object other$luggageCapacityKg = other.getLuggageCapacityKg();
        if (this$luggageCapacityKg == null ? other$luggageCapacityKg != null : !this$luggageCapacityKg.equals(other$luggageCapacityKg)) return false;
        final java.lang.Object this$availableSpaceKg = this.getAvailableSpaceKg();
        final java.lang.Object other$availableSpaceKg = other.getAvailableSpaceKg();
        if (this$availableSpaceKg == null ? other$availableSpaceKg != null : !this$availableSpaceKg.equals(other$availableSpaceKg)) return false;
        final java.lang.Object this$vehicleType = this.getVehicleType();
        final java.lang.Object other$vehicleType = other.getVehicleType();
        if (this$vehicleType == null ? other$vehicleType != null : !this$vehicleType.equals(other$vehicleType)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        final java.lang.Object this$updatedAt = this.getUpdatedAt();
        final java.lang.Object other$updatedAt = other.getUpdatedAt();
        if (this$updatedAt == null ? other$updatedAt != null : !this$updatedAt.equals(other$updatedAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Trip;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $traveler = this.getTraveler();
        result = result * PRIME + ($traveler == null ? 43 : $traveler.hashCode());
        final java.lang.Object $startCity = this.getStartCity();
        result = result * PRIME + ($startCity == null ? 43 : $startCity.hashCode());
        final java.lang.Object $endCity = this.getEndCity();
        result = result * PRIME + ($endCity == null ? 43 : $endCity.hashCode());
        final java.lang.Object $departureDate = this.getDepartureDate();
        result = result * PRIME + ($departureDate == null ? 43 : $departureDate.hashCode());
        final java.lang.Object $arrivalDate = this.getArrivalDate();
        result = result * PRIME + ($arrivalDate == null ? 43 : $arrivalDate.hashCode());
        final java.lang.Object $luggageCapacityKg = this.getLuggageCapacityKg();
        result = result * PRIME + ($luggageCapacityKg == null ? 43 : $luggageCapacityKg.hashCode());
        final java.lang.Object $availableSpaceKg = this.getAvailableSpaceKg();
        result = result * PRIME + ($availableSpaceKg == null ? 43 : $availableSpaceKg.hashCode());
        final java.lang.Object $vehicleType = this.getVehicleType();
        result = result * PRIME + ($vehicleType == null ? 43 : $vehicleType.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        final java.lang.Object $updatedAt = this.getUpdatedAt();
        result = result * PRIME + ($updatedAt == null ? 43 : $updatedAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "Trip(id=" + this.getId() + ", traveler=" + this.getTraveler() + ", startCity=" + this.getStartCity() + ", endCity=" + this.getEndCity() + ", departureDate=" + this.getDepartureDate() + ", arrivalDate=" + this.getArrivalDate() + ", luggageCapacityKg=" + this.getLuggageCapacityKg() + ", availableSpaceKg=" + this.getAvailableSpaceKg() + ", vehicleType=" + this.getVehicleType() + ", status=" + this.getStatus() + ", createdAt=" + this.getCreatedAt() + ", updatedAt=" + this.getUpdatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Trip() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Trip(final UUID id, final User traveler, final String startCity, final String endCity, final OffsetDateTime departureDate, final OffsetDateTime arrivalDate, final BigDecimal luggageCapacityKg, final BigDecimal availableSpaceKg, final String vehicleType, final String status, final OffsetDateTime createdAt, final OffsetDateTime updatedAt) {
        this.id = id;
        this.traveler = traveler;
        this.startCity = startCity;
        this.endCity = endCity;
        this.departureDate = departureDate;
        this.arrivalDate = arrivalDate;
        this.luggageCapacityKg = luggageCapacityKg;
        this.availableSpaceKg = availableSpaceKg;
        this.vehicleType = vehicleType;
        this.status = status;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
}
