// Generated by delombok at Thu Jul 16 14:07:14 IST 2026
package com.travelcarry.ai.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.OffsetDateTime;
import java.util.UUID;

@Entity
@Table(name = "user_badges", uniqueConstraints = {@UniqueConstraint(columnNames = {"user_id", "badge_id"})})
public class UserBadge {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "badge_id", nullable = false)
    private RewardBadge badge;
    @Column(name = "awarded_at", updatable = false)
    private OffsetDateTime awardedAt;

    @PrePersist
    protected void onCreate() {
        awardedAt = OffsetDateTime.now();
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class UserBadgeBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UUID id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private User user;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private RewardBadge badge;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private OffsetDateTime awardedAt;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        UserBadgeBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public UserBadge.UserBadgeBuilder id(final UUID id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public UserBadge.UserBadgeBuilder user(final User user) {
            this.user = user;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public UserBadge.UserBadgeBuilder badge(final RewardBadge badge) {
            this.badge = badge;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public UserBadge.UserBadgeBuilder awardedAt(final OffsetDateTime awardedAt) {
            this.awardedAt = awardedAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public UserBadge build() {
            return new UserBadge(this.id, this.user, this.badge, this.awardedAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "UserBadge.UserBadgeBuilder(id=" + this.id + ", user=" + this.user + ", badge=" + this.badge + ", awardedAt=" + this.awardedAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static UserBadge.UserBadgeBuilder builder() {
        return new UserBadge.UserBadgeBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UUID getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public User getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public RewardBadge getBadge() {
        return this.badge;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public OffsetDateTime getAwardedAt() {
        return this.awardedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final UUID id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUser(final User user) {
        this.user = user;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBadge(final RewardBadge badge) {
        this.badge = badge;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAwardedAt(final OffsetDateTime awardedAt) {
        this.awardedAt = awardedAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof UserBadge)) return false;
        final UserBadge other = (UserBadge) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$user = this.getUser();
        final java.lang.Object other$user = other.getUser();
        if (this$user == null ? other$user != null : !this$user.equals(other$user)) return false;
        final java.lang.Object this$badge = this.getBadge();
        final java.lang.Object other$badge = other.getBadge();
        if (this$badge == null ? other$badge != null : !this$badge.equals(other$badge)) return false;
        final java.lang.Object this$awardedAt = this.getAwardedAt();
        final java.lang.Object other$awardedAt = other.getAwardedAt();
        if (this$awardedAt == null ? other$awardedAt != null : !this$awardedAt.equals(other$awardedAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof UserBadge;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $user = this.getUser();
        result = result * PRIME + ($user == null ? 43 : $user.hashCode());
        final java.lang.Object $badge = this.getBadge();
        result = result * PRIME + ($badge == null ? 43 : $badge.hashCode());
        final java.lang.Object $awardedAt = this.getAwardedAt();
        result = result * PRIME + ($awardedAt == null ? 43 : $awardedAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "UserBadge(id=" + this.getId() + ", user=" + this.getUser() + ", badge=" + this.getBadge() + ", awardedAt=" + this.getAwardedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UserBadge() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UserBadge(final UUID id, final User user, final RewardBadge badge, final OffsetDateTime awardedAt) {
        this.id = id;
        this.user = user;
        this.badge = badge;
        this.awardedAt = awardedAt;
    }
}
