// Generated by delombok at Thu Jul 16 14:07:14 IST 2026
package com.travelcarry.ai.entity;

import jakarta.persistence.*;
import lombok.*;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

@Entity
@Table(name = "users")
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;
    @Column(unique = true, nullable = false)
    private String email;
    @Column(name = "password_hash", nullable = false)
    private String passwordHash;
    @Column(name = "first_name", nullable = false)
    private String firstName;
    @Column(name = "last_name", nullable = false)
    private String lastName;
    @Column(name = "phone_number", unique = true)
    private String phoneNumber;
    @Column(nullable = false)
    private String role; // TRAVELER, SENDER, ADMIN
    @Column(precision = 3, scale = 2)
    private BigDecimal rating;
    @Column(name = "trust_score")
    private Integer trustScore;
    @Column(name = "trust_level")
    private String trustLevel;
    @Column(name = "completed_deliveries")
    private Integer completedDeliveries;
    @Column(name = "cancellation_rate", precision = 5, scale = 2)
    private BigDecimal cancellationRate;
    private String status; // ACTIVE, BLOCKED, SUSPENDED
    @Column(name = "created_at", updatable = false)
    private OffsetDateTime createdAt;
    @Column(name = "updated_at")
    private OffsetDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        createdAt = OffsetDateTime.now();
        updatedAt = OffsetDateTime.now();
        if (rating == null) rating = BigDecimal.ZERO;
        if (trustScore == null) trustScore = 50;
        if (trustLevel == null) trustLevel = "New User";
        if (completedDeliveries == null) completedDeliveries = 0;
        if (cancellationRate == null) cancellationRate = BigDecimal.ZERO;
        if (status == null) status = "ACTIVE";
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = OffsetDateTime.now();
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class UserBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UUID id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String email;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String passwordHash;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String firstName;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String lastName;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String phoneNumber;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String role;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal rating;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Integer trustScore;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String trustLevel;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Integer completedDeliveries;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal cancellationRate;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String status;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private OffsetDateTime createdAt;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private OffsetDateTime updatedAt;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        UserBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public User.UserBuilder id(final UUID id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public User.UserBuilder email(final String email) {
            this.email = email;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public User.UserBuilder passwordHash(final String passwordHash) {
            this.passwordHash = passwordHash;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public User.UserBuilder firstName(final String firstName) {
            this.firstName = firstName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public User.UserBuilder lastName(final String lastName) {
            this.lastName = lastName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public User.UserBuilder phoneNumber(final String phoneNumber) {
            this.phoneNumber = phoneNumber;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public User.UserBuilder role(final String role) {
            this.role = role;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public User.UserBuilder rating(final BigDecimal rating) {
            this.rating = rating;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public User.UserBuilder trustScore(final Integer trustScore) {
            this.trustScore = trustScore;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public User.UserBuilder trustLevel(final String trustLevel) {
            this.trustLevel = trustLevel;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public User.UserBuilder completedDeliveries(final Integer completedDeliveries) {
            this.completedDeliveries = completedDeliveries;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public User.UserBuilder cancellationRate(final BigDecimal cancellationRate) {
            this.cancellationRate = cancellationRate;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public User.UserBuilder status(final String status) {
            this.status = status;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public User.UserBuilder createdAt(final OffsetDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public User.UserBuilder updatedAt(final OffsetDateTime updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public User build() {
            return new User(this.id, this.email, this.passwordHash, this.firstName, this.lastName, this.phoneNumber, this.role, this.rating, this.trustScore, this.trustLevel, this.completedDeliveries, this.cancellationRate, this.status, this.createdAt, this.updatedAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "User.UserBuilder(id=" + this.id + ", email=" + this.email + ", passwordHash=" + this.passwordHash + ", firstName=" + this.firstName + ", lastName=" + this.lastName + ", phoneNumber=" + this.phoneNumber + ", role=" + this.role + ", rating=" + this.rating + ", trustScore=" + this.trustScore + ", trustLevel=" + this.trustLevel + ", completedDeliveries=" + this.completedDeliveries + ", cancellationRate=" + this.cancellationRate + ", status=" + this.status + ", createdAt=" + this.createdAt + ", updatedAt=" + this.updatedAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static User.UserBuilder builder() {
        return new User.UserBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UUID getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPasswordHash() {
        return this.passwordHash;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getFirstName() {
        return this.firstName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getLastName() {
        return this.lastName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getRole() {
        return this.role;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getRating() {
        return this.rating;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getTrustScore() {
        return this.trustScore;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTrustLevel() {
        return this.trustLevel;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getCompletedDeliveries() {
        return this.completedDeliveries;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getCancellationRate() {
        return this.cancellationRate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final UUID id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEmail(final String email) {
        this.email = email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPasswordHash(final String passwordHash) {
        this.passwordHash = passwordHash;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFirstName(final String firstName) {
        this.firstName = firstName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLastName(final String lastName) {
        this.lastName = lastName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPhoneNumber(final String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRole(final String role) {
        this.role = role;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRating(final BigDecimal rating) {
        this.rating = rating;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTrustScore(final Integer trustScore) {
        this.trustScore = trustScore;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTrustLevel(final String trustLevel) {
        this.trustLevel = trustLevel;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCompletedDeliveries(final Integer completedDeliveries) {
        this.completedDeliveries = completedDeliveries;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCancellationRate(final BigDecimal cancellationRate) {
        this.cancellationRate = cancellationRate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUpdatedAt(final OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof User)) return false;
        final User other = (User) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$trustScore = this.getTrustScore();
        final java.lang.Object other$trustScore = other.getTrustScore();
        if (this$trustScore == null ? other$trustScore != null : !this$trustScore.equals(other$trustScore)) return false;
        final java.lang.Object this$completedDeliveries = this.getCompletedDeliveries();
        final java.lang.Object other$completedDeliveries = other.getCompletedDeliveries();
        if (this$completedDeliveries == null ? other$completedDeliveries != null : !this$completedDeliveries.equals(other$completedDeliveries)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$email = this.getEmail();
        final java.lang.Object other$email = other.getEmail();
        if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
        final java.lang.Object this$passwordHash = this.getPasswordHash();
        final java.lang.Object other$passwordHash = other.getPasswordHash();
        if (this$passwordHash == null ? other$passwordHash != null : !this$passwordHash.equals(other$passwordHash)) return false;
        final java.lang.Object this$firstName = this.getFirstName();
        final java.lang.Object other$firstName = other.getFirstName();
        if (this$firstName == null ? other$firstName != null : !this$firstName.equals(other$firstName)) return false;
        final java.lang.Object this$lastName = this.getLastName();
        final java.lang.Object other$lastName = other.getLastName();
        if (this$lastName == null ? other$lastName != null : !this$lastName.equals(other$lastName)) return false;
        final java.lang.Object this$phoneNumber = this.getPhoneNumber();
        final java.lang.Object other$phoneNumber = other.getPhoneNumber();
        if (this$phoneNumber == null ? other$phoneNumber != null : !this$phoneNumber.equals(other$phoneNumber)) return false;
        final java.lang.Object this$role = this.getRole();
        final java.lang.Object other$role = other.getRole();
        if (this$role == null ? other$role != null : !this$role.equals(other$role)) return false;
        final java.lang.Object this$rating = this.getRating();
        final java.lang.Object other$rating = other.getRating();
        if (this$rating == null ? other$rating != null : !this$rating.equals(other$rating)) return false;
        final java.lang.Object this$trustLevel = this.getTrustLevel();
        final java.lang.Object other$trustLevel = other.getTrustLevel();
        if (this$trustLevel == null ? other$trustLevel != null : !this$trustLevel.equals(other$trustLevel)) return false;
        final java.lang.Object this$cancellationRate = this.getCancellationRate();
        final java.lang.Object other$cancellationRate = other.getCancellationRate();
        if (this$cancellationRate == null ? other$cancellationRate != null : !this$cancellationRate.equals(other$cancellationRate)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        final java.lang.Object this$updatedAt = this.getUpdatedAt();
        final java.lang.Object other$updatedAt = other.getUpdatedAt();
        if (this$updatedAt == null ? other$updatedAt != null : !this$updatedAt.equals(other$updatedAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof User;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $trustScore = this.getTrustScore();
        result = result * PRIME + ($trustScore == null ? 43 : $trustScore.hashCode());
        final java.lang.Object $completedDeliveries = this.getCompletedDeliveries();
        result = result * PRIME + ($completedDeliveries == null ? 43 : $completedDeliveries.hashCode());
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $email = this.getEmail();
        result = result * PRIME + ($email == null ? 43 : $email.hashCode());
        final java.lang.Object $passwordHash = this.getPasswordHash();
        result = result * PRIME + ($passwordHash == null ? 43 : $passwordHash.hashCode());
        final java.lang.Object $firstName = this.getFirstName();
        result = result * PRIME + ($firstName == null ? 43 : $firstName.hashCode());
        final java.lang.Object $lastName = this.getLastName();
        result = result * PRIME + ($lastName == null ? 43 : $lastName.hashCode());
        final java.lang.Object $phoneNumber = this.getPhoneNumber();
        result = result * PRIME + ($phoneNumber == null ? 43 : $phoneNumber.hashCode());
        final java.lang.Object $role = this.getRole();
        result = result * PRIME + ($role == null ? 43 : $role.hashCode());
        final java.lang.Object $rating = this.getRating();
        result = result * PRIME + ($rating == null ? 43 : $rating.hashCode());
        final java.lang.Object $trustLevel = this.getTrustLevel();
        result = result * PRIME + ($trustLevel == null ? 43 : $trustLevel.hashCode());
        final java.lang.Object $cancellationRate = this.getCancellationRate();
        result = result * PRIME + ($cancellationRate == null ? 43 : $cancellationRate.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        final java.lang.Object $updatedAt = this.getUpdatedAt();
        result = result * PRIME + ($updatedAt == null ? 43 : $updatedAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "User(id=" + this.getId() + ", email=" + this.getEmail() + ", passwordHash=" + this.getPasswordHash() + ", firstName=" + this.getFirstName() + ", lastName=" + this.getLastName() + ", phoneNumber=" + this.getPhoneNumber() + ", role=" + this.getRole() + ", rating=" + this.getRating() + ", trustScore=" + this.getTrustScore() + ", trustLevel=" + this.getTrustLevel() + ", completedDeliveries=" + this.getCompletedDeliveries() + ", cancellationRate=" + this.getCancellationRate() + ", status=" + this.getStatus() + ", createdAt=" + this.getCreatedAt() + ", updatedAt=" + this.getUpdatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public User() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public User(final UUID id, final String email, final String passwordHash, final String firstName, final String lastName, final String phoneNumber, final String role, final BigDecimal rating, final Integer trustScore, final String trustLevel, final Integer completedDeliveries, final BigDecimal cancellationRate, final String status, final OffsetDateTime createdAt, final OffsetDateTime updatedAt) {
        this.id = id;
        this.email = email;
        this.passwordHash = passwordHash;
        this.firstName = firstName;
        this.lastName = lastName;
        this.phoneNumber = phoneNumber;
        this.role = role;
        this.rating = rating;
        this.trustScore = trustScore;
        this.trustLevel = trustLevel;
        this.completedDeliveries = completedDeliveries;
        this.cancellationRate = cancellationRate;
        this.status = status;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
}
