// Generated by delombok at Thu Jul 16 14:07:14 IST 2026
package com.travelcarry.ai.service;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;
import java.math.BigDecimal;
import java.util.*;

@Service
public class AIService {
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(AIService.class);
    private final RestTemplate restTemplate = new RestTemplate();
    @Value("${travelcarry.jwt.secret}")
    private String jwtSecret;
    @Value("${travelcarry.ai.service-url}")
    private String aiServiceUrl;


    public static class MatchResult {
        private UUID travelerId;
        private UUID tripId;
        private String travelerName;
        private Double rating;
        private Integer trustScore;
        private String vehicleType;
        private Double matchConfidence; // Percentage e.g. 96.50

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        MatchResult(final UUID travelerId, final UUID tripId, final String travelerName, final Double rating, final Integer trustScore, final String vehicleType, final Double matchConfidence) {
            this.travelerId = travelerId;
            this.tripId = tripId;
            this.travelerName = travelerName;
            this.rating = rating;
            this.trustScore = trustScore;
            this.vehicleType = vehicleType;
            this.matchConfidence = matchConfidence;
        }


        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public static class MatchResultBuilder {
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            private UUID travelerId;
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            private UUID tripId;
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            private String travelerName;
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            private Double rating;
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            private Integer trustScore;
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            private String vehicleType;
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            private Double matchConfidence;

            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            MatchResultBuilder() {
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public AIService.MatchResult.MatchResultBuilder travelerId(final UUID travelerId) {
                this.travelerId = travelerId;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public AIService.MatchResult.MatchResultBuilder tripId(final UUID tripId) {
                this.tripId = tripId;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public AIService.MatchResult.MatchResultBuilder travelerName(final String travelerName) {
                this.travelerName = travelerName;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public AIService.MatchResult.MatchResultBuilder rating(final Double rating) {
                this.rating = rating;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public AIService.MatchResult.MatchResultBuilder trustScore(final Integer trustScore) {
                this.trustScore = trustScore;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public AIService.MatchResult.MatchResultBuilder vehicleType(final String vehicleType) {
                this.vehicleType = vehicleType;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public AIService.MatchResult.MatchResultBuilder matchConfidence(final Double matchConfidence) {
                this.matchConfidence = matchConfidence;
                return this;
            }

            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public AIService.MatchResult build() {
                return new AIService.MatchResult(this.travelerId, this.tripId, this.travelerName, this.rating, this.trustScore, this.vehicleType, this.matchConfidence);
            }

            @java.lang.Override
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public java.lang.String toString() {
                return "AIService.MatchResult.MatchResultBuilder(travelerId=" + this.travelerId + ", tripId=" + this.tripId + ", travelerName=" + this.travelerName + ", rating=" + this.rating + ", trustScore=" + this.trustScore + ", vehicleType=" + this.vehicleType + ", matchConfidence=" + this.matchConfidence + ")";
            }
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public static AIService.MatchResult.MatchResultBuilder builder() {
            return new AIService.MatchResult.MatchResultBuilder();
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public UUID getTravelerId() {
            return this.travelerId;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public UUID getTripId() {
            return this.tripId;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public String getTravelerName() {
            return this.travelerName;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Double getRating() {
            return this.rating;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Integer getTrustScore() {
            return this.trustScore;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public String getVehicleType() {
            return this.vehicleType;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Double getMatchConfidence() {
            return this.matchConfidence;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setTravelerId(final UUID travelerId) {
            this.travelerId = travelerId;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setTripId(final UUID tripId) {
            this.tripId = tripId;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setTravelerName(final String travelerName) {
            this.travelerName = travelerName;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setRating(final Double rating) {
            this.rating = rating;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setTrustScore(final Integer trustScore) {
            this.trustScore = trustScore;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setVehicleType(final String vehicleType) {
            this.vehicleType = vehicleType;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setMatchConfidence(final Double matchConfidence) {
            this.matchConfidence = matchConfidence;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof AIService.MatchResult)) return false;
            final AIService.MatchResult other = (AIService.MatchResult) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$rating = this.getRating();
            final java.lang.Object other$rating = other.getRating();
            if (this$rating == null ? other$rating != null : !this$rating.equals(other$rating)) return false;
            final java.lang.Object this$trustScore = this.getTrustScore();
            final java.lang.Object other$trustScore = other.getTrustScore();
            if (this$trustScore == null ? other$trustScore != null : !this$trustScore.equals(other$trustScore)) return false;
            final java.lang.Object this$matchConfidence = this.getMatchConfidence();
            final java.lang.Object other$matchConfidence = other.getMatchConfidence();
            if (this$matchConfidence == null ? other$matchConfidence != null : !this$matchConfidence.equals(other$matchConfidence)) return false;
            final java.lang.Object this$travelerId = this.getTravelerId();
            final java.lang.Object other$travelerId = other.getTravelerId();
            if (this$travelerId == null ? other$travelerId != null : !this$travelerId.equals(other$travelerId)) return false;
            final java.lang.Object this$tripId = this.getTripId();
            final java.lang.Object other$tripId = other.getTripId();
            if (this$tripId == null ? other$tripId != null : !this$tripId.equals(other$tripId)) return false;
            final java.lang.Object this$travelerName = this.getTravelerName();
            final java.lang.Object other$travelerName = other.getTravelerName();
            if (this$travelerName == null ? other$travelerName != null : !this$travelerName.equals(other$travelerName)) return false;
            final java.lang.Object this$vehicleType = this.getVehicleType();
            final java.lang.Object other$vehicleType = other.getVehicleType();
            if (this$vehicleType == null ? other$vehicleType != null : !this$vehicleType.equals(other$vehicleType)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof AIService.MatchResult;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $rating = this.getRating();
            result = result * PRIME + ($rating == null ? 43 : $rating.hashCode());
            final java.lang.Object $trustScore = this.getTrustScore();
            result = result * PRIME + ($trustScore == null ? 43 : $trustScore.hashCode());
            final java.lang.Object $matchConfidence = this.getMatchConfidence();
            result = result * PRIME + ($matchConfidence == null ? 43 : $matchConfidence.hashCode());
            final java.lang.Object $travelerId = this.getTravelerId();
            result = result * PRIME + ($travelerId == null ? 43 : $travelerId.hashCode());
            final java.lang.Object $tripId = this.getTripId();
            result = result * PRIME + ($tripId == null ? 43 : $tripId.hashCode());
            final java.lang.Object $travelerName = this.getTravelerName();
            result = result * PRIME + ($travelerName == null ? 43 : $travelerName.hashCode());
            final java.lang.Object $vehicleType = this.getVehicleType();
            result = result * PRIME + ($vehicleType == null ? 43 : $vehicleType.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "AIService.MatchResult(travelerId=" + this.getTravelerId() + ", tripId=" + this.getTripId() + ", travelerName=" + this.getTravelerName() + ", rating=" + this.getRating() + ", trustScore=" + this.getTrustScore() + ", vehicleType=" + this.getVehicleType() + ", matchConfidence=" + this.getMatchConfidence() + ")";
        }
    }


    public static class PricePrediction {
        private BigDecimal minPrice;
        private BigDecimal recommendedPrice;
        private BigDecimal premiumExpressPrice;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        PricePrediction(final BigDecimal minPrice, final BigDecimal recommendedPrice, final BigDecimal premiumExpressPrice) {
            this.minPrice = minPrice;
            this.recommendedPrice = recommendedPrice;
            this.premiumExpressPrice = premiumExpressPrice;
        }


        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public static class PricePredictionBuilder {
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            private BigDecimal minPrice;
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            private BigDecimal recommendedPrice;
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            private BigDecimal premiumExpressPrice;

            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            PricePredictionBuilder() {
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public AIService.PricePrediction.PricePredictionBuilder minPrice(final BigDecimal minPrice) {
                this.minPrice = minPrice;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public AIService.PricePrediction.PricePredictionBuilder recommendedPrice(final BigDecimal recommendedPrice) {
                this.recommendedPrice = recommendedPrice;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public AIService.PricePrediction.PricePredictionBuilder premiumExpressPrice(final BigDecimal premiumExpressPrice) {
                this.premiumExpressPrice = premiumExpressPrice;
                return this;
            }

            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public AIService.PricePrediction build() {
                return new AIService.PricePrediction(this.minPrice, this.recommendedPrice, this.premiumExpressPrice);
            }

            @java.lang.Override
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public java.lang.String toString() {
                return "AIService.PricePrediction.PricePredictionBuilder(minPrice=" + this.minPrice + ", recommendedPrice=" + this.recommendedPrice + ", premiumExpressPrice=" + this.premiumExpressPrice + ")";
            }
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public static AIService.PricePrediction.PricePredictionBuilder builder() {
            return new AIService.PricePrediction.PricePredictionBuilder();
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public BigDecimal getMinPrice() {
            return this.minPrice;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public BigDecimal getRecommendedPrice() {
            return this.recommendedPrice;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public BigDecimal getPremiumExpressPrice() {
            return this.premiumExpressPrice;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setMinPrice(final BigDecimal minPrice) {
            this.minPrice = minPrice;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setRecommendedPrice(final BigDecimal recommendedPrice) {
            this.recommendedPrice = recommendedPrice;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setPremiumExpressPrice(final BigDecimal premiumExpressPrice) {
            this.premiumExpressPrice = premiumExpressPrice;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof AIService.PricePrediction)) return false;
            final AIService.PricePrediction other = (AIService.PricePrediction) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$minPrice = this.getMinPrice();
            final java.lang.Object other$minPrice = other.getMinPrice();
            if (this$minPrice == null ? other$minPrice != null : !this$minPrice.equals(other$minPrice)) return false;
            final java.lang.Object this$recommendedPrice = this.getRecommendedPrice();
            final java.lang.Object other$recommendedPrice = other.getRecommendedPrice();
            if (this$recommendedPrice == null ? other$recommendedPrice != null : !this$recommendedPrice.equals(other$recommendedPrice)) return false;
            final java.lang.Object this$premiumExpressPrice = this.getPremiumExpressPrice();
            final java.lang.Object other$premiumExpressPrice = other.getPremiumExpressPrice();
            if (this$premiumExpressPrice == null ? other$premiumExpressPrice != null : !this$premiumExpressPrice.equals(other$premiumExpressPrice)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof AIService.PricePrediction;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $minPrice = this.getMinPrice();
            result = result * PRIME + ($minPrice == null ? 43 : $minPrice.hashCode());
            final java.lang.Object $recommendedPrice = this.getRecommendedPrice();
            result = result * PRIME + ($recommendedPrice == null ? 43 : $recommendedPrice.hashCode());
            final java.lang.Object $premiumExpressPrice = this.getPremiumExpressPrice();
            result = result * PRIME + ($premiumExpressPrice == null ? 43 : $premiumExpressPrice.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "AIService.PricePrediction(minPrice=" + this.getMinPrice() + ", recommendedPrice=" + this.getRecommendedPrice() + ", premiumExpressPrice=" + this.getPremiumExpressPrice() + ")";
        }
    }


    public static class SafetyScanResult {
        private Integer riskScore;
        private String packingRecommendation;
        private String classification;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        SafetyScanResult(final Integer riskScore, final String packingRecommendation, final String classification) {
            this.riskScore = riskScore;
            this.packingRecommendation = packingRecommendation;
            this.classification = classification;
        }


        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public static class SafetyScanResultBuilder {
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            private Integer riskScore;
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            private String packingRecommendation;
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            private String classification;

            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            SafetyScanResultBuilder() {
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public AIService.SafetyScanResult.SafetyScanResultBuilder riskScore(final Integer riskScore) {
                this.riskScore = riskScore;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public AIService.SafetyScanResult.SafetyScanResultBuilder packingRecommendation(final String packingRecommendation) {
                this.packingRecommendation = packingRecommendation;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public AIService.SafetyScanResult.SafetyScanResultBuilder classification(final String classification) {
                this.classification = classification;
                return this;
            }

            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public AIService.SafetyScanResult build() {
                return new AIService.SafetyScanResult(this.riskScore, this.packingRecommendation, this.classification);
            }

            @java.lang.Override
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public java.lang.String toString() {
                return "AIService.SafetyScanResult.SafetyScanResultBuilder(riskScore=" + this.riskScore + ", packingRecommendation=" + this.packingRecommendation + ", classification=" + this.classification + ")";
            }
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public static AIService.SafetyScanResult.SafetyScanResultBuilder builder() {
            return new AIService.SafetyScanResult.SafetyScanResultBuilder();
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Integer getRiskScore() {
            return this.riskScore;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public String getPackingRecommendation() {
            return this.packingRecommendation;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public String getClassification() {
            return this.classification;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setRiskScore(final Integer riskScore) {
            this.riskScore = riskScore;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setPackingRecommendation(final String packingRecommendation) {
            this.packingRecommendation = packingRecommendation;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setClassification(final String classification) {
            this.classification = classification;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof AIService.SafetyScanResult)) return false;
            final AIService.SafetyScanResult other = (AIService.SafetyScanResult) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$riskScore = this.getRiskScore();
            final java.lang.Object other$riskScore = other.getRiskScore();
            if (this$riskScore == null ? other$riskScore != null : !this$riskScore.equals(other$riskScore)) return false;
            final java.lang.Object this$packingRecommendation = this.getPackingRecommendation();
            final java.lang.Object other$packingRecommendation = other.getPackingRecommendation();
            if (this$packingRecommendation == null ? other$packingRecommendation != null : !this$packingRecommendation.equals(other$packingRecommendation)) return false;
            final java.lang.Object this$classification = this.getClassification();
            final java.lang.Object other$classification = other.getClassification();
            if (this$classification == null ? other$classification != null : !this$classification.equals(other$classification)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof AIService.SafetyScanResult;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $riskScore = this.getRiskScore();
            result = result * PRIME + ($riskScore == null ? 43 : $riskScore.hashCode());
            final java.lang.Object $packingRecommendation = this.getPackingRecommendation();
            result = result * PRIME + ($packingRecommendation == null ? 43 : $packingRecommendation.hashCode());
            final java.lang.Object $classification = this.getClassification();
            result = result * PRIME + ($classification == null ? 43 : $classification.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "AIService.SafetyScanResult(riskScore=" + this.getRiskScore() + ", packingRecommendation=" + this.getPackingRecommendation() + ", classification=" + this.getClassification() + ")";
        }
    }

    // AI traveler matching with fallback
    public List<MatchResult> getTravelerMatches(String startCity, String endCity, double weightKg, String category) {
        try {
            Map<String, Object> req = new HashMap<>();
            req.put("start_city", startCity);
            req.put("end_city", endCity);
            req.put("weight_kg", weightKg);
            req.put("category", category);
            ResponseEntity<MatchResult[]> response = restTemplate.postForEntity(aiServiceUrl + "/ai/match", req, MatchResult[].class);
            if (response.getBody() != null) {
                return Arrays.asList(response.getBody());
            }
        } catch (Exception e) {
            log.warn("FastAPI service unavailable, falling back to local rule-based match calculation. Error: {}", e.getMessage());
        }
        // Return rich local mock calculations if FastAPI is offline
        return generateMockMatches(startCity, endCity);
    }

    // AI Pricing predictor with fallback
    public PricePrediction predictPricing(String startCity, String endCity, double weightKg, String priority) {
        try {
            Map<String, Object> req = new HashMap<>();
            req.put("start_city", startCity);
            req.put("end_city", endCity);
            req.put("weight_kg", weightKg);
            req.put("priority", priority);
            ResponseEntity<PricePrediction> response = restTemplate.postForEntity(aiServiceUrl + "/ai/pricing", req, PricePrediction.class);
            if (response.getBody() != null) {
                return response.getBody();
            }
        } catch (Exception e) {
            log.warn("FastAPI pricing failed, falling back to local formulas. Error: {}", e.getMessage());
        }
        // Return local formula price predictions
        double distanceFactor = startCity.equalsIgnoreCase(endCity) ? 50 : 600;
        double weightFactor = weightKg * 50;
        double base = 150 + distanceFactor + weightFactor;
        if ("EMERGENCY".equalsIgnoreCase(priority)) {
            base += 200;
        }
        return PricePrediction.builder().minPrice(BigDecimal.valueOf(Math.round(base * 0.85))).recommendedPrice(BigDecimal.valueOf(Math.round(base))).premiumExpressPrice(BigDecimal.valueOf(Math.round(base * 1.35))).build();
    }

    // AI Safety Scanner with fallback
    public SafetyScanResult scanParcelSafety(String category, String description) {
        try {
            Map<String, Object> req = new HashMap<>();
            req.put("category", category);
            req.put("description", description);
            ResponseEntity<SafetyScanResult> response = restTemplate.postForEntity(aiServiceUrl + "/ai/parcel-safety", req, SafetyScanResult.class);
            if (response.getBody() != null) {
                return response.getBody();
            }
        } catch (Exception e) {
            log.warn("FastAPI safety scan failed. Using local classifier fallback. Error: {}", e.getMessage());
        }
        // Local Fallback matching rules
        int score = switch (category.toUpperCase()) {
            case "ELECTRONICS" -> 20;
            case "FRAGILE" -> 60;
            case "LIQUID" -> 50;
            case "FOOD" -> 15;
            default -> 5;
        };
        return SafetyScanResult.builder().riskScore(score).packingRecommendation("Make sure to place elements in waterproof insulation wrap.").classification(category).build();
    }

    private List<MatchResult> generateMockMatches(String start, String end) {
        List<MatchResult> mockList = new ArrayList<>();
        // Mock Traveler 1
        mockList.add(MatchResult.builder().travelerId(UUID.fromString("00000000-0000-0000-0000-000000000001")).tripId(UUID.randomUUID()).travelerName("Rohan Sharma").rating(4.9).trustScore(98).vehicleType("FLIGHT").matchConfidence(96.5).build());
        // Mock Traveler 2
        mockList.add(MatchResult.builder().travelerId(UUID.fromString("00000000-0000-0000-0000-000000000002")).tripId(UUID.randomUUID()).travelerName("Priya Patel").rating(4.7).trustScore(88).vehicleType("TRAIN").matchConfidence(84.0).build());
        return mockList;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public AIService() {
    }
}
