// Generated by delombok at Thu Jul 16 14:07:14 IST 2026
package com.travelcarry.ai.service;

import com.travelcarry.ai.config.JwtUtils;
import com.travelcarry.ai.dto.AuthResponse;
import com.travelcarry.ai.dto.LoginRequest;
import com.travelcarry.ai.dto.RegisterRequest;
import com.travelcarry.ai.entity.CarbonSavings;
import com.travelcarry.ai.entity.Otp;
import com.travelcarry.ai.entity.User;
import com.travelcarry.ai.entity.Wallet;
import com.travelcarry.ai.exception.BadRequestException;
import com.travelcarry.ai.exception.ResourceNotFoundException;
import com.travelcarry.ai.repository.CarbonSavingsRepository;
import com.travelcarry.ai.repository.OtpRepository;
import com.travelcarry.ai.repository.UserRepository;
import com.travelcarry.ai.repository.WalletRepository;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Optional;
import java.util.Random;

@Service
public class AuthService {
    private final UserRepository userRepository;
    private final WalletRepository walletRepository;
    private final CarbonSavingsRepository carbonSavingsRepository;
    private final OtpRepository otpRepository;
    private final PasswordEncoder passwordEncoder;
    private final JwtUtils jwtUtils;

    @Transactional
    public AuthResponse register(RegisterRequest request) {
        if (userRepository.existsByEmail(request.getEmail())) {
            throw new BadRequestException("Email already in use.");
        }
        if (request.getPhoneNumber() != null && userRepository.existsByPhoneNumber(request.getPhoneNumber())) {
            throw new BadRequestException("Phone number already in use.");
        }
        User user = User.builder().email(request.getEmail()).passwordHash(passwordEncoder.encode(request.getPassword())).firstName(request.getFirstName()).lastName(request.getLastName()).phoneNumber(request.getPhoneNumber()).role(request.getRole()).build();
        User savedUser = userRepository.save(user);
        // Auto-provision Wallet
        Wallet wallet = Wallet.builder().user(savedUser).balance(BigDecimal.ZERO).currency("INR").build();
        walletRepository.save(wallet);
        // Auto-provision CarbonSavings
        CarbonSavings carbonSavings = CarbonSavings.builder().user(savedUser).co2SavedKg(BigDecimal.ZERO).fuelSavedLiters(BigDecimal.ZERO).totalTripsShared(0).build();
        carbonSavingsRepository.save(carbonSavings);
        String token = jwtUtils.generateToken(savedUser.getEmail(), savedUser.getRole());
        return AuthResponse.builder().token(token).userId(savedUser.getId()).email(savedUser.getEmail()).firstName(savedUser.getFirstName()).lastName(savedUser.getLastName()).role(savedUser.getRole()).build();
    }

    public AuthResponse login(LoginRequest request) {
        User user = userRepository.findByEmail(request.getEmail()).orElseThrow(() -> new ResourceNotFoundException("User not found with email: " + request.getEmail()));
        if (!passwordEncoder.matches(request.getPassword(), user.getPasswordHash())) {
            throw new BadRequestException("Invalid email or password.");
        }
        String token = jwtUtils.generateToken(user.getEmail(), user.getRole());
        return AuthResponse.builder().token(token).userId(user.getId()).email(user.getEmail()).firstName(user.getFirstName()).lastName(user.getLastName()).role(user.getRole()).build();
    }

    public String generateOtp(String contact, String purpose) {
        String code = String.format("%06d", new Random().nextInt(999999));
        Otp otp = Otp.builder().email(contact.contains("@") ? contact : null).phoneNumber(!contact.contains("@") ? contact : null).otpCode(code).purpose(purpose).isVerified(false).expiresAt(OffsetDateTime.now().plusMinutes(5)).build();
        otpRepository.save(otp);
        return code; // In production, send via email (Resend) or SMS (Twilio/Firebase)
    }

    public boolean verifyOtp(String contact, String code, String purpose) {
        Optional<Otp> otpOpt = contact.contains("@") ? otpRepository.findByEmailAndOtpCodeAndPurpose(contact, code, purpose) : otpRepository.findByPhoneNumberAndOtpCodeAndPurpose(contact, code, purpose);
        if (otpOpt.isEmpty()) {
            return false;
        }
        Otp otp = otpOpt.get();
        if (otp.getExpiresAt().isBefore(OffsetDateTime.now()) || otp.getIsVerified()) {
            return false;
        }
        otp.setIsVerified(true);
        otpRepository.save(otp);
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public AuthService(final UserRepository userRepository, final WalletRepository walletRepository, final CarbonSavingsRepository carbonSavingsRepository, final OtpRepository otpRepository, final PasswordEncoder passwordEncoder, final JwtUtils jwtUtils) {
        this.userRepository = userRepository;
        this.walletRepository = walletRepository;
        this.carbonSavingsRepository = carbonSavingsRepository;
        this.otpRepository = otpRepository;
        this.passwordEncoder = passwordEncoder;
        this.jwtUtils = jwtUtils;
    }
}
