// Generated by delombok at Thu Jul 16 14:07:14 IST 2026
package com.travelcarry.ai.service;

import com.travelcarry.ai.dto.BookingDTO;
import com.travelcarry.ai.entity.*;
import com.travelcarry.ai.exception.BadRequestException;
import com.travelcarry.ai.exception.ResourceNotFoundException;
import com.travelcarry.ai.repository.BookingRepository;
import com.travelcarry.ai.repository.ParcelRepository;
import com.travelcarry.ai.repository.TripRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Random;
import java.util.UUID;
import java.util.stream.Collectors;

@Service
public class BookingService {
    private final BookingRepository bookingRepository;
    private final TripRepository tripRepository;
    private final ParcelRepository parcelRepository;
    private final WalletService walletService;
    private final TrackingService trackingService;
    private final NotificationService notificationService;

    @Transactional
    public BookingDTO createBooking(UUID tripId, UUID parcelId, BigDecimal price) {
        Trip trip = tripRepository.findById(tripId).orElseThrow(() -> new ResourceNotFoundException("Trip not found"));
        Parcel parcel = parcelRepository.findById(parcelId).orElseThrow(() -> new ResourceNotFoundException("Parcel not found"));
        if (!parcel.getStatus().equals("POSTED")) {
            throw new BadRequestException("Parcel is already booked or completed");
        }
        if (trip.getAvailableSpaceKg().compareTo(parcel.getWeightKg()) < 0) {
            throw new BadRequestException("Not enough luggage capacity on traveler\'s trip");
        }
        // Pricing calculation (15% platform commission)
        BigDecimal commission = price.multiply(BigDecimal.valueOf(0.15));
        BigDecimal basePrice = price.subtract(commission);
        // Generate OTPs
        String pickupOtp = String.format("%06d", new Random().nextInt(999999));
        String deliveryOtp = String.format("%06d", new Random().nextInt(999999));
        Booking booking = Booking.builder().trip(trip).parcel(parcel).traveler(trip.getTraveler()).price(price).commission(commission).basePrice(basePrice).pickupOtp(pickupOtp).deliveryOtp(deliveryOtp).status("PENDING").build();
        // Lock luggage capacity
        trip.setAvailableSpaceKg(trip.getAvailableSpaceKg().subtract(parcel.getWeightKg()));
        tripRepository.save(trip);
        // Update Parcel status
        parcel.setStatus("MATCHED");
        parcelRepository.save(parcel);
        Booking saved = bookingRepository.save(booking);
        // Hold Sender's wallet money in Escrow
        walletService.withdrawFunds(parcel.getSender().getId(), price, "Escrow hold for parcel booking #" + saved.getId().toString().substring(0, 8));
        // Notify Traveler
        notificationService.createNotification(trip.getTraveler().getId(), "New Match Offer", "You have a new delivery request for a " + parcel.getTitle() + " from " + trip.getStartCity() + " to " + trip.getEndCity(), "BOOKING");
        return mapToDTO(saved);
    }

    @Transactional
    public BookingDTO acceptBooking(UUID bookingId) {
        Booking booking = bookingRepository.findById(bookingId).orElseThrow(() -> new ResourceNotFoundException("Booking not found"));
        if (!booking.getStatus().equals("PENDING")) {
            throw new BadRequestException("Booking cannot be accepted from state: " + booking.getStatus());
        }
        booking.setStatus("ACCEPTED");
        Booking saved = bookingRepository.save(booking);
        // Notify Sender
        notificationService.createNotification(booking.getParcel().getSender().getId(), "Traveler Accepted", booking.getTraveler().getFirstName() + " has accepted to carry your parcel. OTP is sent to traveler for verification.", "BOOKING");
        return mapToDTO(saved);
    }

    @Transactional
    public BookingDTO verifyPickup(UUID bookingId, String otpCode) {
        Booking booking = bookingRepository.findById(bookingId).orElseThrow(() -> new ResourceNotFoundException("Booking not found"));
        if (!booking.getStatus().equals("ACCEPTED")) {
            throw new BadRequestException("Invalid state for pickup verification");
        }
        if (!booking.getPickupOtp().equals(otpCode)) {
            throw new BadRequestException("Invalid Pickup OTP code");
        }
        booking.setStatus("PICKED_UP");
        booking.getParcel().setStatus("IN_TRANSIT");
        parcelRepository.save(booking.getParcel());
        Booking saved = bookingRepository.save(booking);
        // Trigger / Initialize tracking
        trackingService.getOrInitializeTracking(bookingId);
        // Notify Sender
        notificationService.createNotification(booking.getParcel().getSender().getId(), "Parcel Picked Up", "Your parcel has been picked up by traveler " + booking.getTraveler().getFirstName() + " and is now in transit.", "BOOKING");
        return mapToDTO(saved);
    }

    @Transactional
    public BookingDTO verifyDelivery(UUID bookingId, String otpCode) {
        Booking booking = bookingRepository.findById(bookingId).orElseThrow(() -> new ResourceNotFoundException("Booking not found"));
        if (!booking.getStatus().equals("PICKED_UP")) {
            throw new BadRequestException("Invalid state for delivery verification");
        }
        if (!booking.getDeliveryOtp().equals(otpCode)) {
            throw new BadRequestException("Invalid Delivery OTP code");
        }
        booking.setStatus("DELIVERED");
        booking.getParcel().setStatus("DELIVERED");
        parcelRepository.save(booking.getParcel());
        Booking saved = bookingRepository.save(booking);
        // Payout transfer (escrow release)
        walletService.addFunds(booking.getTraveler().getId(), booking.getBasePrice(), "Earnings payout for booking #" + booking.getId().toString().substring(0, 8));
        // Update tracking to complete
        trackingService.updateLocation(bookingId, null, null, "Parcel successfully delivered to receiver.");
        // Record carbon stats (Mock route distance 1000 km)
        trackingService.recordCarbonSavings(booking.getTraveler().getId(), 850.0);
        // Notify Sender
        notificationService.createNotification(booking.getParcel().getSender().getId(), "Delivery Completed", "Your parcel was successfully delivered. Please rate the traveler.", "BOOKING");
        // Notify Traveler
        notificationService.createNotification(booking.getTraveler().getId(), "Payout Released", "Payout of INR " + booking.getBasePrice() + " has been added to your wallet.", "BOOKING");
        return mapToDTO(saved);
    }

    public List<BookingDTO> getBookingsForTraveler(UUID travelerId) {
        return bookingRepository.findByTravelerId(travelerId).stream().map(this::mapToDTO).collect(Collectors.toList());
    }

    public List<BookingDTO> getBookingsForSender(UUID senderId) {
        return bookingRepository.findByParcelSenderId(senderId).stream().map(this::mapToDTO).collect(Collectors.toList());
    }

    public BookingDTO getBookingById(UUID id) {
        Booking booking = bookingRepository.findById(id).orElseThrow(() -> new ResourceNotFoundException("Booking not found"));
        return mapToDTO(booking);
    }

    public BookingDTO mapToDTO(Booking b) {
        return BookingDTO.builder().id(b.getId()).parcelId(b.getParcel().getId()).parcelTitle(b.getParcel().getTitle()).tripId(b.getTrip().getId()).travelerId(b.getTraveler().getId()).travelerName(b.getTraveler().getFirstName() + " " + b.getTraveler().getLastName()).senderName(b.getParcel().getSender().getFirstName() + " " + b.getParcel().getSender().getLastName()).price(b.getPrice()).commission(b.getCommission()).basePrice(b.getBasePrice()).status(b.getStatus()).pickupOtp(b.getPickupOtp()).deliveryOtp(b.getDeliveryOtp()).createdAt(b.getCreatedAt()).build();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BookingService(final BookingRepository bookingRepository, final TripRepository tripRepository, final ParcelRepository parcelRepository, final WalletService walletService, final TrackingService trackingService, final NotificationService notificationService) {
        this.bookingRepository = bookingRepository;
        this.tripRepository = tripRepository;
        this.parcelRepository = parcelRepository;
        this.walletService = walletService;
        this.trackingService = trackingService;
        this.notificationService = notificationService;
    }
}
