// Generated by delombok at Thu Jul 16 14:07:14 IST 2026
package com.travelcarry.ai.service;

import com.travelcarry.ai.dto.ChatDTO;
import com.travelcarry.ai.dto.MessageDTO;
import com.travelcarry.ai.entity.Booking;
import com.travelcarry.ai.entity.Chat;
import com.travelcarry.ai.entity.Message;
import com.travelcarry.ai.entity.User;
import com.travelcarry.ai.exception.ResourceNotFoundException;
import com.travelcarry.ai.repository.BookingRepository;
import com.travelcarry.ai.repository.ChatRepository;
import com.travelcarry.ai.repository.MessageRepository;
import com.travelcarry.ai.repository.UserRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

@Service
public class ChatService {
    private final ChatRepository chatRepository;
    private final MessageRepository messageRepository;
    private final BookingRepository bookingRepository;
    private final UserRepository userRepository;

    @Transactional
    public ChatDTO getOrInitializeChat(UUID bookingId) {
        return chatRepository.findByBookingId(bookingId).map(this::mapToDTO).orElseGet(() -> {
            Booking booking = bookingRepository.findById(bookingId).orElseThrow(() -> new ResourceNotFoundException("Booking not found"));
            Chat chat = Chat.builder().booking(booking).traveler(booking.getTraveler()).sender(booking.getParcel().getSender()).build();
            Chat saved = chatRepository.save(chat);
            return mapToDTO(saved);
        });
    }

    @Transactional
    public MessageDTO sendMessage(UUID chatId, UUID senderId, String text) {
        Chat chat = chatRepository.findById(chatId).orElseThrow(() -> new ResourceNotFoundException("Chat thread not found"));
        User sender = userRepository.findById(senderId).orElseThrow(() -> new ResourceNotFoundException("Sender user not found"));
        Message message = Message.builder().chat(chat).sender(sender).messageText(text).isRead(false).build();
        Message saved = messageRepository.save(message);
        return mapMessageToDTO(saved);
    }

    public List<MessageDTO> getMessages(UUID chatId) {
        return messageRepository.findByChatIdOrderByCreatedAtAsc(chatId).stream().map(this::mapMessageToDTO).collect(Collectors.toList());
    }

    public ChatDTO mapToDTO(Chat c) {
        return ChatDTO.builder().id(c.getId()).bookingId(c.getBooking().getId()).travelerId(c.getTraveler().getId()).travelerName(c.getTraveler().getFirstName() + " " + c.getTraveler().getLastName()).senderId(c.getSender().getId()).senderName(c.getSender().getFirstName() + " " + c.getSender().getLastName()).createdAt(c.getCreatedAt()).build();
    }

    private MessageDTO mapMessageToDTO(Message m) {
        return MessageDTO.builder().id(m.getId()).chatId(m.getChat().getId()).senderId(m.getSender().getId()).senderName(m.getSender().getFirstName() + " " + m.getSender().getLastName()).messageText(m.getMessageText()).isRead(m.getIsRead()).createdAt(m.getCreatedAt()).build();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ChatService(final ChatRepository chatRepository, final MessageRepository messageRepository, final BookingRepository bookingRepository, final UserRepository userRepository) {
        this.chatRepository = chatRepository;
        this.messageRepository = messageRepository;
        this.bookingRepository = bookingRepository;
        this.userRepository = userRepository;
    }
}
