// Generated by delombok at Thu Jul 16 14:07:14 IST 2026
package com.travelcarry.ai.service;

import com.travelcarry.ai.dto.ParcelDTO;
import com.travelcarry.ai.entity.Parcel;
import com.travelcarry.ai.entity.User;
import com.travelcarry.ai.exception.ResourceNotFoundException;
import com.travelcarry.ai.repository.ParcelRepository;
import com.travelcarry.ai.repository.UserRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

@Service
public class ParcelService {
    private final ParcelRepository parcelRepository;
    private final UserRepository userRepository;

    @Transactional
    public ParcelDTO createParcel(ParcelDTO dto, UUID senderId) {
        User sender = userRepository.findById(senderId).orElseThrow(() -> new ResourceNotFoundException("User not found"));
        // Mock AI parcel safety check logic for fallback
        int riskScore = calculateMockRisk(dto.getCategory());
        String packingRec = getPackingRecommendation(dto.getCategory());
        Parcel parcel = Parcel.builder().sender(sender).title(dto.getTitle()).description(dto.getDescription()).weightKg(dto.getWeightKg()).widthCm(dto.getWidthCm()).heightCm(dto.getHeightCm()).depthCm(dto.getDepthCm()).startCity(dto.getStartCity()).endCity(dto.getEndCity()).category(dto.getCategory()).riskScore(riskScore).packingRecommendation(packingRec).priority(dto.getPriority()).imageUrl(dto.getImageUrl()).status("POSTED").build();
        Parcel savedParcel = parcelRepository.save(parcel);
        return mapToDTO(savedParcel);
    }

    public ParcelDTO getParcelById(UUID id) {
        Parcel parcel = parcelRepository.findById(id).orElseThrow(() -> new ResourceNotFoundException("Parcel not found"));
        return mapToDTO(parcel);
    }

    public List<ParcelDTO> getParcelsBySender(UUID senderId) {
        return parcelRepository.findBySenderId(senderId).stream().map(this::mapToDTO).collect(Collectors.toList());
    }

    @Transactional
    public ParcelDTO updateParcelStatus(UUID id, String status) {
        Parcel parcel = parcelRepository.findById(id).orElseThrow(() -> new ResourceNotFoundException("Parcel not found"));
        parcel.setStatus(status);
        Parcel savedParcel = parcelRepository.save(parcel);
        return mapToDTO(savedParcel);
    }

    private int calculateMockRisk(String category) {
        return switch (category.toUpperCase()) {
            case "ELECTRONICS" -> 25;
            case "FRAGILE" -> 60;
            case "LIQUID" -> 45;
            case "FOOD" -> 15;
            case "DOCUMENTS" -> 5;
            default -> 10;
        };
    }

    private String getPackingRecommendation(String category) {
        return switch (category.toUpperCase()) {
            case "ELECTRONICS" -> "Wrap in anti-static bubble wrap and use a sturdy exterior box.";
            case "FRAGILE" -> "Layer with cushion foam, label package as FRAGILE, and pack tightly.";
            case "LIQUID" -> "Ensure double-sealed container lids. Place inside a leakproof ziploc bag.";
            case "FOOD" -> "Place in an airtight insulation container with gel coolant pack.";
            case "DOCUMENTS" -> "Store inside a rigid, waterproof document folder to avoid bends.";
            default -> "Standard bubble wrapping inside a standard parcel cardboard box.";
        };
    }

    public ParcelDTO mapToDTO(Parcel parcel) {
        return ParcelDTO.builder().id(parcel.getId()).senderId(parcel.getSender().getId()).senderName(parcel.getSender().getFirstName() + " " + parcel.getSender().getLastName()).title(parcel.getTitle()).description(parcel.getDescription()).weightKg(parcel.getWeightKg()).widthCm(parcel.getWidthCm()).heightCm(parcel.getHeightCm()).depthCm(parcel.getDepthCm()).startCity(parcel.getStartCity()).endCity(parcel.getEndCity()).category(parcel.getCategory()).riskScore(parcel.getRiskScore()).packingRecommendation(parcel.getPackingRecommendation()).priority(parcel.getPriority()).imageUrl(parcel.getImageUrl()).status(parcel.getStatus()).build();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ParcelService(final ParcelRepository parcelRepository, final UserRepository userRepository) {
        this.parcelRepository = parcelRepository;
        this.userRepository = userRepository;
    }
}
