// Generated by delombok at Thu Jul 16 14:07:14 IST 2026
package com.travelcarry.ai.service;

import com.travelcarry.ai.dto.TrackingDTO;
import com.travelcarry.ai.entity.Booking;
import com.travelcarry.ai.entity.CarbonSavings;
import com.travelcarry.ai.entity.Tracking;
import com.travelcarry.ai.entity.User;
import com.travelcarry.ai.exception.ResourceNotFoundException;
import com.travelcarry.ai.repository.BookingRepository;
import com.travelcarry.ai.repository.CarbonSavingsRepository;
import com.travelcarry.ai.repository.TrackingRepository;
import com.travelcarry.ai.repository.UserRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

@Service
public class TrackingService {
    private final TrackingRepository trackingRepository;
    private final BookingRepository bookingRepository;
    private final CarbonSavingsRepository carbonSavingsRepository;
    private final UserRepository userRepository;

    @Transactional
    public TrackingDTO getOrInitializeTracking(UUID bookingId) {
        return trackingRepository.findByBookingId(bookingId).map(this::mapToDTO).orElseGet(() -> {
            Booking booking = bookingRepository.findById(bookingId).orElseThrow(() -> new ResourceNotFoundException("Booking not found"));
            Tracking tracking =  // Default Bangalore/Delhi coords
            Tracking.builder().booking(booking).statusDescription("Booking confirmed. Waiting for traveler pickup.").currentLatitude(BigDecimal.valueOf(12.9716)).currentLongitude(BigDecimal.valueOf(77.5946)).co2SavedKg(BigDecimal.ZERO).estimatedDeliveryTime(OffsetDateTime.now().plusDays(2)).build();
            Tracking saved = trackingRepository.save(tracking);
            return mapToDTO(saved);
        });
    }

    @Transactional
    public TrackingDTO updateLocation(UUID bookingId, BigDecimal latitude, BigDecimal longitude, String statusDesc) {
        Tracking tracking = trackingRepository.findByBookingId(bookingId).orElseThrow(() -> new ResourceNotFoundException("Tracking data not found for booking: " + bookingId));
        tracking.setCurrentLatitude(latitude);
        tracking.setCurrentLongitude(longitude);
        if (statusDesc != null) {
            tracking.setStatusDescription(statusDesc);
        }
        Tracking saved = trackingRepository.save(tracking);
        return mapToDTO(saved);
    }

    @Transactional
    public void recordCarbonSavings(UUID travelerId, double distanceKm) {
        // CO2 saved formula: 1 km flight/truck cargo = 0.25 kg CO2. Since traveler is already flying, we save 100% of that cargo footprint.
        BigDecimal co2Saved = BigDecimal.valueOf(distanceKm * 0.21); // 0.21 kg per km
        BigDecimal fuelSaved = BigDecimal.valueOf(distanceKm * 0.08); // 0.08 liters per km saved compared to truck
        CarbonSavings savings = carbonSavingsRepository.findByUserId(travelerId).orElseGet(() -> CarbonSavings.builder().user(userRepository.findById(travelerId).orElseThrow()).co2SavedKg(BigDecimal.ZERO).fuelSavedLiters(BigDecimal.ZERO).totalTripsShared(0).build());
        savings.setCo2SavedKg(savings.getCo2SavedKg().add(co2Saved));
        savings.setFuelSavedLiters(savings.getFuelSavedLiters().add(fuelSaved));
        savings.setTotalTripsShared(savings.getTotalTripsShared() + 1);
        carbonSavingsRepository.save(savings);
        // Update Traveler completed deliveries & trust level
        User traveler = userRepository.findById(travelerId).orElseThrow();
        traveler.setCompletedDeliveries(traveler.getCompletedDeliveries() + 1);
        traveler.setTrustScore(Math.min(100, traveler.getTrustScore() + 2)); // Add trust points
        if (traveler.getCompletedDeliveries() >= 20 && traveler.getTrustScore() >= 90) {
            traveler.setTrustLevel("Gold Trusted");
        } else if (traveler.getCompletedDeliveries() >= 10) {
            traveler.setTrustLevel("Silver");
        } else {
            traveler.setTrustLevel("Verified");
        }
        userRepository.save(traveler);
    }

    public TrackingDTO mapToDTO(Tracking t) {
        return TrackingDTO.builder().id(t.getId()).bookingId(t.getBooking().getId()).currentLatitude(t.getCurrentLatitude()).currentLongitude(t.getCurrentLongitude()).statusDescription(t.getStatusDescription()).estimatedDeliveryTime(t.getEstimatedDeliveryTime()).co2SavedKg(t.getCo2SavedKg()).lastUpdated(t.getLastUpdated()).build();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public TrackingService(final TrackingRepository trackingRepository, final BookingRepository bookingRepository, final CarbonSavingsRepository carbonSavingsRepository, final UserRepository userRepository) {
        this.trackingRepository = trackingRepository;
        this.bookingRepository = bookingRepository;
        this.carbonSavingsRepository = carbonSavingsRepository;
        this.userRepository = userRepository;
    }
}
