// Generated by delombok at Thu Jul 16 14:07:14 IST 2026
package com.travelcarry.ai.service;

import com.travelcarry.ai.dto.TripDTO;
import com.travelcarry.ai.entity.Trip;
import com.travelcarry.ai.entity.User;
import com.travelcarry.ai.exception.ResourceNotFoundException;
import com.travelcarry.ai.repository.TripRepository;
import com.travelcarry.ai.repository.UserRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

@Service
public class TripService {
    private final TripRepository tripRepository;
    private final UserRepository userRepository;

    @Transactional
    public TripDTO createTrip(TripDTO dto, UUID travelerId) {
        User traveler = userRepository.findById(travelerId).orElseThrow(() -> new ResourceNotFoundException("User not found"));
        Trip trip = Trip.builder().traveler(traveler).startCity(dto.getStartCity()).endCity(dto.getEndCity()).departureDate(dto.getDepartureDate()).arrivalDate(dto.getArrivalDate()).luggageCapacityKg(dto.getLuggageCapacityKg()).availableSpaceKg(dto.getLuggageCapacityKg()).vehicleType(dto.getVehicleType()).status("PLANNED").build();
        Trip savedTrip = tripRepository.save(trip);
        return mapToDTO(savedTrip);
    }

    public TripDTO getTripById(UUID id) {
        Trip trip = tripRepository.findById(id).orElseThrow(() -> new ResourceNotFoundException("Trip not found"));
        return mapToDTO(trip);
    }

    public List<TripDTO> getTripsByTraveler(UUID travelerId) {
        return tripRepository.findByTravelerId(travelerId).stream().map(this::mapToDTO).collect(Collectors.toList());
    }

    public List<TripDTO> searchTrips(String startCity, String endCity) {
        return tripRepository.findByStartCityAndEndCityAndStatus(startCity, endCity, "PLANNED").stream().map(this::mapToDTO).collect(Collectors.toList());
    }

    @Transactional
    public TripDTO updateTripStatus(UUID tripId, String status) {
        Trip trip = tripRepository.findById(tripId).orElseThrow(() -> new ResourceNotFoundException("Trip not found"));
        trip.setStatus(status);
        Trip savedTrip = tripRepository.save(trip);
        return mapToDTO(savedTrip);
    }

    public TripDTO mapToDTO(Trip trip) {
        return TripDTO.builder().id(trip.getId()).travelerId(trip.getTraveler().getId()).travelerName(trip.getTraveler().getFirstName() + " " + trip.getTraveler().getLastName()).startCity(trip.getStartCity()).endCity(trip.getEndCity()).departureDate(trip.getDepartureDate()).arrivalDate(trip.getArrivalDate()).luggageCapacityKg(trip.getLuggageCapacityKg()).availableSpaceKg(trip.getAvailableSpaceKg()).vehicleType(trip.getVehicleType()).status(trip.getStatus()).build();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public TripService(final TripRepository tripRepository, final UserRepository userRepository) {
        this.tripRepository = tripRepository;
        this.userRepository = userRepository;
    }
}
