// Generated by delombok at Thu Jul 16 14:07:14 IST 2026
package com.travelcarry.ai.service;

import com.travelcarry.ai.dto.WalletDTO;
import com.travelcarry.ai.entity.Wallet;
import com.travelcarry.ai.entity.WalletHistory;
import com.travelcarry.ai.exception.BadRequestException;
import com.travelcarry.ai.exception.ResourceNotFoundException;
import com.travelcarry.ai.repository.WalletHistoryRepository;
import com.travelcarry.ai.repository.WalletRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

@Service
public class WalletService {
    private final WalletRepository walletRepository;
    private final WalletHistoryRepository walletHistoryRepository;

    public WalletDTO getWalletByUser(UUID userId) {
        Wallet wallet = walletRepository.findByUserId(userId).orElseThrow(() -> new ResourceNotFoundException("Wallet not found for user: " + userId));
        List<WalletHistory> histories = walletHistoryRepository.findByWalletIdOrderByCreatedAtDesc(wallet.getId());
        List<WalletDTO.WalletHistoryDTO> historyDTOs = histories.stream().map(h -> WalletDTO.WalletHistoryDTO.builder().id(h.getId()).amount(h.getAmount()).type(h.getType()).description(h.getDescription()).createdAt(h.getCreatedAt()).build()).collect(Collectors.toList());
        return WalletDTO.builder().id(wallet.getId()).userId(wallet.getUser().getId()).balance(wallet.getBalance()).currency(wallet.getCurrency()).history(historyDTOs).build();
    }

    @Transactional
    public WalletDTO addFunds(UUID userId, BigDecimal amount, String description) {
        if (amount.compareTo(BigDecimal.ZERO) <= 0) {
            throw new BadRequestException("Amount must be positive");
        }
        Wallet wallet = walletRepository.findByUserId(userId).orElseThrow(() -> new ResourceNotFoundException("Wallet not found"));
        wallet.setBalance(wallet.getBalance().add(amount));
        walletRepository.save(wallet);
        WalletHistory history = WalletHistory.builder().wallet(wallet).amount(amount).type("DEPOSIT").description(description).build();
        walletHistoryRepository.save(history);
        return getWalletByUser(userId);
    }

    @Transactional
    public WalletDTO withdrawFunds(UUID userId, BigDecimal amount, String description) {
        if (amount.compareTo(BigDecimal.ZERO) <= 0) {
            throw new BadRequestException("Amount must be positive");
        }
        Wallet wallet = walletRepository.findByUserId(userId).orElseThrow(() -> new ResourceNotFoundException("Wallet not found"));
        if (wallet.getBalance().compareTo(amount) < 0) {
            throw new BadRequestException("Insufficient balance");
        }
        wallet.setBalance(wallet.getBalance().subtract(amount));
        walletRepository.save(wallet);
        WalletHistory history = WalletHistory.builder().wallet(wallet).amount(amount.negate()).type("WITHDRAWAL").description(description).build();
        walletHistoryRepository.save(history);
        return getWalletByUser(userId);
    }

    @Transactional
    public void transferEscrow(UUID fromUserId, UUID toUserId, BigDecimal amount, String description) {
        Wallet fromWallet = walletRepository.findByUserId(fromUserId).orElseThrow(() -> new ResourceNotFoundException("Sender wallet not found"));
        Wallet toWallet = walletRepository.findByUserId(toUserId).orElseThrow(() -> new ResourceNotFoundException("Traveler wallet not found"));
        if (fromWallet.getBalance().compareTo(amount) < 0) {
            throw new BadRequestException("Sender has insufficient funds in wallet");
        }
        // Deduct from sender
        fromWallet.setBalance(fromWallet.getBalance().subtract(amount));
        walletRepository.save(fromWallet);
        WalletHistory senderHistory = WalletHistory.builder().wallet(fromWallet).amount(amount.negate()).type("ESCROW_HOLD").description(description + " (Escrow hold)").build();
        walletHistoryRepository.save(senderHistory);
        // Add to traveler
        toWallet.setBalance(toWallet.getBalance().add(amount));
        walletRepository.save(toWallet);
        WalletHistory travelerHistory = WalletHistory.builder().wallet(toWallet).amount(amount).type("EARNING").description(description + " (Payout released)").build();
        walletHistoryRepository.save(travelerHistory);
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public WalletService(final WalletRepository walletRepository, final WalletHistoryRepository walletHistoryRepository) {
        this.walletRepository = walletRepository;
        this.walletHistoryRepository = walletHistoryRepository;
    }
}
