// Generated by delombok at Thu Jul 16 14:07:14 IST 2026
package com.travelcarry.ai.dto;

import lombok.*;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

public class BookingDTO {
    private UUID id;
    private UUID parcelId;
    private String parcelTitle;
    private UUID tripId;
    private UUID travelerId;
    private String travelerName;
    private String senderName;
    private BigDecimal price;
    private BigDecimal commission;
    private BigDecimal basePrice;
    private String status;
    private String pickupOtp;
    private String deliveryOtp;
    private OffsetDateTime createdAt;


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class BookingDTOBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UUID id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UUID parcelId;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String parcelTitle;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UUID tripId;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UUID travelerId;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String travelerName;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String senderName;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal price;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal commission;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal basePrice;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String status;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String pickupOtp;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String deliveryOtp;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private OffsetDateTime createdAt;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        BookingDTOBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public BookingDTO.BookingDTOBuilder id(final UUID id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public BookingDTO.BookingDTOBuilder parcelId(final UUID parcelId) {
            this.parcelId = parcelId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public BookingDTO.BookingDTOBuilder parcelTitle(final String parcelTitle) {
            this.parcelTitle = parcelTitle;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public BookingDTO.BookingDTOBuilder tripId(final UUID tripId) {
            this.tripId = tripId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public BookingDTO.BookingDTOBuilder travelerId(final UUID travelerId) {
            this.travelerId = travelerId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public BookingDTO.BookingDTOBuilder travelerName(final String travelerName) {
            this.travelerName = travelerName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public BookingDTO.BookingDTOBuilder senderName(final String senderName) {
            this.senderName = senderName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public BookingDTO.BookingDTOBuilder price(final BigDecimal price) {
            this.price = price;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public BookingDTO.BookingDTOBuilder commission(final BigDecimal commission) {
            this.commission = commission;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public BookingDTO.BookingDTOBuilder basePrice(final BigDecimal basePrice) {
            this.basePrice = basePrice;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public BookingDTO.BookingDTOBuilder status(final String status) {
            this.status = status;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public BookingDTO.BookingDTOBuilder pickupOtp(final String pickupOtp) {
            this.pickupOtp = pickupOtp;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public BookingDTO.BookingDTOBuilder deliveryOtp(final String deliveryOtp) {
            this.deliveryOtp = deliveryOtp;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public BookingDTO.BookingDTOBuilder createdAt(final OffsetDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public BookingDTO build() {
            return new BookingDTO(this.id, this.parcelId, this.parcelTitle, this.tripId, this.travelerId, this.travelerName, this.senderName, this.price, this.commission, this.basePrice, this.status, this.pickupOtp, this.deliveryOtp, this.createdAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "BookingDTO.BookingDTOBuilder(id=" + this.id + ", parcelId=" + this.parcelId + ", parcelTitle=" + this.parcelTitle + ", tripId=" + this.tripId + ", travelerId=" + this.travelerId + ", travelerName=" + this.travelerName + ", senderName=" + this.senderName + ", price=" + this.price + ", commission=" + this.commission + ", basePrice=" + this.basePrice + ", status=" + this.status + ", pickupOtp=" + this.pickupOtp + ", deliveryOtp=" + this.deliveryOtp + ", createdAt=" + this.createdAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static BookingDTO.BookingDTOBuilder builder() {
        return new BookingDTO.BookingDTOBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UUID getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UUID getParcelId() {
        return this.parcelId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getParcelTitle() {
        return this.parcelTitle;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UUID getTripId() {
        return this.tripId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UUID getTravelerId() {
        return this.travelerId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTravelerName() {
        return this.travelerName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSenderName() {
        return this.senderName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getPrice() {
        return this.price;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getCommission() {
        return this.commission;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getBasePrice() {
        return this.basePrice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPickupOtp() {
        return this.pickupOtp;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDeliveryOtp() {
        return this.deliveryOtp;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final UUID id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setParcelId(final UUID parcelId) {
        this.parcelId = parcelId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setParcelTitle(final String parcelTitle) {
        this.parcelTitle = parcelTitle;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTripId(final UUID tripId) {
        this.tripId = tripId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTravelerId(final UUID travelerId) {
        this.travelerId = travelerId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTravelerName(final String travelerName) {
        this.travelerName = travelerName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSenderName(final String senderName) {
        this.senderName = senderName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPrice(final BigDecimal price) {
        this.price = price;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCommission(final BigDecimal commission) {
        this.commission = commission;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBasePrice(final BigDecimal basePrice) {
        this.basePrice = basePrice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPickupOtp(final String pickupOtp) {
        this.pickupOtp = pickupOtp;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDeliveryOtp(final String deliveryOtp) {
        this.deliveryOtp = deliveryOtp;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof BookingDTO)) return false;
        final BookingDTO other = (BookingDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$parcelId = this.getParcelId();
        final java.lang.Object other$parcelId = other.getParcelId();
        if (this$parcelId == null ? other$parcelId != null : !this$parcelId.equals(other$parcelId)) return false;
        final java.lang.Object this$parcelTitle = this.getParcelTitle();
        final java.lang.Object other$parcelTitle = other.getParcelTitle();
        if (this$parcelTitle == null ? other$parcelTitle != null : !this$parcelTitle.equals(other$parcelTitle)) return false;
        final java.lang.Object this$tripId = this.getTripId();
        final java.lang.Object other$tripId = other.getTripId();
        if (this$tripId == null ? other$tripId != null : !this$tripId.equals(other$tripId)) return false;
        final java.lang.Object this$travelerId = this.getTravelerId();
        final java.lang.Object other$travelerId = other.getTravelerId();
        if (this$travelerId == null ? other$travelerId != null : !this$travelerId.equals(other$travelerId)) return false;
        final java.lang.Object this$travelerName = this.getTravelerName();
        final java.lang.Object other$travelerName = other.getTravelerName();
        if (this$travelerName == null ? other$travelerName != null : !this$travelerName.equals(other$travelerName)) return false;
        final java.lang.Object this$senderName = this.getSenderName();
        final java.lang.Object other$senderName = other.getSenderName();
        if (this$senderName == null ? other$senderName != null : !this$senderName.equals(other$senderName)) return false;
        final java.lang.Object this$price = this.getPrice();
        final java.lang.Object other$price = other.getPrice();
        if (this$price == null ? other$price != null : !this$price.equals(other$price)) return false;
        final java.lang.Object this$commission = this.getCommission();
        final java.lang.Object other$commission = other.getCommission();
        if (this$commission == null ? other$commission != null : !this$commission.equals(other$commission)) return false;
        final java.lang.Object this$basePrice = this.getBasePrice();
        final java.lang.Object other$basePrice = other.getBasePrice();
        if (this$basePrice == null ? other$basePrice != null : !this$basePrice.equals(other$basePrice)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$pickupOtp = this.getPickupOtp();
        final java.lang.Object other$pickupOtp = other.getPickupOtp();
        if (this$pickupOtp == null ? other$pickupOtp != null : !this$pickupOtp.equals(other$pickupOtp)) return false;
        final java.lang.Object this$deliveryOtp = this.getDeliveryOtp();
        final java.lang.Object other$deliveryOtp = other.getDeliveryOtp();
        if (this$deliveryOtp == null ? other$deliveryOtp != null : !this$deliveryOtp.equals(other$deliveryOtp)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof BookingDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $parcelId = this.getParcelId();
        result = result * PRIME + ($parcelId == null ? 43 : $parcelId.hashCode());
        final java.lang.Object $parcelTitle = this.getParcelTitle();
        result = result * PRIME + ($parcelTitle == null ? 43 : $parcelTitle.hashCode());
        final java.lang.Object $tripId = this.getTripId();
        result = result * PRIME + ($tripId == null ? 43 : $tripId.hashCode());
        final java.lang.Object $travelerId = this.getTravelerId();
        result = result * PRIME + ($travelerId == null ? 43 : $travelerId.hashCode());
        final java.lang.Object $travelerName = this.getTravelerName();
        result = result * PRIME + ($travelerName == null ? 43 : $travelerName.hashCode());
        final java.lang.Object $senderName = this.getSenderName();
        result = result * PRIME + ($senderName == null ? 43 : $senderName.hashCode());
        final java.lang.Object $price = this.getPrice();
        result = result * PRIME + ($price == null ? 43 : $price.hashCode());
        final java.lang.Object $commission = this.getCommission();
        result = result * PRIME + ($commission == null ? 43 : $commission.hashCode());
        final java.lang.Object $basePrice = this.getBasePrice();
        result = result * PRIME + ($basePrice == null ? 43 : $basePrice.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $pickupOtp = this.getPickupOtp();
        result = result * PRIME + ($pickupOtp == null ? 43 : $pickupOtp.hashCode());
        final java.lang.Object $deliveryOtp = this.getDeliveryOtp();
        result = result * PRIME + ($deliveryOtp == null ? 43 : $deliveryOtp.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "BookingDTO(id=" + this.getId() + ", parcelId=" + this.getParcelId() + ", parcelTitle=" + this.getParcelTitle() + ", tripId=" + this.getTripId() + ", travelerId=" + this.getTravelerId() + ", travelerName=" + this.getTravelerName() + ", senderName=" + this.getSenderName() + ", price=" + this.getPrice() + ", commission=" + this.getCommission() + ", basePrice=" + this.getBasePrice() + ", status=" + this.getStatus() + ", pickupOtp=" + this.getPickupOtp() + ", deliveryOtp=" + this.getDeliveryOtp() + ", createdAt=" + this.getCreatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BookingDTO() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BookingDTO(final UUID id, final UUID parcelId, final String parcelTitle, final UUID tripId, final UUID travelerId, final String travelerName, final String senderName, final BigDecimal price, final BigDecimal commission, final BigDecimal basePrice, final String status, final String pickupOtp, final String deliveryOtp, final OffsetDateTime createdAt) {
        this.id = id;
        this.parcelId = parcelId;
        this.parcelTitle = parcelTitle;
        this.tripId = tripId;
        this.travelerId = travelerId;
        this.travelerName = travelerName;
        this.senderName = senderName;
        this.price = price;
        this.commission = commission;
        this.basePrice = basePrice;
        this.status = status;
        this.pickupOtp = pickupOtp;
        this.deliveryOtp = deliveryOtp;
        this.createdAt = createdAt;
    }
}
