// Generated by delombok at Thu Jul 16 14:07:14 IST 2026
package com.travelcarry.ai.dto;

import lombok.*;
import java.time.OffsetDateTime;
import java.util.UUID;

public class ChatDTO {
    private UUID id;
    private UUID bookingId;
    private UUID travelerId;
    private String travelerName;
    private UUID senderId;
    private String senderName;
    private OffsetDateTime createdAt;


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class ChatDTOBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UUID id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UUID bookingId;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UUID travelerId;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String travelerName;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UUID senderId;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String senderName;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private OffsetDateTime createdAt;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        ChatDTOBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ChatDTO.ChatDTOBuilder id(final UUID id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ChatDTO.ChatDTOBuilder bookingId(final UUID bookingId) {
            this.bookingId = bookingId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ChatDTO.ChatDTOBuilder travelerId(final UUID travelerId) {
            this.travelerId = travelerId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ChatDTO.ChatDTOBuilder travelerName(final String travelerName) {
            this.travelerName = travelerName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ChatDTO.ChatDTOBuilder senderId(final UUID senderId) {
            this.senderId = senderId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ChatDTO.ChatDTOBuilder senderName(final String senderName) {
            this.senderName = senderName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ChatDTO.ChatDTOBuilder createdAt(final OffsetDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ChatDTO build() {
            return new ChatDTO(this.id, this.bookingId, this.travelerId, this.travelerName, this.senderId, this.senderName, this.createdAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "ChatDTO.ChatDTOBuilder(id=" + this.id + ", bookingId=" + this.bookingId + ", travelerId=" + this.travelerId + ", travelerName=" + this.travelerName + ", senderId=" + this.senderId + ", senderName=" + this.senderName + ", createdAt=" + this.createdAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static ChatDTO.ChatDTOBuilder builder() {
        return new ChatDTO.ChatDTOBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UUID getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UUID getBookingId() {
        return this.bookingId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UUID getTravelerId() {
        return this.travelerId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTravelerName() {
        return this.travelerName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UUID getSenderId() {
        return this.senderId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSenderName() {
        return this.senderName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final UUID id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBookingId(final UUID bookingId) {
        this.bookingId = bookingId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTravelerId(final UUID travelerId) {
        this.travelerId = travelerId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTravelerName(final String travelerName) {
        this.travelerName = travelerName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSenderId(final UUID senderId) {
        this.senderId = senderId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSenderName(final String senderName) {
        this.senderName = senderName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ChatDTO)) return false;
        final ChatDTO other = (ChatDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$bookingId = this.getBookingId();
        final java.lang.Object other$bookingId = other.getBookingId();
        if (this$bookingId == null ? other$bookingId != null : !this$bookingId.equals(other$bookingId)) return false;
        final java.lang.Object this$travelerId = this.getTravelerId();
        final java.lang.Object other$travelerId = other.getTravelerId();
        if (this$travelerId == null ? other$travelerId != null : !this$travelerId.equals(other$travelerId)) return false;
        final java.lang.Object this$travelerName = this.getTravelerName();
        final java.lang.Object other$travelerName = other.getTravelerName();
        if (this$travelerName == null ? other$travelerName != null : !this$travelerName.equals(other$travelerName)) return false;
        final java.lang.Object this$senderId = this.getSenderId();
        final java.lang.Object other$senderId = other.getSenderId();
        if (this$senderId == null ? other$senderId != null : !this$senderId.equals(other$senderId)) return false;
        final java.lang.Object this$senderName = this.getSenderName();
        final java.lang.Object other$senderName = other.getSenderName();
        if (this$senderName == null ? other$senderName != null : !this$senderName.equals(other$senderName)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ChatDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $bookingId = this.getBookingId();
        result = result * PRIME + ($bookingId == null ? 43 : $bookingId.hashCode());
        final java.lang.Object $travelerId = this.getTravelerId();
        result = result * PRIME + ($travelerId == null ? 43 : $travelerId.hashCode());
        final java.lang.Object $travelerName = this.getTravelerName();
        result = result * PRIME + ($travelerName == null ? 43 : $travelerName.hashCode());
        final java.lang.Object $senderId = this.getSenderId();
        result = result * PRIME + ($senderId == null ? 43 : $senderId.hashCode());
        final java.lang.Object $senderName = this.getSenderName();
        result = result * PRIME + ($senderName == null ? 43 : $senderName.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "ChatDTO(id=" + this.getId() + ", bookingId=" + this.getBookingId() + ", travelerId=" + this.getTravelerId() + ", travelerName=" + this.getTravelerName() + ", senderId=" + this.getSenderId() + ", senderName=" + this.getSenderName() + ", createdAt=" + this.getCreatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ChatDTO() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ChatDTO(final UUID id, final UUID bookingId, final UUID travelerId, final String travelerName, final UUID senderId, final String senderName, final OffsetDateTime createdAt) {
        this.id = id;
        this.bookingId = bookingId;
        this.travelerId = travelerId;
        this.travelerName = travelerName;
        this.senderId = senderId;
        this.senderName = senderName;
        this.createdAt = createdAt;
    }
}
