// Generated by delombok at Thu Jul 16 14:07:14 IST 2026
package com.travelcarry.ai.dto;

import lombok.*;
import java.time.OffsetDateTime;
import java.util.UUID;

public class MessageDTO {
    private UUID id;
    private UUID chatId;
    private UUID senderId;
    private String senderName;
    private String messageText;
    private Boolean isRead;
    private OffsetDateTime createdAt;


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class MessageDTOBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UUID id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UUID chatId;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UUID senderId;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String senderName;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String messageText;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Boolean isRead;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private OffsetDateTime createdAt;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        MessageDTOBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public MessageDTO.MessageDTOBuilder id(final UUID id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public MessageDTO.MessageDTOBuilder chatId(final UUID chatId) {
            this.chatId = chatId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public MessageDTO.MessageDTOBuilder senderId(final UUID senderId) {
            this.senderId = senderId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public MessageDTO.MessageDTOBuilder senderName(final String senderName) {
            this.senderName = senderName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public MessageDTO.MessageDTOBuilder messageText(final String messageText) {
            this.messageText = messageText;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public MessageDTO.MessageDTOBuilder isRead(final Boolean isRead) {
            this.isRead = isRead;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public MessageDTO.MessageDTOBuilder createdAt(final OffsetDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public MessageDTO build() {
            return new MessageDTO(this.id, this.chatId, this.senderId, this.senderName, this.messageText, this.isRead, this.createdAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "MessageDTO.MessageDTOBuilder(id=" + this.id + ", chatId=" + this.chatId + ", senderId=" + this.senderId + ", senderName=" + this.senderName + ", messageText=" + this.messageText + ", isRead=" + this.isRead + ", createdAt=" + this.createdAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static MessageDTO.MessageDTOBuilder builder() {
        return new MessageDTO.MessageDTOBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UUID getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UUID getChatId() {
        return this.chatId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UUID getSenderId() {
        return this.senderId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSenderName() {
        return this.senderName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getMessageText() {
        return this.messageText;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Boolean getIsRead() {
        return this.isRead;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final UUID id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setChatId(final UUID chatId) {
        this.chatId = chatId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSenderId(final UUID senderId) {
        this.senderId = senderId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSenderName(final String senderName) {
        this.senderName = senderName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMessageText(final String messageText) {
        this.messageText = messageText;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setIsRead(final Boolean isRead) {
        this.isRead = isRead;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof MessageDTO)) return false;
        final MessageDTO other = (MessageDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$isRead = this.getIsRead();
        final java.lang.Object other$isRead = other.getIsRead();
        if (this$isRead == null ? other$isRead != null : !this$isRead.equals(other$isRead)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$chatId = this.getChatId();
        final java.lang.Object other$chatId = other.getChatId();
        if (this$chatId == null ? other$chatId != null : !this$chatId.equals(other$chatId)) return false;
        final java.lang.Object this$senderId = this.getSenderId();
        final java.lang.Object other$senderId = other.getSenderId();
        if (this$senderId == null ? other$senderId != null : !this$senderId.equals(other$senderId)) return false;
        final java.lang.Object this$senderName = this.getSenderName();
        final java.lang.Object other$senderName = other.getSenderName();
        if (this$senderName == null ? other$senderName != null : !this$senderName.equals(other$senderName)) return false;
        final java.lang.Object this$messageText = this.getMessageText();
        final java.lang.Object other$messageText = other.getMessageText();
        if (this$messageText == null ? other$messageText != null : !this$messageText.equals(other$messageText)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof MessageDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $isRead = this.getIsRead();
        result = result * PRIME + ($isRead == null ? 43 : $isRead.hashCode());
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $chatId = this.getChatId();
        result = result * PRIME + ($chatId == null ? 43 : $chatId.hashCode());
        final java.lang.Object $senderId = this.getSenderId();
        result = result * PRIME + ($senderId == null ? 43 : $senderId.hashCode());
        final java.lang.Object $senderName = this.getSenderName();
        result = result * PRIME + ($senderName == null ? 43 : $senderName.hashCode());
        final java.lang.Object $messageText = this.getMessageText();
        result = result * PRIME + ($messageText == null ? 43 : $messageText.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "MessageDTO(id=" + this.getId() + ", chatId=" + this.getChatId() + ", senderId=" + this.getSenderId() + ", senderName=" + this.getSenderName() + ", messageText=" + this.getMessageText() + ", isRead=" + this.getIsRead() + ", createdAt=" + this.getCreatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public MessageDTO() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public MessageDTO(final UUID id, final UUID chatId, final UUID senderId, final String senderName, final String messageText, final Boolean isRead, final OffsetDateTime createdAt) {
        this.id = id;
        this.chatId = chatId;
        this.senderId = senderId;
        this.senderName = senderName;
        this.messageText = messageText;
        this.isRead = isRead;
        this.createdAt = createdAt;
    }
}
