// Generated by delombok at Thu Jul 16 14:07:14 IST 2026
package com.travelcarry.ai.dto;

import lombok.*;
import java.math.BigDecimal;
import java.util.UUID;

public class ParcelDTO {
    private UUID id;
    private UUID senderId;
    private String senderName;
    private String title;
    private String description;
    private BigDecimal weightKg;
    private BigDecimal widthCm;
    private BigDecimal heightCm;
    private BigDecimal depthCm;
    private String startCity;
    private String endCity;
    private String category;
    private Integer riskScore;
    private String packingRecommendation;
    private String priority;
    private String imageUrl;
    private String status;


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class ParcelDTOBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UUID id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UUID senderId;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String senderName;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String title;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String description;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal weightKg;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal widthCm;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal heightCm;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal depthCm;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String startCity;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String endCity;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String category;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Integer riskScore;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String packingRecommendation;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String priority;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String imageUrl;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String status;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        ParcelDTOBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ParcelDTO.ParcelDTOBuilder id(final UUID id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ParcelDTO.ParcelDTOBuilder senderId(final UUID senderId) {
            this.senderId = senderId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ParcelDTO.ParcelDTOBuilder senderName(final String senderName) {
            this.senderName = senderName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ParcelDTO.ParcelDTOBuilder title(final String title) {
            this.title = title;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ParcelDTO.ParcelDTOBuilder description(final String description) {
            this.description = description;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ParcelDTO.ParcelDTOBuilder weightKg(final BigDecimal weightKg) {
            this.weightKg = weightKg;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ParcelDTO.ParcelDTOBuilder widthCm(final BigDecimal widthCm) {
            this.widthCm = widthCm;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ParcelDTO.ParcelDTOBuilder heightCm(final BigDecimal heightCm) {
            this.heightCm = heightCm;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ParcelDTO.ParcelDTOBuilder depthCm(final BigDecimal depthCm) {
            this.depthCm = depthCm;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ParcelDTO.ParcelDTOBuilder startCity(final String startCity) {
            this.startCity = startCity;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ParcelDTO.ParcelDTOBuilder endCity(final String endCity) {
            this.endCity = endCity;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ParcelDTO.ParcelDTOBuilder category(final String category) {
            this.category = category;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ParcelDTO.ParcelDTOBuilder riskScore(final Integer riskScore) {
            this.riskScore = riskScore;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ParcelDTO.ParcelDTOBuilder packingRecommendation(final String packingRecommendation) {
            this.packingRecommendation = packingRecommendation;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ParcelDTO.ParcelDTOBuilder priority(final String priority) {
            this.priority = priority;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ParcelDTO.ParcelDTOBuilder imageUrl(final String imageUrl) {
            this.imageUrl = imageUrl;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ParcelDTO.ParcelDTOBuilder status(final String status) {
            this.status = status;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ParcelDTO build() {
            return new ParcelDTO(this.id, this.senderId, this.senderName, this.title, this.description, this.weightKg, this.widthCm, this.heightCm, this.depthCm, this.startCity, this.endCity, this.category, this.riskScore, this.packingRecommendation, this.priority, this.imageUrl, this.status);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "ParcelDTO.ParcelDTOBuilder(id=" + this.id + ", senderId=" + this.senderId + ", senderName=" + this.senderName + ", title=" + this.title + ", description=" + this.description + ", weightKg=" + this.weightKg + ", widthCm=" + this.widthCm + ", heightCm=" + this.heightCm + ", depthCm=" + this.depthCm + ", startCity=" + this.startCity + ", endCity=" + this.endCity + ", category=" + this.category + ", riskScore=" + this.riskScore + ", packingRecommendation=" + this.packingRecommendation + ", priority=" + this.priority + ", imageUrl=" + this.imageUrl + ", status=" + this.status + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static ParcelDTO.ParcelDTOBuilder builder() {
        return new ParcelDTO.ParcelDTOBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UUID getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UUID getSenderId() {
        return this.senderId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSenderName() {
        return this.senderName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getWeightKg() {
        return this.weightKg;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getWidthCm() {
        return this.widthCm;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getHeightCm() {
        return this.heightCm;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getDepthCm() {
        return this.depthCm;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStartCity() {
        return this.startCity;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getEndCity() {
        return this.endCity;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCategory() {
        return this.category;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getRiskScore() {
        return this.riskScore;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPackingRecommendation() {
        return this.packingRecommendation;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPriority() {
        return this.priority;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getImageUrl() {
        return this.imageUrl;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final UUID id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSenderId(final UUID senderId) {
        this.senderId = senderId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSenderName(final String senderName) {
        this.senderName = senderName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTitle(final String title) {
        this.title = title;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWeightKg(final BigDecimal weightKg) {
        this.weightKg = weightKg;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWidthCm(final BigDecimal widthCm) {
        this.widthCm = widthCm;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setHeightCm(final BigDecimal heightCm) {
        this.heightCm = heightCm;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDepthCm(final BigDecimal depthCm) {
        this.depthCm = depthCm;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStartCity(final String startCity) {
        this.startCity = startCity;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEndCity(final String endCity) {
        this.endCity = endCity;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCategory(final String category) {
        this.category = category;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRiskScore(final Integer riskScore) {
        this.riskScore = riskScore;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPackingRecommendation(final String packingRecommendation) {
        this.packingRecommendation = packingRecommendation;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPriority(final String priority) {
        this.priority = priority;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setImageUrl(final String imageUrl) {
        this.imageUrl = imageUrl;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ParcelDTO)) return false;
        final ParcelDTO other = (ParcelDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$riskScore = this.getRiskScore();
        final java.lang.Object other$riskScore = other.getRiskScore();
        if (this$riskScore == null ? other$riskScore != null : !this$riskScore.equals(other$riskScore)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$senderId = this.getSenderId();
        final java.lang.Object other$senderId = other.getSenderId();
        if (this$senderId == null ? other$senderId != null : !this$senderId.equals(other$senderId)) return false;
        final java.lang.Object this$senderName = this.getSenderName();
        final java.lang.Object other$senderName = other.getSenderName();
        if (this$senderName == null ? other$senderName != null : !this$senderName.equals(other$senderName)) return false;
        final java.lang.Object this$title = this.getTitle();
        final java.lang.Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        final java.lang.Object this$weightKg = this.getWeightKg();
        final java.lang.Object other$weightKg = other.getWeightKg();
        if (this$weightKg == null ? other$weightKg != null : !this$weightKg.equals(other$weightKg)) return false;
        final java.lang.Object this$widthCm = this.getWidthCm();
        final java.lang.Object other$widthCm = other.getWidthCm();
        if (this$widthCm == null ? other$widthCm != null : !this$widthCm.equals(other$widthCm)) return false;
        final java.lang.Object this$heightCm = this.getHeightCm();
        final java.lang.Object other$heightCm = other.getHeightCm();
        if (this$heightCm == null ? other$heightCm != null : !this$heightCm.equals(other$heightCm)) return false;
        final java.lang.Object this$depthCm = this.getDepthCm();
        final java.lang.Object other$depthCm = other.getDepthCm();
        if (this$depthCm == null ? other$depthCm != null : !this$depthCm.equals(other$depthCm)) return false;
        final java.lang.Object this$startCity = this.getStartCity();
        final java.lang.Object other$startCity = other.getStartCity();
        if (this$startCity == null ? other$startCity != null : !this$startCity.equals(other$startCity)) return false;
        final java.lang.Object this$endCity = this.getEndCity();
        final java.lang.Object other$endCity = other.getEndCity();
        if (this$endCity == null ? other$endCity != null : !this$endCity.equals(other$endCity)) return false;
        final java.lang.Object this$category = this.getCategory();
        final java.lang.Object other$category = other.getCategory();
        if (this$category == null ? other$category != null : !this$category.equals(other$category)) return false;
        final java.lang.Object this$packingRecommendation = this.getPackingRecommendation();
        final java.lang.Object other$packingRecommendation = other.getPackingRecommendation();
        if (this$packingRecommendation == null ? other$packingRecommendation != null : !this$packingRecommendation.equals(other$packingRecommendation)) return false;
        final java.lang.Object this$priority = this.getPriority();
        final java.lang.Object other$priority = other.getPriority();
        if (this$priority == null ? other$priority != null : !this$priority.equals(other$priority)) return false;
        final java.lang.Object this$imageUrl = this.getImageUrl();
        final java.lang.Object other$imageUrl = other.getImageUrl();
        if (this$imageUrl == null ? other$imageUrl != null : !this$imageUrl.equals(other$imageUrl)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ParcelDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $riskScore = this.getRiskScore();
        result = result * PRIME + ($riskScore == null ? 43 : $riskScore.hashCode());
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $senderId = this.getSenderId();
        result = result * PRIME + ($senderId == null ? 43 : $senderId.hashCode());
        final java.lang.Object $senderName = this.getSenderName();
        result = result * PRIME + ($senderName == null ? 43 : $senderName.hashCode());
        final java.lang.Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        final java.lang.Object $weightKg = this.getWeightKg();
        result = result * PRIME + ($weightKg == null ? 43 : $weightKg.hashCode());
        final java.lang.Object $widthCm = this.getWidthCm();
        result = result * PRIME + ($widthCm == null ? 43 : $widthCm.hashCode());
        final java.lang.Object $heightCm = this.getHeightCm();
        result = result * PRIME + ($heightCm == null ? 43 : $heightCm.hashCode());
        final java.lang.Object $depthCm = this.getDepthCm();
        result = result * PRIME + ($depthCm == null ? 43 : $depthCm.hashCode());
        final java.lang.Object $startCity = this.getStartCity();
        result = result * PRIME + ($startCity == null ? 43 : $startCity.hashCode());
        final java.lang.Object $endCity = this.getEndCity();
        result = result * PRIME + ($endCity == null ? 43 : $endCity.hashCode());
        final java.lang.Object $category = this.getCategory();
        result = result * PRIME + ($category == null ? 43 : $category.hashCode());
        final java.lang.Object $packingRecommendation = this.getPackingRecommendation();
        result = result * PRIME + ($packingRecommendation == null ? 43 : $packingRecommendation.hashCode());
        final java.lang.Object $priority = this.getPriority();
        result = result * PRIME + ($priority == null ? 43 : $priority.hashCode());
        final java.lang.Object $imageUrl = this.getImageUrl();
        result = result * PRIME + ($imageUrl == null ? 43 : $imageUrl.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "ParcelDTO(id=" + this.getId() + ", senderId=" + this.getSenderId() + ", senderName=" + this.getSenderName() + ", title=" + this.getTitle() + ", description=" + this.getDescription() + ", weightKg=" + this.getWeightKg() + ", widthCm=" + this.getWidthCm() + ", heightCm=" + this.getHeightCm() + ", depthCm=" + this.getDepthCm() + ", startCity=" + this.getStartCity() + ", endCity=" + this.getEndCity() + ", category=" + this.getCategory() + ", riskScore=" + this.getRiskScore() + ", packingRecommendation=" + this.getPackingRecommendation() + ", priority=" + this.getPriority() + ", imageUrl=" + this.getImageUrl() + ", status=" + this.getStatus() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ParcelDTO() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ParcelDTO(final UUID id, final UUID senderId, final String senderName, final String title, final String description, final BigDecimal weightKg, final BigDecimal widthCm, final BigDecimal heightCm, final BigDecimal depthCm, final String startCity, final String endCity, final String category, final Integer riskScore, final String packingRecommendation, final String priority, final String imageUrl, final String status) {
        this.id = id;
        this.senderId = senderId;
        this.senderName = senderName;
        this.title = title;
        this.description = description;
        this.weightKg = weightKg;
        this.widthCm = widthCm;
        this.heightCm = heightCm;
        this.depthCm = depthCm;
        this.startCity = startCity;
        this.endCity = endCity;
        this.category = category;
        this.riskScore = riskScore;
        this.packingRecommendation = packingRecommendation;
        this.priority = priority;
        this.imageUrl = imageUrl;
        this.status = status;
    }
}
