// Generated by delombok at Thu Jul 16 14:07:14 IST 2026
package com.travelcarry.ai.dto;

import lombok.*;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

public class TrackingDTO {
    private UUID id;
    private UUID bookingId;
    private BigDecimal currentLatitude;
    private BigDecimal currentLongitude;
    private String statusDescription;
    private OffsetDateTime estimatedDeliveryTime;
    private BigDecimal co2SavedKg;
    private OffsetDateTime lastUpdated;


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class TrackingDTOBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UUID id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UUID bookingId;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal currentLatitude;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal currentLongitude;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String statusDescription;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private OffsetDateTime estimatedDeliveryTime;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal co2SavedKg;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private OffsetDateTime lastUpdated;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        TrackingDTOBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TrackingDTO.TrackingDTOBuilder id(final UUID id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TrackingDTO.TrackingDTOBuilder bookingId(final UUID bookingId) {
            this.bookingId = bookingId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TrackingDTO.TrackingDTOBuilder currentLatitude(final BigDecimal currentLatitude) {
            this.currentLatitude = currentLatitude;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TrackingDTO.TrackingDTOBuilder currentLongitude(final BigDecimal currentLongitude) {
            this.currentLongitude = currentLongitude;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TrackingDTO.TrackingDTOBuilder statusDescription(final String statusDescription) {
            this.statusDescription = statusDescription;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TrackingDTO.TrackingDTOBuilder estimatedDeliveryTime(final OffsetDateTime estimatedDeliveryTime) {
            this.estimatedDeliveryTime = estimatedDeliveryTime;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TrackingDTO.TrackingDTOBuilder co2SavedKg(final BigDecimal co2SavedKg) {
            this.co2SavedKg = co2SavedKg;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TrackingDTO.TrackingDTOBuilder lastUpdated(final OffsetDateTime lastUpdated) {
            this.lastUpdated = lastUpdated;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TrackingDTO build() {
            return new TrackingDTO(this.id, this.bookingId, this.currentLatitude, this.currentLongitude, this.statusDescription, this.estimatedDeliveryTime, this.co2SavedKg, this.lastUpdated);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "TrackingDTO.TrackingDTOBuilder(id=" + this.id + ", bookingId=" + this.bookingId + ", currentLatitude=" + this.currentLatitude + ", currentLongitude=" + this.currentLongitude + ", statusDescription=" + this.statusDescription + ", estimatedDeliveryTime=" + this.estimatedDeliveryTime + ", co2SavedKg=" + this.co2SavedKg + ", lastUpdated=" + this.lastUpdated + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static TrackingDTO.TrackingDTOBuilder builder() {
        return new TrackingDTO.TrackingDTOBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UUID getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UUID getBookingId() {
        return this.bookingId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getCurrentLatitude() {
        return this.currentLatitude;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getCurrentLongitude() {
        return this.currentLongitude;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStatusDescription() {
        return this.statusDescription;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public OffsetDateTime getEstimatedDeliveryTime() {
        return this.estimatedDeliveryTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getCo2SavedKg() {
        return this.co2SavedKg;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public OffsetDateTime getLastUpdated() {
        return this.lastUpdated;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final UUID id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBookingId(final UUID bookingId) {
        this.bookingId = bookingId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCurrentLatitude(final BigDecimal currentLatitude) {
        this.currentLatitude = currentLatitude;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCurrentLongitude(final BigDecimal currentLongitude) {
        this.currentLongitude = currentLongitude;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatusDescription(final String statusDescription) {
        this.statusDescription = statusDescription;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEstimatedDeliveryTime(final OffsetDateTime estimatedDeliveryTime) {
        this.estimatedDeliveryTime = estimatedDeliveryTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCo2SavedKg(final BigDecimal co2SavedKg) {
        this.co2SavedKg = co2SavedKg;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLastUpdated(final OffsetDateTime lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof TrackingDTO)) return false;
        final TrackingDTO other = (TrackingDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$bookingId = this.getBookingId();
        final java.lang.Object other$bookingId = other.getBookingId();
        if (this$bookingId == null ? other$bookingId != null : !this$bookingId.equals(other$bookingId)) return false;
        final java.lang.Object this$currentLatitude = this.getCurrentLatitude();
        final java.lang.Object other$currentLatitude = other.getCurrentLatitude();
        if (this$currentLatitude == null ? other$currentLatitude != null : !this$currentLatitude.equals(other$currentLatitude)) return false;
        final java.lang.Object this$currentLongitude = this.getCurrentLongitude();
        final java.lang.Object other$currentLongitude = other.getCurrentLongitude();
        if (this$currentLongitude == null ? other$currentLongitude != null : !this$currentLongitude.equals(other$currentLongitude)) return false;
        final java.lang.Object this$statusDescription = this.getStatusDescription();
        final java.lang.Object other$statusDescription = other.getStatusDescription();
        if (this$statusDescription == null ? other$statusDescription != null : !this$statusDescription.equals(other$statusDescription)) return false;
        final java.lang.Object this$estimatedDeliveryTime = this.getEstimatedDeliveryTime();
        final java.lang.Object other$estimatedDeliveryTime = other.getEstimatedDeliveryTime();
        if (this$estimatedDeliveryTime == null ? other$estimatedDeliveryTime != null : !this$estimatedDeliveryTime.equals(other$estimatedDeliveryTime)) return false;
        final java.lang.Object this$co2SavedKg = this.getCo2SavedKg();
        final java.lang.Object other$co2SavedKg = other.getCo2SavedKg();
        if (this$co2SavedKg == null ? other$co2SavedKg != null : !this$co2SavedKg.equals(other$co2SavedKg)) return false;
        final java.lang.Object this$lastUpdated = this.getLastUpdated();
        final java.lang.Object other$lastUpdated = other.getLastUpdated();
        if (this$lastUpdated == null ? other$lastUpdated != null : !this$lastUpdated.equals(other$lastUpdated)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof TrackingDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $bookingId = this.getBookingId();
        result = result * PRIME + ($bookingId == null ? 43 : $bookingId.hashCode());
        final java.lang.Object $currentLatitude = this.getCurrentLatitude();
        result = result * PRIME + ($currentLatitude == null ? 43 : $currentLatitude.hashCode());
        final java.lang.Object $currentLongitude = this.getCurrentLongitude();
        result = result * PRIME + ($currentLongitude == null ? 43 : $currentLongitude.hashCode());
        final java.lang.Object $statusDescription = this.getStatusDescription();
        result = result * PRIME + ($statusDescription == null ? 43 : $statusDescription.hashCode());
        final java.lang.Object $estimatedDeliveryTime = this.getEstimatedDeliveryTime();
        result = result * PRIME + ($estimatedDeliveryTime == null ? 43 : $estimatedDeliveryTime.hashCode());
        final java.lang.Object $co2SavedKg = this.getCo2SavedKg();
        result = result * PRIME + ($co2SavedKg == null ? 43 : $co2SavedKg.hashCode());
        final java.lang.Object $lastUpdated = this.getLastUpdated();
        result = result * PRIME + ($lastUpdated == null ? 43 : $lastUpdated.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "TrackingDTO(id=" + this.getId() + ", bookingId=" + this.getBookingId() + ", currentLatitude=" + this.getCurrentLatitude() + ", currentLongitude=" + this.getCurrentLongitude() + ", statusDescription=" + this.getStatusDescription() + ", estimatedDeliveryTime=" + this.getEstimatedDeliveryTime() + ", co2SavedKg=" + this.getCo2SavedKg() + ", lastUpdated=" + this.getLastUpdated() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public TrackingDTO() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public TrackingDTO(final UUID id, final UUID bookingId, final BigDecimal currentLatitude, final BigDecimal currentLongitude, final String statusDescription, final OffsetDateTime estimatedDeliveryTime, final BigDecimal co2SavedKg, final OffsetDateTime lastUpdated) {
        this.id = id;
        this.bookingId = bookingId;
        this.currentLatitude = currentLatitude;
        this.currentLongitude = currentLongitude;
        this.statusDescription = statusDescription;
        this.estimatedDeliveryTime = estimatedDeliveryTime;
        this.co2SavedKg = co2SavedKg;
        this.lastUpdated = lastUpdated;
    }
}
