// Generated by delombok at Thu Jul 16 14:07:14 IST 2026
package com.travelcarry.ai.dto;

import lombok.*;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

public class TripDTO {
    private UUID id;
    private UUID travelerId;
    private String travelerName;
    private String startCity;
    private String endCity;
    private OffsetDateTime departureDate;
    private OffsetDateTime arrivalDate;
    private BigDecimal luggageCapacityKg;
    private BigDecimal availableSpaceKg;
    private String vehicleType;
    private String status;


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class TripDTOBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UUID id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UUID travelerId;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String travelerName;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String startCity;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String endCity;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private OffsetDateTime departureDate;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private OffsetDateTime arrivalDate;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal luggageCapacityKg;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal availableSpaceKg;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String vehicleType;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String status;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        TripDTOBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TripDTO.TripDTOBuilder id(final UUID id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TripDTO.TripDTOBuilder travelerId(final UUID travelerId) {
            this.travelerId = travelerId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TripDTO.TripDTOBuilder travelerName(final String travelerName) {
            this.travelerName = travelerName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TripDTO.TripDTOBuilder startCity(final String startCity) {
            this.startCity = startCity;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TripDTO.TripDTOBuilder endCity(final String endCity) {
            this.endCity = endCity;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TripDTO.TripDTOBuilder departureDate(final OffsetDateTime departureDate) {
            this.departureDate = departureDate;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TripDTO.TripDTOBuilder arrivalDate(final OffsetDateTime arrivalDate) {
            this.arrivalDate = arrivalDate;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TripDTO.TripDTOBuilder luggageCapacityKg(final BigDecimal luggageCapacityKg) {
            this.luggageCapacityKg = luggageCapacityKg;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TripDTO.TripDTOBuilder availableSpaceKg(final BigDecimal availableSpaceKg) {
            this.availableSpaceKg = availableSpaceKg;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TripDTO.TripDTOBuilder vehicleType(final String vehicleType) {
            this.vehicleType = vehicleType;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TripDTO.TripDTOBuilder status(final String status) {
            this.status = status;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public TripDTO build() {
            return new TripDTO(this.id, this.travelerId, this.travelerName, this.startCity, this.endCity, this.departureDate, this.arrivalDate, this.luggageCapacityKg, this.availableSpaceKg, this.vehicleType, this.status);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "TripDTO.TripDTOBuilder(id=" + this.id + ", travelerId=" + this.travelerId + ", travelerName=" + this.travelerName + ", startCity=" + this.startCity + ", endCity=" + this.endCity + ", departureDate=" + this.departureDate + ", arrivalDate=" + this.arrivalDate + ", luggageCapacityKg=" + this.luggageCapacityKg + ", availableSpaceKg=" + this.availableSpaceKg + ", vehicleType=" + this.vehicleType + ", status=" + this.status + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static TripDTO.TripDTOBuilder builder() {
        return new TripDTO.TripDTOBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UUID getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UUID getTravelerId() {
        return this.travelerId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTravelerName() {
        return this.travelerName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStartCity() {
        return this.startCity;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getEndCity() {
        return this.endCity;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public OffsetDateTime getDepartureDate() {
        return this.departureDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public OffsetDateTime getArrivalDate() {
        return this.arrivalDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getLuggageCapacityKg() {
        return this.luggageCapacityKg;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getAvailableSpaceKg() {
        return this.availableSpaceKg;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getVehicleType() {
        return this.vehicleType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final UUID id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTravelerId(final UUID travelerId) {
        this.travelerId = travelerId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTravelerName(final String travelerName) {
        this.travelerName = travelerName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStartCity(final String startCity) {
        this.startCity = startCity;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEndCity(final String endCity) {
        this.endCity = endCity;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDepartureDate(final OffsetDateTime departureDate) {
        this.departureDate = departureDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setArrivalDate(final OffsetDateTime arrivalDate) {
        this.arrivalDate = arrivalDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLuggageCapacityKg(final BigDecimal luggageCapacityKg) {
        this.luggageCapacityKg = luggageCapacityKg;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAvailableSpaceKg(final BigDecimal availableSpaceKg) {
        this.availableSpaceKg = availableSpaceKg;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setVehicleType(final String vehicleType) {
        this.vehicleType = vehicleType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof TripDTO)) return false;
        final TripDTO other = (TripDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$travelerId = this.getTravelerId();
        final java.lang.Object other$travelerId = other.getTravelerId();
        if (this$travelerId == null ? other$travelerId != null : !this$travelerId.equals(other$travelerId)) return false;
        final java.lang.Object this$travelerName = this.getTravelerName();
        final java.lang.Object other$travelerName = other.getTravelerName();
        if (this$travelerName == null ? other$travelerName != null : !this$travelerName.equals(other$travelerName)) return false;
        final java.lang.Object this$startCity = this.getStartCity();
        final java.lang.Object other$startCity = other.getStartCity();
        if (this$startCity == null ? other$startCity != null : !this$startCity.equals(other$startCity)) return false;
        final java.lang.Object this$endCity = this.getEndCity();
        final java.lang.Object other$endCity = other.getEndCity();
        if (this$endCity == null ? other$endCity != null : !this$endCity.equals(other$endCity)) return false;
        final java.lang.Object this$departureDate = this.getDepartureDate();
        final java.lang.Object other$departureDate = other.getDepartureDate();
        if (this$departureDate == null ? other$departureDate != null : !this$departureDate.equals(other$departureDate)) return false;
        final java.lang.Object this$arrivalDate = this.getArrivalDate();
        final java.lang.Object other$arrivalDate = other.getArrivalDate();
        if (this$arrivalDate == null ? other$arrivalDate != null : !this$arrivalDate.equals(other$arrivalDate)) return false;
        final java.lang.Object this$luggageCapacityKg = this.getLuggageCapacityKg();
        final java.lang.Object other$luggageCapacityKg = other.getLuggageCapacityKg();
        if (this$luggageCapacityKg == null ? other$luggageCapacityKg != null : !this$luggageCapacityKg.equals(other$luggageCapacityKg)) return false;
        final java.lang.Object this$availableSpaceKg = this.getAvailableSpaceKg();
        final java.lang.Object other$availableSpaceKg = other.getAvailableSpaceKg();
        if (this$availableSpaceKg == null ? other$availableSpaceKg != null : !this$availableSpaceKg.equals(other$availableSpaceKg)) return false;
        final java.lang.Object this$vehicleType = this.getVehicleType();
        final java.lang.Object other$vehicleType = other.getVehicleType();
        if (this$vehicleType == null ? other$vehicleType != null : !this$vehicleType.equals(other$vehicleType)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof TripDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $travelerId = this.getTravelerId();
        result = result * PRIME + ($travelerId == null ? 43 : $travelerId.hashCode());
        final java.lang.Object $travelerName = this.getTravelerName();
        result = result * PRIME + ($travelerName == null ? 43 : $travelerName.hashCode());
        final java.lang.Object $startCity = this.getStartCity();
        result = result * PRIME + ($startCity == null ? 43 : $startCity.hashCode());
        final java.lang.Object $endCity = this.getEndCity();
        result = result * PRIME + ($endCity == null ? 43 : $endCity.hashCode());
        final java.lang.Object $departureDate = this.getDepartureDate();
        result = result * PRIME + ($departureDate == null ? 43 : $departureDate.hashCode());
        final java.lang.Object $arrivalDate = this.getArrivalDate();
        result = result * PRIME + ($arrivalDate == null ? 43 : $arrivalDate.hashCode());
        final java.lang.Object $luggageCapacityKg = this.getLuggageCapacityKg();
        result = result * PRIME + ($luggageCapacityKg == null ? 43 : $luggageCapacityKg.hashCode());
        final java.lang.Object $availableSpaceKg = this.getAvailableSpaceKg();
        result = result * PRIME + ($availableSpaceKg == null ? 43 : $availableSpaceKg.hashCode());
        final java.lang.Object $vehicleType = this.getVehicleType();
        result = result * PRIME + ($vehicleType == null ? 43 : $vehicleType.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "TripDTO(id=" + this.getId() + ", travelerId=" + this.getTravelerId() + ", travelerName=" + this.getTravelerName() + ", startCity=" + this.getStartCity() + ", endCity=" + this.getEndCity() + ", departureDate=" + this.getDepartureDate() + ", arrivalDate=" + this.getArrivalDate() + ", luggageCapacityKg=" + this.getLuggageCapacityKg() + ", availableSpaceKg=" + this.getAvailableSpaceKg() + ", vehicleType=" + this.getVehicleType() + ", status=" + this.getStatus() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public TripDTO() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public TripDTO(final UUID id, final UUID travelerId, final String travelerName, final String startCity, final String endCity, final OffsetDateTime departureDate, final OffsetDateTime arrivalDate, final BigDecimal luggageCapacityKg, final BigDecimal availableSpaceKg, final String vehicleType, final String status) {
        this.id = id;
        this.travelerId = travelerId;
        this.travelerName = travelerName;
        this.startCity = startCity;
        this.endCity = endCity;
        this.departureDate = departureDate;
        this.arrivalDate = arrivalDate;
        this.luggageCapacityKg = luggageCapacityKg;
        this.availableSpaceKg = availableSpaceKg;
        this.vehicleType = vehicleType;
        this.status = status;
    }
}
