// Generated by delombok at Thu Jul 16 14:07:14 IST 2026
package com.travelcarry.ai.dto;

import lombok.*;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;

public class WalletDTO {
    private UUID id;
    private UUID userId;
    private BigDecimal balance;
    private String currency;
    private List<WalletHistoryDTO> history;


    public static class WalletHistoryDTO {
        private UUID id;
        private BigDecimal amount;
        private String type;
        private String description;
        private OffsetDateTime createdAt;


        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public static class WalletHistoryDTOBuilder {
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            private UUID id;
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            private BigDecimal amount;
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            private String type;
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            private String description;
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            private OffsetDateTime createdAt;

            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            WalletHistoryDTOBuilder() {
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public WalletDTO.WalletHistoryDTO.WalletHistoryDTOBuilder id(final UUID id) {
                this.id = id;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public WalletDTO.WalletHistoryDTO.WalletHistoryDTOBuilder amount(final BigDecimal amount) {
                this.amount = amount;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public WalletDTO.WalletHistoryDTO.WalletHistoryDTOBuilder type(final String type) {
                this.type = type;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public WalletDTO.WalletHistoryDTO.WalletHistoryDTOBuilder description(final String description) {
                this.description = description;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public WalletDTO.WalletHistoryDTO.WalletHistoryDTOBuilder createdAt(final OffsetDateTime createdAt) {
                this.createdAt = createdAt;
                return this;
            }

            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public WalletDTO.WalletHistoryDTO build() {
                return new WalletDTO.WalletHistoryDTO(this.id, this.amount, this.type, this.description, this.createdAt);
            }

            @java.lang.Override
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public java.lang.String toString() {
                return "WalletDTO.WalletHistoryDTO.WalletHistoryDTOBuilder(id=" + this.id + ", amount=" + this.amount + ", type=" + this.type + ", description=" + this.description + ", createdAt=" + this.createdAt + ")";
            }
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public static WalletDTO.WalletHistoryDTO.WalletHistoryDTOBuilder builder() {
            return new WalletDTO.WalletHistoryDTO.WalletHistoryDTOBuilder();
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public UUID getId() {
            return this.id;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public BigDecimal getAmount() {
            return this.amount;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public String getType() {
            return this.type;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public String getDescription() {
            return this.description;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public OffsetDateTime getCreatedAt() {
            return this.createdAt;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setId(final UUID id) {
            this.id = id;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setAmount(final BigDecimal amount) {
            this.amount = amount;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setType(final String type) {
            this.type = type;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setDescription(final String description) {
            this.description = description;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setCreatedAt(final OffsetDateTime createdAt) {
            this.createdAt = createdAt;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof WalletDTO.WalletHistoryDTO)) return false;
            final WalletDTO.WalletHistoryDTO other = (WalletDTO.WalletHistoryDTO) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$id = this.getId();
            final java.lang.Object other$id = other.getId();
            if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
            final java.lang.Object this$amount = this.getAmount();
            final java.lang.Object other$amount = other.getAmount();
            if (this$amount == null ? other$amount != null : !this$amount.equals(other$amount)) return false;
            final java.lang.Object this$type = this.getType();
            final java.lang.Object other$type = other.getType();
            if (this$type == null ? other$type != null : !this$type.equals(other$type)) return false;
            final java.lang.Object this$description = this.getDescription();
            final java.lang.Object other$description = other.getDescription();
            if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
            final java.lang.Object this$createdAt = this.getCreatedAt();
            final java.lang.Object other$createdAt = other.getCreatedAt();
            if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof WalletDTO.WalletHistoryDTO;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $id = this.getId();
            result = result * PRIME + ($id == null ? 43 : $id.hashCode());
            final java.lang.Object $amount = this.getAmount();
            result = result * PRIME + ($amount == null ? 43 : $amount.hashCode());
            final java.lang.Object $type = this.getType();
            result = result * PRIME + ($type == null ? 43 : $type.hashCode());
            final java.lang.Object $description = this.getDescription();
            result = result * PRIME + ($description == null ? 43 : $description.hashCode());
            final java.lang.Object $createdAt = this.getCreatedAt();
            result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "WalletDTO.WalletHistoryDTO(id=" + this.getId() + ", amount=" + this.getAmount() + ", type=" + this.getType() + ", description=" + this.getDescription() + ", createdAt=" + this.getCreatedAt() + ")";
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public WalletHistoryDTO() {
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public WalletHistoryDTO(final UUID id, final BigDecimal amount, final String type, final String description, final OffsetDateTime createdAt) {
            this.id = id;
            this.amount = amount;
            this.type = type;
            this.description = description;
            this.createdAt = createdAt;
        }
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class WalletDTOBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UUID id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UUID userId;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private BigDecimal balance;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String currency;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private List<WalletHistoryDTO> history;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        WalletDTOBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public WalletDTO.WalletDTOBuilder id(final UUID id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public WalletDTO.WalletDTOBuilder userId(final UUID userId) {
            this.userId = userId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public WalletDTO.WalletDTOBuilder balance(final BigDecimal balance) {
            this.balance = balance;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public WalletDTO.WalletDTOBuilder currency(final String currency) {
            this.currency = currency;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public WalletDTO.WalletDTOBuilder history(final List<WalletHistoryDTO> history) {
            this.history = history;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public WalletDTO build() {
            return new WalletDTO(this.id, this.userId, this.balance, this.currency, this.history);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "WalletDTO.WalletDTOBuilder(id=" + this.id + ", userId=" + this.userId + ", balance=" + this.balance + ", currency=" + this.currency + ", history=" + this.history + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static WalletDTO.WalletDTOBuilder builder() {
        return new WalletDTO.WalletDTOBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UUID getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UUID getUserId() {
        return this.userId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getBalance() {
        return this.balance;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCurrency() {
        return this.currency;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<WalletHistoryDTO> getHistory() {
        return this.history;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final UUID id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUserId(final UUID userId) {
        this.userId = userId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBalance(final BigDecimal balance) {
        this.balance = balance;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCurrency(final String currency) {
        this.currency = currency;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setHistory(final List<WalletHistoryDTO> history) {
        this.history = history;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof WalletDTO)) return false;
        final WalletDTO other = (WalletDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$userId = this.getUserId();
        final java.lang.Object other$userId = other.getUserId();
        if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId)) return false;
        final java.lang.Object this$balance = this.getBalance();
        final java.lang.Object other$balance = other.getBalance();
        if (this$balance == null ? other$balance != null : !this$balance.equals(other$balance)) return false;
        final java.lang.Object this$currency = this.getCurrency();
        final java.lang.Object other$currency = other.getCurrency();
        if (this$currency == null ? other$currency != null : !this$currency.equals(other$currency)) return false;
        final java.lang.Object this$history = this.getHistory();
        final java.lang.Object other$history = other.getHistory();
        if (this$history == null ? other$history != null : !this$history.equals(other$history)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof WalletDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $userId = this.getUserId();
        result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
        final java.lang.Object $balance = this.getBalance();
        result = result * PRIME + ($balance == null ? 43 : $balance.hashCode());
        final java.lang.Object $currency = this.getCurrency();
        result = result * PRIME + ($currency == null ? 43 : $currency.hashCode());
        final java.lang.Object $history = this.getHistory();
        result = result * PRIME + ($history == null ? 43 : $history.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "WalletDTO(id=" + this.getId() + ", userId=" + this.getUserId() + ", balance=" + this.getBalance() + ", currency=" + this.getCurrency() + ", history=" + this.getHistory() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public WalletDTO() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public WalletDTO(final UUID id, final UUID userId, final BigDecimal balance, final String currency, final List<WalletHistoryDTO> history) {
        this.id = id;
        this.userId = userId;
        this.balance = balance;
        this.currency = currency;
        this.history = history;
    }
}
